### ISSUE TITLE
How to Send a Video To reportportal 

### ISSUE THREAD

**Issue by dharma-keyutech** [reportportal/reportportal#1014]
Can any one guide how to display video of our test scripts into reportportal logs section

**Comment by evjlobanova** [comment]
@dharma-keyutech if you are using SauceLabs, we can propose to configure a SauceLAbs integration https://reportportal.io/docs/Sauce-Labs-integration

In this case, you will see a video right in ReportPortal.

Otherwise, you can attach video files to execution as simple attachments, but for viewing it, you should firstly download it.

There is one more option, if you store your video in the cloud, you can add a link to the video to the logs. Markdown will recognize it as a link, and you will be able to click on it.

**Comment by dharma-keyutech** [comment]
can you Explain how we can display our total script exection video  in Logs section

**Comment by evjlobanova** [comment]
@dharma-keyutech do you want to attach a video file to execution or do you want to view the video on log view in test execution?

**Comment by evjlobanova** [comment]
Here you can find a dev guide on how to attach a file to test executions
https://github.com/reportportal/documentation/blob/master/src/md/src/DevGuides/reporting.md#batch-save-logs

Which agent do you use for reporting?

**Comment by dharma-keyutech** [comment]
> @dharma-keyutech do you want to attach a video file to execution or do you want to view the video on log view in test execution?

I need Guidence for  video on log view in test execution?

**Comment by OscarCarrilloTR** [comment]
Where you able to record your tests and show them in ReportPortal?
