### ISSUE TITLE
Import Log and Attach Screenshot

### ISSUE THREAD

**Issue by priyankachaturvedi30** [reportportal/reportportal#1036]
I have been using Import feature(https://reportportal.io/docs/Import-data-to) to add logs for one of my projects containing some 200 testcases. Now, as my testcases grew in number I have a need to attach screenshots as well in order to categorize and access the failures more accurately. I have gone through the API endpoint `/v1/{projectName}/log` to attach attachments. Now the issue is both the launchUuid and itemUuid are generated at runtime (Attached json image for reference), and i have ~200 cases been imported and corresponding screenshots to each case to be attached. How can I achieve it by using a combination of Import feature (to import logs) and API(to attach screenshots corresponding to the logs which are getting imported)?
![image](https://user-images.githubusercontent.com/50797731/85716340-fae32400-b709-11ea-8295-226cade6c46a.png)

**Comment by evjlobanova** [comment]
@priyankachaturvedi30, for now, the Import feature has very low priority. Our main feature is real-time reporting.
We have checked this issue, and try to investigate a root cause

**Comment by priyankachaturvedi30** [comment]
Yes Sure. I understand. Just curious to know if we can somehow make use of a combination of both import feature(for logs) and API (for screenshot) call to achieve logs along with the screenshots.

**Comment by sspieker-cc** [comment]
@priyankachaturvedi30 - We have had some issues with the ReportPortal tooling not reporting the correct number of test cases for JUnit tests when using a non-standard runner (Mockito for example).  So to circumvent these kinds of issues and to standardize our CICD pipeline, we have implemented a java library that interfaces with the API endpoint.  The client-java.jar file would probably work instead of build-your-own but in our case we had built one.  We are using RP 5 and interact with the API entirely for the processes of importing the launch, updating the launch details (launch controller) (description, tags, etc.) and then finally attaching files (log controller) to the launch, suite and even the testcase (testitem controller).

Anyway, our solution was multi-fold.  We wanted to upload / import test cases from our Jenkins server runs as well as docker test packages run in our various environments and datacenters.  We have created an S3 bucket that would allow access from the environments as well as from Jenkins.  This bucket it just a filestore and the results of all executions are zipped up JUnit files (as you know since you are using this feature now).

There is a reportportal.properties file that is created with the docker images and the entrypoint script does the work of executing the tests as well as putting the results in the correct location.  There is filename pattern that we use to keep results from the various environments and executions unique - again, handled by the entrypoint script within the container.  These files are dropped into the bucket and the container is destroyed.  A zip file contains the test results XML, there is a properties file to contain the launch name, User UUID, project, description and tags to be associated with the launch.  Any other files (your screenshots, stdout, stderr files, etc.) are then also dropped into the bucket with the filename patterns to keep them isolated from each other.

We had then written a directory watcher application that is multi-threaded and uses the observer / observable patterns to have a list of files to be imported and the associated properties files.  Once these files are found and import is completed, the utility class looks for any support files (of any type) that match the filename pattern (datestamp_testsuite_testcase_filename_counter.extension) and then utilize the java library to interact with the API all the way through.  Querying the TestItem controller, Log Controller and Launch controllers.  These operations allow for us to use a single tool to perform the reporting of test results regardless of language, platform, etc.

Although this is an in-house solution, it would be fairly smooth to create a collection within postman, rest assured, or some other tool to perform the operations as you had queried.  Long story short, yes, it is do-able and now that we have worked out the process it is 'pretty' easy though the swagger API documentation leaves much to be desired in terms of request and response information via the UI.

I am happy to help with some guidance if you are interested.
