### ISSUE TITLE
Unable to set Sendgrid smtp to email server integration[v5]

### ISSUE THREAD

**Issue by Tumite** [reportportal/reportportal#1060]
**Describe the bug**
I would like to add sendgrid smtp user to email server integration but i can't. I got this message: https://i.imgur.com/sChJWDA.png

**Additional context**
I also tried with Yandex account but didn't work.
https://i.imgur.com/ogTkxHp.png

**Comment by evjlobanova** [comment]
@e-olga @VolhaKarenko Could you please check this issue?

**Comment by VolhaKarenko** [comment]
Integration with Yandex account works without issues on version 5.0.
@Tumite Yandex issue on the screenshot seems to be not on our side. Could you please check your Yandex account settings for any connection restrictions?
The issue with Sendgrid may occur due to invalid configuration. Please see the email server integration guide: https://reportportal.io/docs/E-mail-server-integration
Note the format of 'Host' and 'Username' fields.
