### ISSUE TITLE
API hits max connections limit on Postgres DB

### ISSUE THREAD

**Issue by jlundy2** [reportportal/reportportal#1062]
When test results are sent to the report portal API, the application opens a ton of db connections and then there's contention for them and then for instance, UAT can't connect to the database.
 Errors are thrown by the api and uat of the form: `Could not open JPA EntityManager for transaction; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection`

I can't log into the db server to take a look at what connections are actually causing the issue.

**Comment by evjlobanova** [comment]
@e-olga Olga, could you please create a bug to release 5.3.1

**Comment by evjlobanova** [comment]
Pull request https://github.com/reportportal/service-api/pull/1252

@Yumfriez Could you please describe the proposed decision?

**Comment by Yumfriez** [comment]
@jlundy2 

https://github.com/reportportal/service-api/pull/1252 In this PR properties of the thread pool executors were made modifiable.

RP_DATASOURCE_MAXIMUMPOOLSIZE - specifies the connection pool size of the `api` service. BY DEFAULT - 27. 
Notice that `api` and `uat` services acquire 27 connections each. Also default connection pool size from the PostgreSQL size = 100 connections.

RP_ENVIRONMENT_VARIABLE_EXECUTOR_POOL_SAVE_LOGS_MAX - maximum pool size of the async executor that saves logs and attachment in RP instance. Each executor thread acquires 1 DB connection, so this value should be less then RP_DATASOURCE_MAXIMUMPOOLSIZE (Try to set it to 20. You can set higher value if you want to increase DB connection pool size from 27 to higher value).
 
RP_ENVIRONMENT_VARIABLE_EXECUTOR_POOL_SAVE_LOGS_CORE - core pool size (20 by default). This variable can be left as it is, because acquired DB connections maximum count limited by the RP_ENVIRONMENT_VARIABLE_EXECUTOR_POOL_SAVE_LOGS_MAX variable.

RP_ENVIRONMENT_VARIABLE_EXECUTOR_POOL_SAVE_LOGS_QUEUE=5000 - also async executor config param that can be left unchanged. It corresponds for the attachments queue that will be consumed by executor threads.

So the main idea is to have RP_ENVIRONMENT_VARIABLE_EXECUTOR_POOL_SAVE_LOGS_MAX `less than` RP_DATASOURCE_MAXIMUMPOOLSIZE

**Comment by jlundy2** [comment]
Hello, upgrading to the latest images, etc. I get the following error on startup:

` ERROR 6 --- [ main] o.s.b.web.embedded.tomcat.TomcatStarter : Error starting Tomcat context. Exception: org.springframework.beans.factory.BeanCreationException. Message: Error creating bean with name 'servletEndpointRegistrar' defined in class path resource [org/springframework/boot/actuate/autoconfigure/endpoint/web/ServletEndpointManagementContextConfiguration$WebMvcServletEndpointManagementContextConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.actuate.endpoint.web.ServletEndpointRegistrar]: Factory method 'servletEndpointRegistrar' threw exception; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'healthEndpoint' defined in class path resource [org/springframework/boot/actuate/autoconfigure/health/HealthEndpointConfiguration.class]: Unsatisfied dependency expressed through method 'healthEndpoint' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'healthContributorRegistry' defined in class path resource [org/springframework/boot/actuate/autoconfigure/health/HealthEndpointConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.actuate.health.HealthContributorRegistry]: Factory method 'healthContributorRegistry' threw exception; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'rabbitHealthContributor' defined in class path resource [org/springframework/boot/actuate/autoconfigure/amqp/RabbitHealthContributorAutoConfiguration.class]: Unsatisfied dependency expressed through method 'rabbitHealthContributor' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'rabbitTemplate' defined in class path resource [com/epam/ta/reportportal/core/configs/rabbit/RabbitMqConfiguration.class]: Unsatisfied dependency expressed through method 'rabbitTemplate' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'connectionFactory' defined in class path resource [com/epam/ta/reportportal/core/configs/rabbit/RabbitMqConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.amqp.rabbit.connection.ConnectionFactory]: Factory method 'connectionFactory' threw exception; nested exception is java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0`

**Comment by avarabyeu** [comment]
@jlundy2 @Yumfriez isn't the error related to RabbitMQ misconfiguration?

**Comment by Yumfriez** [comment]
@avarabyeu Yes, probably outdated version of `docker-compose.yml` was used. @jlundy2 Try to use the latest file with provided `RabbitMq` credentials:
https://github.com/reportportal/reportportal/blob/master/docker-compose.yml

**Comment by jlundy2** [comment]
Thanks @avarabyeu and @Yumfriez, I upgraded to 5.3.0 successfully yesterday with the rabbitMQ credentials setup correctly and the upgrade worked properly. I'd really like to see #reportportal/service-authorization!187 and #reportportal/service-api!1261 resolved so these passwords don't have to be written into the compose file for a real deployment.
For the point of this ticket, I switched my connection to be direct instead of through an SSH tunnel and the issue looks to be resolved.
