### ISSUE TITLE
Report portal rendering is very slow in UI

### ISSUE THREAD

**Issue by harshagv12** [reportportal/reportportal#1081]
Application is launched from docker compose, but UI rendering is very slow. How to increase the docker memory.
Below is the system configuration where we hosted the report portal,

OS : Ubuntu 18
CPU : 32 
Memory: 64G 
Storage:  1 TB.

**Comment by evjlobanova** [comment]
Please follow the steps to improve issue with performance, and let us know if it helps https://reportportal.io/docs/How-to-resolve
cc @irynakozak2

**Comment by harshagv12** [comment]
We still sufficient storage where we hosted the docker composer for report portal. Below is the config details,
fvt@bulfct04:~$ df -h
Filesystem                                                Size  Used Avail Use% Mounted on
udev                                                      7.9G     0  7.9G   0% /dev
tmpfs                                                     1.6G  1.9M  1.6G   1% /run
**/dev/sda2                                                 206G   60G  136G  31% /**
tmpfs                                                     7.9G     0  7.9G   0% /dev/shm
tmpfs                                                     5.0M     0  5.0M   0% /run/lock
tmpfs                                                     7.9G     0  7.9G   0% /sys/fs/cgroup

Can you help use to locate the docker config file where cpu and ram is defined. So that we can increase the resource

**Comment by irynakozak2** [comment]
@harshagv12 Hello, by default, a container has no resource constraints and can use as much of a given resource as the host’s kernel scheduler allows, but you can increase Java Heap Memory for speed up the service-api(in the default Docker installation we have -Xmx1g) so that increasing this parameter will improve the RP performance and allows to use more RAM resource.
Could you please specify the version of the ReportPortal which you use and deployment(Docker or Kubernetes)?

**Comment by harshagv12** [comment]
We have deployed the report portal from docker with report portal version 5.0.0

**Comment by irynakozak2** [comment]
@harshagv12 could you please let us know if increasing the Xmx option help you to solve the issue?
