### ISSUE TITLE
differentiate how long we keep test results, versus test logs

### ISSUE THREAD

**Issue by mihtac** [reportportal/reportportal#1086]
**Describe the solution you'd like**
I'd like to be able to keep historical results (pass/fail numbers) for a longer amount of time (months), but keep the log entries (per test) for a lower time (a month?) - to save space on the backup.

**Is your feature request related to a problem? Please describe.**
We're having issues with upgrading to a newer version, as the backup we currently have doesn't fit in our artefactory...

**Comment by Kozovskaya** [comment]
Hello @mihtac,
In Project settings - General tab, you can configure different retention policy for launches, logs and attachments.
You can choose 'Keep launches' for 3 months (for example) and keep logs (30 days). 
After 30 days the logs will be deleted, launch structure will be saved in order to keep statistics.
![image](https://github.com/reportportal/reportportal/assets/106231727/2b6fb0e0-506d-4169-a2bb-f7ca7ec519e0)
