### ISSUE TITLE
[v5] Defect types not updating instantly and take too long time 

### ISSUE THREAD

**Issue by tharindu99** [reportportal/reportportal#1098]
**Describe the bug**
Under the test case investigation, if we change defect type it will not appear when we click save button. But after a few minutes later it will update. 

**Expected behavior**
When we change something and click the save button, it should appear instantly.

**Comment by Brrovko** [comment]
Faced with the same issue. Ignore in Auto Analysis helps to changes defect type immediately.

**Comment by evjlobanova** [comment]
@tamasmartin @Brrovko please check firstly steps for performance improvement https://reportportal.io/docs/How-to-resolve

If issue is still reproduced, please let us know, we will proceed with investigations

**Comment by evjlobanova** [comment]
@irynakozak2 could you please keep an eye on this issue

**Comment by irynakozak2** [comment]
@tharindu99 hello, on latest RP version(5.3) we've fixed the same issue, as you've described, and as for now, update the defect type for the set of items should appear on 3-4sec for 155 items count. The point regarding reducing this response time to almost immediately I've already checked and confirmed(this behavior occurs because update defect type affects the elasticsearch analyzer resources, and also rabbitmq connection, by which service-api and analyzer communicate).
I've already raised ticket to our backlog to investigate a possible solution to reduce that response time, thanks a lot!

**Comment by heilwood** [comment]
Same issue on 5.3.1, changing defect type, started index regeneration which is to slow, when regeneration finished defect types updated.

**Comment by akeshmiri** [comment]
Greetings,

I just start a new instance with about 100 launches in it and I need to wait about 10 minutes every time a changing defect type.
Current version:API Service: 5.3.5;Index Service: 5.0.10;Authorization Service: 5.3.5;Service UI: 5.3.5

**Comment by akeshmiri** [comment]
Hi @evjlobanova, 
any thought on this?
Shall we reopen the bug or create a new one?

**Comment by evjlobanova** [comment]
@akeshmiri it can be connected with your instance configuration? Could you please check if your configuration is chosen in accordance with our system requirements:
https://reportportal.io/docs/Optimal-Performance-Hardware%3E1-disk-i-o

**Comment by irynakozak2** [comment]
@akeshmiri in version 5.4.1 we made refactoring for the best performance of the Defect Types updating and made this process async and it will allow us to update the defect types almost immediately.

**Comment by evjlobanova** [comment]
We are planning to release 5.4 this month
And 5.4.1 will come ±2 weeks after 5.4

**Comment by akeshmiri** [comment]
Thank you @evjlobanova and @irynakozak2 for the update.
You are your team doing a fantastic job to support this.
looking forward to getting 5.4.

Best luck to you
