### ISSUE TITLE
Feature Request: Allow for the addition of multiple shared widgets to a dashboard through UI

### ISSUE THREAD

**Issue by sspieker-cc** [reportportal/reportportal#1108]
Currently (V5.2.3) the UI has the option to only add a single shared widget at a time (Radio button selection type).  If this were changed to a checkbox selection type we can filter down to a group of widgets and add them as an array to the dashboard.

This step would help facilitate creating dashboards that are to summarize data for different environments.  For example, having one dashboard with the same layout and widget definitions (with different filter criteria) for DEV, QA, Staging, Production, UAT, etc.

The current workflow is to:

1. Generate filters manually for each environment and test suites to be included in the filter.
2. Add the Passing rate summary widget with the dev filter (via UI and record the filter ID and body of the widget creation request).  The names of the filters and widgets are similar (<Suite> Launch Name Filter, <Suite> - <Environment> Widget)
3. Add a method in Postman to allow for the creation of this widget for each following environment, adjusting the filter ID and Name as well as the Widget name.  Run the request for each additional environment appropriately.
4. Add the Overall Statistics widget with the dev filter (Follow the postman steps above with the body of the overall statistics type)
5. Add the Next widget following the same process, etc.
6. Return to Dashboard and choose add Shared Widget and search based on suite and environment to find an abbreviated list of widgets.
7. Select one widget and "add".
8. Size and Arrange widget
9. Repeat steps 6-8 for each widget

The hope is that the selected **widgets** would then be added to the dashboard either to the top (the default current behavior with position 0,0 as the default placement) or be appended to the end of the existing dashboard widgets.  This feature request is looking to cut out the number of manual steps required in #9 above.  The size and arrange step would encompass all of the existing widgets instead of repeating that step on existing widgets as well as the newly added widget as well.

Addition of the widgets would hopefully performed in the order in which they are selected from the list then arrangement and sizing would happen after the selected group(s) are added.

**Comment by evjlobanova** [comment]
Thank you for request
For now we have a little bit another vision for dashboard growth in future.
We are planning to create a self updated dashboard.
![image](https://user-images.githubusercontent.com/30413511/90634422-56282300-e230-11ea-962c-21b08b680000.png)
That helps you to reduce number of dashboards.
But this is an idea for future development.

Possible solutions for now:
1. For now 3 widgets can reduce your manual work:
* Cumulative trend chart
* Component Health Check widget
* Component Health Check widget (table view)

This widgets are based on attributes and you can use them without filter update. 


2. Create several dashboards for different envs, add filter and widgets.
And add API call to pipeline for filter update.
So that all your widgets and dashboards will be updated automatically.

What do you think about it?
