### ISSUE TITLE
testng report upload 

### ISSUE THREAD

**Issue by tharindu99** [reportportal/reportportal#1110]
**Describe the solution you'd like**
If we can introduce testng file upload for launches that would make an added advantage. 

**Is your feature request related to a problem? Please describe.**
At the movement, we can use an agent for a similar situation but it can be worst when we got issue and we will be lost our manual control.

**Comment by evjlobanova** [comment]
@tharindu99 thank you for request
For now expert is a feature with minoк priority
The main advantage of reportportal is real-time reporting. So that our focus now is on real-time reporting.

It is a little bit unclear for us, what you mean under "e will be lost our manual control". Could you please clarify your use case?
