### ISSUE TITLE
[v5] Logs not ordered by timestamp

### ISSUE THREAD

**Issue by mnicula** [reportportal/reportportal#1138]
**Describe the bug**
Logs are not ordered by timestamp

**Screenshots**
![image](https://user-images.githubusercontent.com/48491734/92393057-e9fe5800-f127-11ea-825b-bfd50be48c4e.png)

**Comment by HardNorth** [comment]
@mnicula They are not supposed to be ordered by a timestamp inside log, since it's a pure text information and we do not parse it (we are not an "Elasticsearch"). They are usually ordered by the order in which they come to our logger, which sets an event timestamp in milliseconds. Everything else is on conscience of your logging framework, how long it will pass a message to our logger.

For Java agents it's possible to directly control our internal timestamp by calling this method directly:
https://github.com/reportportal/client-java/blob/develop/src/main/java/com/epam/reportportal/service/ReportPortal.java#L356

If you are using another language then tell me which. I can refer you to a corresponding expert.

**Comment by nvborisenko** [comment]
I think demonstrated timestamp is a part of CreateLogItemRequest.  On the picture I also see nested steps.

**Comment by mnicula** [comment]
@nvborisenko you are right.

**Comment by mnicula** [comment]
@HardNorth I understand, but in our case, every log entry is an step from the test. Mixing them creates confusion. Please suggest an solution to avoid this. Thanks!

**Comment by HardNorth** [comment]
@mnicula so, are you using a .Net agent?

**Comment by mnicula** [comment]
@HardNorth no, .net client

**Comment by HardNorth** [comment]
@nvborisenko Do you have any methods inside client which allows to bypass event timestamps?

**Comment by mnicula** [comment]
@HardNorth this is the client I'm using [net-client](https://github.com/reportportal/client-net). I don't think there is such method, as the client is just sending http requests to the API. @nvborisenko , please correct me if I'm wrong.

**Comment by nvborisenko** [comment]
https://github.com/reportportal/client-net/blob/b08034cef71ebec43d5f94227e2be52123789807/test/ReportPortal.Client.IntegrationTests/LogItem/LogItemFixture.cs#L37

Using client you should provide `Time` property, timezone is UTC.

**Comment by mnicula** [comment]
@nvborisenko i do provide the Time property, and I see it's value on UI. the problem is that they are not ordered))

**Comment by evjlobanova** [comment]
@AmsterGet please check

**Comment by mnicula** [comment]
@AmsterGet , @evjlobanova  any updates on this?

**Comment by mnicula** [comment]
I tried also with sending the logs in batch, same issue.
![image](https://user-images.githubusercontent.com/48491734/97009287-9798bf80-154c-11eb-91ec-31707439e4ca.png)

**Comment by VeranikaRymzha** [comment]
Hello @mnicula,
Sorry for coming back to you late.

At the moment logger sets a timestamp at the time of log sending rather than at the time the log was created.
As Analyzer doesn't support time in messages and we don't take into consideration this parameter at the time of analysis, we don't plan to change it in the near future. Thus, we highly recommend you not to log time in ReportPortal.

Please, let us know if there are any other questions.
