### ISSUE TITLE
How to remove "EPAM" text from the bottom of the report portal UI

### ISSUE THREAD

**Issue by gopikishan1995** [reportportal/reportportal#1158]
How to remove "EPAM" text from the bottom of the report portal UI

**Comment by evjlobanova** [comment]
hello, why you want to remove EPAM name?

**Comment by gopikishan1995** [comment]
Due to contractual obligations with our clients

**Comment by DzmitryHumianiuk** [comment]
@gopikishan1995 ReportPortal is an open source solution available to everyone for free.

EPAM Systems is an original company where solution was founded. 
In 2016 EPAM shared it's intellectual property with community via open sourcing.
Now EPAM is major sponsor and contributor into the solution.

Copyright belongs to EPAM Systems, and it's distributed under Apache License.
`
The Apache License is permissive; it does not require a derivative work of the software, or modifications to the original, to be distributed using the same license. It still requires application of the same license to all unmodified parts. In every licensed file, original copyright, patent, trademark, and attribution notices must be preserved (excluding notices that do not pertain to any part of the derivative works). In every licensed file changed, a notification must be added stating that changes have been made to that file.
`

In case of any obligations, your company can obtain commercial license for ReportPortal solution, in order to meet any contractual limitations.
Please contact us for details at 
![image](https://user-images.githubusercontent.com/11332788/94433011-5658fe00-01a0-11eb-9bcf-7ddd69a54490.png)

**Comment by gopikishan1995** [comment]
Thank you :) for the info.
