### ISSUE TITLE
Unable to capture screenshots into report portal for mobile framework through appium driver

### ISSUE THREAD

**Issue by gopikishan1995** [reportportal/reportportal#1171]
Using this below method we are not able to capture screenshots into report portal through appium driver
below is the screenshot method i am using for mobile and it is working fine for Web framework

 // Take screenshots into report portal
		public static ReportPortalMessage ScreenShot(AppiumDriver appiumDriver) {

				 ReportPortalMessage message = null;
				    try {
				    	TakesScreenshot ts = (TakesScreenshot) appiumDriver;
				    	File srcFile = ts.getScreenshotAs(OutputType.FILE);
				    	java.util.Date d= new java.util.Date();
				    	 org.apache.commons.io.FileUtils.copyFile(srcFile, new File("./ScreenShots/"+d.toString().replace(":", "_")+".png"));
				    	String rp_message = "";//test message for ReportPortal
				        message = new ReportPortalMessage(srcFile, rp_message);
				    } catch (IOException e) {
				        e.printStackTrace();
				        LOGGER.error(e);
				    }
				    LOGGER.info(message);
				    return message;
			}

**Comment by evjlobanova** [comment]
@HardNorth Vadzim, could you please help with this issue?

**Comment by gopikishan1995** [comment]
Hi Team,
any update on above ?

**Comment by gopikishan1995** [comment]
Can someone please help on this,

**Comment by mgubanov** [comment]
@evjlobanova hi, any updates?

**Comment by HardNorth** [comment]
Looks like I need to end it up.

There is no any issues with Report Portal code. From Report Portal standpoint it does not matter which tool users are using to take screenshot: WebDriver, Appium, Playwright, etc. It takes Files or Bytes and if there is no Files or Bytes logs nothing. We are reporting tool, we do not fail execution in case we meet unusual situation, so that's why screenshots just disappear. But if the logic would be broken it will be broken for any tool, not just for Appium.

There are three most common mistakes there:
1. Incorrect folder from which screenshot is taken: Just use `BASE64` output type to completely avoid such mistake, as here: https://github.com/reportportal/examples-java/blob/master/example-testng-logback/src/main/java/com/epam/reportportal/example/testng/logback/extension/ScreenshotOnFailureTestExtension.java#L71
2. Screenshot is not actually PNG, or a type of image a person suppose it: try checking the output is not empty and if so use something like [Apache Tika](https://tika.apache.org/2.3.0/detection.html) to determine the type.
3. Platform just simply does not allow to take screenshots, see Appium Documentation for details: http://appium.io/docs/en/commands/session/screenshot/
