### ISSUE TITLE
[Question] The role of Minio when using s3

### ISSUE THREAD

**Issue by yuzujoe** [reportportal/reportportal#1205]
I saw an article that said you can access s3 with Minio as a proxy.
Looking at this content, I see that you have been given read permission, but don't you need permission to write?

**Comment by DzmitryHumianiuk** [comment]
@yuzujoe MinIO is in place, since we need to have some sort of same interface to work with local storages, S3 and any other cloud storage.
If you go with AWS setup, then you can use it without MinIO by itself. AFAIK, interface completely the same.

Permission most likely should be `WRITE`, but I'm not sure what's the exact place for it?

**Comment by yuzujoe** [comment]
Thanks

I think I can specify the URL of s3 host format in the endpoint and it will send the request to s3, is that correct?
