### ISSUE TITLE
[v5]Report portal error log  doesn't include the wild character asterisk(*)

### ISSUE THREAD

**Issue by vivekrai0409** [reportportal/reportportal#1280]
**Describe the bug**
When a selenium test script fails due to Xpath( Xpath has asterisk mark *) locator issue, report portal error log message doesn't include asterisk(*) mark

**To Reproduce**
1. Make a selenium script.
2. Have Xpaths like for  //*[@attribueName='some attribute value']//*[@attributeName='some attribute value']
3. Run the script and ensure it failing because its unable to find the above Xpath

**Expected behavior**
After test script failure, the report portal error log message should correctly show the not found Xpath which is //*[@attribue='some attribute name']//*[@attribute='some attribute name']

But the actual error has Xpath like //[@attribue='some attribute name']//[@attribute='some attribute name']
**Screenshots**
![ReportPortal-issue](https://user-images.githubusercontent.com/65509693/105164525-3d9f9a00-5b3b-11eb-9ebf-44d58b17d1b9.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Browser: Chrome
 - Version:87

**Comment by HardNorth** [comment]
I believe it's related to Markdown view, you even can't describe the bug clearly, since github's markdown engine eats your asterisks. There is nothing to fix from Report Portal side, since it bypasses test/log data "as is". It is user's business how to escape its data. Because if we add this escape logic we will break our Markdown view.
For you here i see two options:
1. Disable markdown view (click on markdown icon in top-right corner)
2. Add asterisk escaping in your code: replace "&ast;" with "&amp;ast;"

@DzmitryHumianiuk Please correct me if I'm wrong.

**Comment by DzmitryHumianiuk** [comment]
@HardNorth that's correct.

The same as in your description @vivekrai0409 - it just makes in bold.
![image](https://user-images.githubusercontent.com/11332788/105182934-adfbea80-5b3e-11eb-9dd1-ba7d525e88dc.png)

**3rd option:** add code snippet block before outputting locator. As:
```
 "```" + locatorString + "```"
```
it's a one-time change in your framework libs which will make it look fancy on RP pages with markdown, and will not affect much, if you will continue to read logs in console output
