### ISSUE TITLE
Elasticsearch index

### ISSUE THREAD

**Issue by rubico259** [reportportal/reportportal#1308]
Hi,
I must know the index name generated in elasticsearch by the auto analyzer service, because i need to open request to our elasticsearch team in my organisation to open permission on specific index.
I saw it generate index named 3 and rp_aa_stats.
What is the meaning of 3 index name, is it random? 
How can i know the names or can i define the index name? Or at least the prefix?
Thanks a lot.

**Comment by MariyaIvanina** [comment]
@rubico259  Hi! We assumed that users will use a separate Elasticsearch instance in the docker, so we didn't add prefix to the index. We have several shareable indices "rp_stats" and "rp_aa_stats" and each project has its own index with the name, project id in the database. So in your case 3 is your project id taht's why it was created like this. But since this issue occurred for several users, we will add an environment variable in the next version, where you'll be able to set up a prefix for a created index per project.

**Comment by rubico259** [comment]
Thanks, i am looking forward for the next version.
