### ISSUE TITLE
Parameterized tests have duplicated name on ReportPortal 

### ISSUE THREAD

**Issue by atanakalafiserv** [reportportal/reportportal#1310]
<img width="861" alt="parameterized-test_duplicateName" src="https://user-images.githubusercontent.com/79228905/108271212-10440d00-7136-11eb-838a-8f36e1498311.png">

can you help determine how this issue can be fixed?

**Comment by atanakalafiserv** [comment]
The name that appears on the report is testName itself and I would like to see if this can be differentiated and it would make things easy to determine which test is actually failing from a data driven context

**Comment by HardNorth** [comment]
@atanakalafiserv That's actually by design and there is nothing to "fix". We are reporting tool and out approach is to report data as is where it's possible. If test framework gives us name 'X', we report it as 'X'. You can customize the behavior by overriding corresponding methods on your own responsibility.
