### ISSUE TITLE
Elastic required permissions

### ISSUE THREAD

**Issue by yonimoses** [reportportal/reportportal#1315]
Hi

Can someone please elaborate on the minimal permissions required for elastic?
I’ve noticed the indexes are generated without any prefix or similar, thus it’s difficult to provide a specific permission for creating such .

**Comment by MariyaIvanina** [comment]
@yonimoses Hi! We assumed that users will use a separate Elasticsearch instance in the docker, so we didn't add prefix to the index. We have several shareable indices "rp_stats" and "rp_aa_stats" and each project has its own index with the name, project id in the database. But since this issue occured for several users, we will add an env variable in the next version, where you'll be able to set up a prefix for a created index per project.
