### ISSUE TITLE
On page ALL DASHBOARDS add possibility to see it in list mode

### ISSUE THREAD

**Issue by esoskovets** [reportportal/reportportal#133]
Now on page `ALL DASHBOARDS` displayed dashboards icons, will be better to have possibility to see it in list mode like on page /ui/#administrate.

**Comment by Iren-Melnyk** [comment]
Hello, Esoskovets!
I'm a designer on ReportPortal. And before redesigning the page would like to know how often do you use ALL DASHBOARDS page? Could you please describe your interaction on this page? How many own and shared dashboards do you have? What information would you like to see in list view?

**Comment by DzmitryHumianiuk** [comment]
@esoskovets up ^^

**Comment by s-shimko** [comment]
I'm answer instead of Egor, he knows about it. Now I'm working with RP.
1. Minimun I'm use ALL DASHBOARDS one time per 2 weeks.
2. Just ordinary interaction. I'm create new dashboard per 2 weeks to observe statistic and I often use 'Most failure test-cases failure'. I'm not editing old dashboards to get information about new sprints.
3. I'm always share My dashboards for my colleagues, who involved in automate process
4. Now I have 10 shared dashboards, cause I delete unused dashboards, without deleting amount could be a lot.
5. In list mode I want to see:
  Dashboard name, number of widgets in a dashboard, shared status, Delete, Edit icons
