### ISSUE TITLE
Report Portal instance keeps on Loading

### ISSUE THREAD

**Issue by priyankachaturvedi30** [reportportal/reportportal#1346]
It works fine during the entire day, and when I login the next day I see following error
![image](https://user-images.githubusercontent.com/50797731/112592040-52dec080-8e2b-11eb-9220-57dc58998cfd.png)
When I try to do a docker-compose up I see following error - 
![image](https://user-images.githubusercontent.com/50797731/112592130-799cf700-8e2b-11eb-8b33-22167c43da85.png)
Can somebody check please. @DzmitryHumianiuk @evjlobanova

**Comment by manishsaini7** [comment]
Facing the same issue on my mac. Is it resolved?

**Comment by DzmitryHumianiuk** [comment]
@manishsaini7 it doesn't depend on operating system. No matter it is mac, win or linux.

if you instance is not responding, you should check statuses of you containers first.
at the same time, make sure i've allocated at least 5gb of RAM for you docker machine.

@priyankachaturvedi30 what i see from the screenshot above: every single containers is failed and not function properly.

**Comment by assiakhateeb** [comment]
@priyankachaturvedi30 how did you solve the issue?

**Comment by bryanphan** [comment]
issue

**Comment by DzmitryHumianiuk** [comment]
**Folks, the grey screen and "Loading...." message can indicate a variety of issues, and each case you encounter might have different reasons and resolutions.**

What I can say for sure is that **most of these problems** are related to **faulty installations** using Docker-compose. When some application components do not start up correctly, fail to register within the micro-services architecture, or don't execute their initialization scripts, these issues arise.

In 99% of cases, it's due to insufficient resources (RAM and CPU) allocated to the Docker machine or Docker process. This leads to situations where the database can't start, or starts very slowly, and simultaneously launching micro-services that are supposed to create data do not wait for the database to come up due to timeout, and they fail silently without creating the initial data structure. This causes a cascade of failures.

**I am intentionally closing this discussion because the causes vary in each specific case.**

However, for those who have encountered such issues, I can provide some basic recommendations to check immediately:
1. Verify the availability of all containers and their health status using the command `docker ps -a`.
   - If you don't understand what this command does, please read about it using a [Google search](https://www.google.com/search?q=how+to+use+docker+ps+-a).
   - The command output should NOT contain duplicate services. Anything with a postfix `_2` should not be there, as it means another container with the same functionality has been launched.
   - If any containers have a status other than `healthy`, you need to check their logs. To learn how to do this, look up articles on [reading logs from a specific Docker container](https://stackoverflow.com/questions/47829345/how-to-see-the-logs-of-a-docker-container).
   - Among all ReportPortal containers, only one container is allowed to have the EXIT status, which is `migrations-db`. Its job is to create an initial data set and then exit. But it should be in running state at the initial start.

2. The # 1 reason for container crashes at the start of ReportPortal is insufficient resources allocated to the Docker process itself. ReportPortal is a complex micro-services application designed to handle high-load reporting systems, so it requires enough memory and resources to deploy properly. We recommend at least 8GB of RAM for the application startup.
   - How to allocate more memory to Docker depends on where you're using it, and you should research this on your own. One good source of information is this: https://stackoverflow.com/questions/44533319/how-to-assign-more-memory-to-docker-container
 
3. Merely restarting single containers won't solve the problem. All containers are interdependent and must be launched in accordance with the dependencies outlined in the docker-compose file. Please don't restart them individually.
   - Stop all containers and then restart the entire compose stack using the command `docker-compose -p reportportal up -d --force-recreate`. The `--force-recreate` flag will reset all accumulated settings and restart everything from scratch.
   - If you've allocated more memory and have done a `--force-recreate` restart, but the problem persists, monitor the status of the containers with `docker ps -a` and check the logs of any that have failed. The logs will give you insights into the cause of the failure.
   - A list of necessary commands and tips can also be found here: https://reportportal.io/docs/installation-steps/DeployWithDockerOnLinuxMac/#deploy-reportportal-with-docker

4. DO NOT IGNORE THE DOCUMENTATION and make sure to read everything described there. Each point is added based on experience and the challenges faced by other users. These instructions are designed to make your experience smoother and faster.

If your knowledge of Docker and containers is very limited, unfortunately, we can't devote time to educate you on Docker usage. Please familiarize yourself with this technology on your own or seek help from a knowledgeable DevOps/System engineer. To launch ReportPortal and troubleshoot its problems, you only need a very basic understanding.

_____
### If you've found yourself in this thread and are still experiencing similar issues

please make sure to read all 4 points mentioned above. This thread will now be closed. 
If you've followed all 4 steps and are still encountering problems, please open a new issue and attach the logs from the containers that failed for you. This will increase the chances that we can assist you with your problem.
