### ISSUE TITLE
Installation / Upgrade ElasticSearch to have installed in the image the Java version we desired

### ISSUE THREAD

**Issue by Tonicku** [reportportal/reportportal#1360]
**Be able to choose the ElasticSearch image with the desire Java version**
... 

*Oracle Java JRE Unsupported Version Detection (Unix).**
...

**Comment by HardNorth** [comment]
We are not controlling elastic packaging / images. But you a free to use whichever version of Elastic you want, choose:
https://www.docker.elastic.co/r/elasticsearch

**Comment by fkrivsky** [comment]
Is there some elastic image that is officially supported by ReportPortal?

**Comment by HardNorth** [comment]
@fkrivsky Our official images are the same which we are use in our docker compose file:
https://github.com/reportportal/reportportal/blob/master/docker-compose.yml#L34
And in Kubernetes values:
https://github.com/reportportal/kubernetes/blob/master/reportportal/requirements.yaml#L13

We test new versions of RP with them. It's not necessarily others won't work, just not tested.

**Comment by Tonicku** [comment]
Thanks for the quick reply

**Comment by HardNorth** [comment]
@Tonicku We don't have any specific preferences of Elastic versions, we don't rely on any version-specific code and do not customize our own version of Elastic. It's just a matter of tested/untested stuff. Elastic package its own java version even in their official archives. We don't interfere into this process.
And because of that I can't answer your question about problems, we just didn't tested other versions. We upgrade Elastic versions in our distributions only if we need new features for our Auto Analysis or if we need certain bug fixes. And because of Elastic is a very complex piece of software we prefer postpone any upgrades without a reason.
