### ISSUE TITLE
UI slowness

### ISSUE THREAD

**Issue by asaflevyz** [reportportal/reportportal#1471]
We are experiencing UI slowness while trying to display logs of any test for the first time, which takes around 30 seconds.
Once we got the logs displayed, next time the same test logs come instantly.
We are using 5.3.5 with separate server for PostgreSQL.

Thanks.

**Comment by evjlobanova** [comment]
@irynakozak2 could you please check?

**Comment by irynakozak2** [comment]
@asaflevyz hello, we know about that problem on version 5.3.5 and on the oldest versions, so we have done with a refactoring database query to display HistoryLine when you open the LogView and expect the slowness. Fix of this issue is planed to release at the 5.5 version.

**Comment by asaflevyz** [comment]
We have done all PostgreSQL optimizations but the behavior is the same.
When you expect the release of 5.5?

Thanks.

**Comment by asaflevyz** [comment]
guys, any update?

**Comment by asaflevyz** [comment]
Guys,
Do you have any release date soon?

**Comment by irynakozak2** [comment]
Please note, as I mentioned above, this is the expected behavior of the application, when the first operation is performed.
That is no issue with ReportPortal itself. It is a normal work of the PostgreSQL database cache memory, so that: 
 - the first execution may take some time to cache;
 - next executions became instantly.

**Comment by asaflevyz** [comment]
Is 5.5 going to improve this?
