### ISSUE TITLE
[v5] db-scrripts migration fail from 5.3.5 to 5.5

### ISSUE THREAD

**Issue by dmitry-beryozkin** [reportportal/reportportal#1511]
**Describe the bug**
Fail after 17 hours of db-scrripts migration.

**To Reproduce**
I tried to update reportportal from 5.3.5 to 5.5 just by updating docker images in docker-compose file and adding new service   metrics-gatherer.

**Expected behavior**
I expected that db-scrripts migration will be finished with a success.

**Screenshots**
![image](https://user-images.githubusercontent.com/71384849/130594460-89a6fb2f-20f4-4129-bd7d-ff5f30e8c9d1.png)
![image](https://user-images.githubusercontent.com/71384849/130594495-f19d7a2c-47df-473a-94ba-47167c39baec.png)

Server:
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"

docker logs -f reportportal_db-scripts_1
wait-for-it.sh: waiting 15 seconds for postgres:5432
wait-for-it.sh: postgres:5432 is available after 0 seconds
26/u retries_lock_fix (350.174356ms)
27/u add_project_id_log (414.993376ms)
28/u create_log_project_idx (11m49.186138976s)
29/u create_table_item_project (11m49.51884163s)
30/u item_project_fill_part1 (13m20.862132745s)
31/u item_project_fill_part2 (13m55.283898285s)
32/u create_item_idx (14m22.108805612s)
33/u drop_log_message_trgm_idx (14m39.666594687s)
34/u fill_project_id_part1 (3h52m35.473470082s)
35/u fill_project_id_part2 (12h27m37.013346376s)
36/u drop_item_project (12h27m40.376273881s)
37/u create_log_message_trgm_idx (16h57m50.014694334s)
38/u add_not_null_log_project_id (17h33m25.553313062s)
39/u attachment_creation_date (17h21m37.272729471s)
40/u attachment_creation_date_fill (17h25m17.08410299s)
41/u attachment_creation_date_not_null (17h23m45.861812296s)
42/u shedlock_table (17h23m12.625681872s)
43/u attachment_for_deletion_table (17h22m46.137350803s)
44/u remove_triggers (17h22m29.276742254s)
45/u add_jobs_indexes (14h26m44.051740426s)
error: migration failed: invalid input syntax for type bigint: "3 months" in line 0: CREATE OR REPLACE FUNCTION update_job_attributes_in_bounds()
    RETURNS INTEGER
    LANGUAGE plpgsql
AS
$$
DECLARE
prj_id                 BIGINT;

    launch_job_attr_id     BIGINT;
    log_job_attr_id        BIGINT;
    attachment_job_attr_id BIGINT;

    launch_job_value       BIGINT;
    log_job_value          BIGINT;
    attachment_job_value   BIGINT;
BEGIN
    launch_job_attr_id := (SELECT id
                           FROM attribute
                           WHERE attribute.name = 'job.keepLaunches');
    log_job_attr_id := (SELECT id
                        FROM attribute
                        WHERE attribute.name = 'job.keepLogs');
    attachment_job_attr_id := (SELECT id
                               FROM attribute
                               WHERE attribute.name = 'job.keepScreenshots');

FOR prj_id IN (SELECT id FROM project ORDER BY id)
        LOOP
            launch_job_value := (SELECT value::BIGINT FROM project_attribute WHERE attribute_id = launch_job_attr_id AND project_id = prj_id);
            log_job_value := (SELECT value::BIGINT FROM project_attribute WHERE attribute_id = log_job_attr_id AND project_id = prj_id);
            attachment_job_value := (SELECT value::BIGINT FROM project_attribute WHERE attribute_id = attachment_job_attr_id AND project_id = prj_id);

            IF launch_job_value != 0
            THEN
                IF log_job_value > launch_job_value OR log_job_value = 0
                THEN
                    log_job_value := launch_job_value;
UPDATE project_attribute
SET value = log_job_value
WHERE attribute_id = log_job_attr_id
  AND project_id = prj_id;
END IF;
END IF;

            IF log_job_value != 0
            THEN
                IF attachment_job_value > log_job_value OR attachment_job_value = 0
                THEN
                    attachment_job_value := log_job_value;
UPDATE project_attribute
SET value = attachment_job_value
WHERE attribute_id = attachment_job_attr_id
  AND project_id = prj_id;
END IF;
END IF;

END LOOP;

RETURN 0;
END;
$$;

SELECT update_job_attributes_in_bounds(); (details: pq: invalid input syntax for type bigint: "3 months")
wait-for-it.sh: waiting 15 seconds for postgres:5432
wait-for-it.sh: postgres:5432 is available after 0 seconds
error: Dirty database version 46. Fix and force version.
wait-for-it.sh: waiting 15 seconds for postgres:5432
wait-for-it.sh: postgres:5432 is available after 0 seconds

PostgreSQL logs:
![image](https://user-images.githubusercontent.com/71384849/130594898-4bbd02f7-1151-4757-8d29-89b6a8828670.png)

**Comment by evjlobanova** [comment]
Hello, please check the documentation regarding migration issue https://github.com/reportportal/documentation/blob/master/src/md/src/TipsAndTricks/MigrationIssue.md

Please try to perform described steps, and let us know about the results.

**Comment by gesmogast** [comment]
Hey @evjlobanova ,
We have already tried to update schema_migrations to lower numbers multiple times but it keeps failing on step #46.
The same error:
`2021-09-20 06:47:46.394 UTC [1300] **ERROR:  invalid input syntax for type bigint: "3 months"**
2021-09-20 06:47:46.394 UTC [1300] CONTEXT:  SQL statement "SELECT (SELECT value::BIGINT FROM project_attribute WHERE attribute_id = launch_job_attr_id AND project_id = prj_id)"
	PL/pgSQL function update_job_attributes_in_bounds() line 25 at assignment
2021-09-20 06:47:46.394 UTC [1300] STATEMENT:  CREATE OR REPLACE FUNCTION update_job_attributes_in_bounds()
	    RETURNS INTEGER
	    LANGUAGE plpgsql
	AS
	$$
	DECLARE
	prj_id                 BIGINT;
	
	    launch_job_attr_id     BIGINT;
	    log_job_attr_id        BIGINT;
	    attachment_job_attr_id BIGINT;
	
	    launch_job_value       BIGINT;
	    log_job_value          BIGINT;
	    attachment_job_value   BIGINT;
	BEGIN
	    launch_job_attr_id := (SELECT id
	                           FROM attribute
	                           WHERE attribute.name = 'job.keepLaunches');
	    log_job_attr_id := (SELECT id
	                        FROM attribute
	                        WHERE attribute.name = 'job.keepLogs');
	    attachment_job_attr_id := (SELECT id
	                               FROM attribute
	                               WHERE attribute.name = 'job.keepScreenshots');
	
	FOR prj_id IN (SELECT id FROM project ORDER BY id)
	        LOOP
	            launch_job_value := (SELECT value::BIGINT FROM project_attribute WHERE attribute_id = launch_job_attr_id AND project_id = prj_id);
	            log_job_value := (SELECT value::BIGINT FROM project_attribute WHERE attribute_id = log_job_attr_id AND project_id = prj_id);
	            attachment_job_value := (SELECT value::BIGINT FROM project_attribute WHERE attribute_id = attachment_job_attr_id AND project_id = prj_id);
	
	            IF launch_job_value != 0
	            THEN
	                IF log_job_value > launch_job_value OR log_job_value = 0
	                THEN
	                    log_job_value := launch_job_value;
	UPDATE project_attribute
	SET value = log_job_value
	WHERE attribute_id = log_job_attr_id
	  AND project_id = prj_id;
	END IF;
	END IF;
	
	            IF log_job_value != 0
	            THEN
	                IF attachment_job_value > log_job_value OR attachment_job_value = 0
	                THEN
	                    attachment_job_value := log_job_value;
	UPDATE project_attribute
	SET value = attachment_job_value
	WHERE attribute_id = attachment_job_attr_id
	  AND project_id = prj_id;
	END IF;
	END IF;
	
	END LOOP;
	
	RETURN 0;
	END;
	$$;
	
	SELECT update_job_attributes_in_bounds();
`

**Comment by gesmogast** [comment]
A bit more context on what is inside the project_attribute table:

`
 attribute_id |          value           | project_id
--------------+--------------------------+------------
            4 | 1209600                  |          9
            2 | 7776000                  |          9
            1 | 3600                     |          9
            3 | 7776000                  |          9
            4 | 1209600                  |         11
           10 | false                    |        109
            7 | 95                       |        109
            4 | 2 weeks                  |        109
            8 | -1                       |        109
           11 | false                    |        109
            2 | 3 months                 |        109
            1 | 1 day                    |        109
            3 | 3 months                 |        109
            9 | false                    |        109
           13 | false                    |        109
           12 | LAUNCH_NAME              |        109
           10 | false                    |        111
            7 | 95                       |        111
            4 | 2 weeks                  |        111
            8 | -1                       |        111
           11 | false                    |        111
            2 | 3 months                 |        111
            1 | 1 day                    |        111
            3 | 3 months                 |        111
            9 | false                    |        111
           13 | false                    |        111
           12 | LAUNCH_NAME              |        111
           10 | false                    |        178
            7 | 95                       |        178
            8 | -1                       |        178
            2 | 7776000                  |        178
           11 | false                    |        178
            1 | 86400                    |        178
            4 | 1209600                  |        178
            9 | false                    |        178
           13 | false                    |        178
            3 | 7776000                  |        178
`

**Comment by evjlobanova** [comment]
@miracle8484 Maksim, could you please check this ticket?

**Comment by SubratKumarTR** [comment]
Hi Team, 

We are facing same issues in DB migration from 5.3.5 to 5.5.0.

Regards,
Subrat.

**Comment by ReddyNitheeesh** [comment]
@gesmogast, @evjlobanova  ,

can you please help with list of rollback steps you followed to downgrade from 5.5 to 5.3.5 , we are facing issues related to elastic search as **"Cannot downgrade node from 7.10.1 to 7.3.0"**
![image](https://user-images.githubusercontent.com/28997011/134817572-b4034f3c-2264-41e8-8440-af3c00d6b768.png)

Thanks,
Nitheesh

**Comment by gesmogast** [comment]
Hey, @ReddyNitheeesh , we are experimenting with this migration on a full copy of the server and restoring it back to 5.3.5 from its snapshots. So I don't think I will be any help for you.

**Comment by AlexeyKolychev** [comment]
Hey Team,
Same issue.

**Comment by miracle8484** [comment]
Hello, guys!
As you can see from your logs, trouble is related to data is stored in your database. To be more precisely "3 months" as projects retention policy attribute. In migration https://github.com/reportportal/migrations/blob/develop/migrations/18_job_attributes.up.sql we converted string intervals to seconds, that can be parsed to BIGINT, but in your case my suggestion is:
1. Migration 18_job_attributes.up.sql has been failed for some reasons, but you ignored it and still using inconsistent version of RP.
2. You updated db fields manually, as result inconsistent state of RP.
Please fix me, if you know how "3 months" value can be written in db.
---------------------------------------------------------------------------------------------------------------
1. If you've ignored some migrations then you db can be in inconsistent state and it needs to manual check all migrations, because we can't be sure that only converting was wrong... BUT to fix only this cause you can use next point.
2. Simple point, you just need to convert string intervals to seconds, you can use script like 18_job_attributes.up.sql

And also have a look at https://github.com/reportportal/documentation/blob/master/src/md/src/TipsAndTricks/MigrationIssue.md,
it helps to rerun broken migrations.

**Comment by ReddyNitheeesh** [comment]
Hello @miracle8484 ,

Current migration version in 5.3.5 RP version is 25, on upgrading to 5.5 it starts migration from 26 version right, then there is flaw in before migration steps only, it is somehow skipping a specific step. Please find additional info below
![image](https://user-images.githubusercontent.com/28997011/135198144-6f76d3ee-d8df-4aa9-9ada-34ef80dfbebb.png)

and can you please provide details, it there any way to revert or roll back elastic search data, as we are facing the below error
![image](https://user-images.githubusercontent.com/28997011/135198319-c93956a7-dd58-4c2b-8bad-a0a74ef55393.png)

can you please provide mitigation steps on how to handle the above scenario, it would be much helpful. 

Thanks in Advance

**Comment by miracle8484** [comment]
Hello, @ReddyNitheeesh, if migration https://github.com/reportportal/migrations/blob/develop/migrations/18_job_attributes.up.sql has been executed correctly, then you must have digits instead of string("3 months"), or possible cases i mentioned above.
But i strongly recommend to you keep database consistent and don't rollback to old versions.
Possible ways to resolve migration trouble, i wrote above, but rollback to old software versions is not recommended flow.

**Comment by gesmogast** [comment]
Hey, @miracle8484 , thanks,
the idea to re-run the db migrations script from step 18 seems working. 
What I did:
1) UPDATE schema_migrations SET version = 17, dirty = false;
2) Rerun the db migration again
3) Checked that the project_attribute table has been updated and has no more string values anymore (3 months, 1 month, etc)
4) The migration process failed several times due to 'table exits', blabla
Then I went back to the initial problematic step (45), knowing all the steps (1-44) finished correctly.
UPDATE schema_migrations SET version = 45, dirty = false;
5) Rerun the migration again and now it went good without any problem.
I'm not sure why step 18 finished incorrectly, rerunning it helped to make the upgrade process successfully complete.

**Comment by miracle8484** [comment]
Actually, idea was to run scripts to fix string data for job attributes, as basic you can use https://github.com/reportportal/migrations/blob/develop/migrations/18_job_attributes.up.sql (possibly you can use it as is).
**!Important**, Rerun all migration from some specific step in the past(for current case from 18 and upper) may be have some side effects, and i DON'T recommend use this way thoughtless.

One more time you can use single script like script in 18 migration, to fix current trouble, but root cause of this trouble in your environment is still unknown and possibly you have inconsistent system in some another part too.

As i mentioned above, after you fix this issue, you can use https://github.com/reportportal/documentation/blob/master/src/md/src/TipsAndTricks/MigrationIssue.md, to continue migrations from you current point(not from 18 point).

**Comment by ReddyNitheeesh** [comment]
Thanks, @miracle8484, 

As per this discussion execute job 18 and then update table of schema migrations table with this command(UPDATE schema_migrations SET version = 45, dirty = false;) and execute migrations would fix our problem.

But to be sure to fix inconsistency are not there in our system,  if we start migrations starting from 18 do you see any issues or data loss??
Thanks,
Nitheesh

**Comment by miracle8484** [comment]
You are welcome, 
unfortunately, there is no simple way do check, 
i can't guarantee that reset and rerun migration from 18 up to current doesn't damage your current data.
As i see, you have few options:
1. Fix current issue and complete migrations, but with risk of inconsistency. 
2. Manually recheck all migrations for consistency with your DB status, and run some migrations or part of it if needed.
3. Install new actual RP version and re-report all needed data.
4. Ask for payed support.(For check you db status instead of you.)

Anyway my advice for the future, if you have some migration trouble you MUSTN'T ignore it, event in case RP is still working with this state.
I hope that helps.
