### ISSUE TITLE
Cannot find Match issues in launch option in Report Portal 5.5.0 

### ISSUE THREAD

**Issue by SreaSrestha9** [reportportal/reportportal#1517]
![image](https://user-images.githubusercontent.com/19340031/132238370-2a02233e-2356-4252-b038-fb39a2dbd604.png)

**Comment by evjlobanova** [comment]
Hello @SreaSrestha9 
"Match Issue" feature has been removed in version 3.x.x. Since that we have rewrite the analyzer twice)
 So in version 5.5 the analogue of "Match issue" is ML suggestions feature:
 
![image](https://user-images.githubusercontent.com/30413511/132338099-958b04be-a2a9-4c1c-942d-9f8519f36427.png)

In the section ML suggestions, you can find items with similar errors for analyzed items.

**Comment by SreaSrestha9** [comment]
The option "Choose among ML suggestion" stays in disabled state. How can we enable it?

**Comment by evjlobanova** [comment]
It depends on the reasons why this option is disabled. You can hover ML suggestion section  and the system should show you a tool tip with a problem. 

There are 2 possible reasons:
- problems with Analyser service
- or there is no ML suggestion for analysed item 

If you have the 1st problem, check you deployment.
If the 2 nd, try to generate index in Project Settings,  if still section is disabled - it means that Analyzer has not found anything similiar
