### ISSUE TITLE
[v5] api performance is much slower than on v4 for /v1/{projectName}/item for huge launches

### ISSUE THREAD

**Issue by DeNNyA19** [reportportal/reportportal#1541]
We use ReportPortal API for generation of an excel report with an information about all tests in the list of launches. After migration to V5 for some launches time required to generate report significantly increased.

Below you may see response timings for requests to V4 which are 10-20 ms
![image](https://user-images.githubusercontent.com/21055259/136187061-09b6e662-3d63-49b7-b335-8c7bb731d089.png)
Launch to which items requests are performed
![image](https://user-images.githubusercontent.com/21055259/136187104-4d33a659-75ea-4346-8b12-afb6a819e4c8.png)

Same requests to a similar launch on V5 which are 10x slower
![image](https://user-images.githubusercontent.com/21055259/136187291-60d8e81c-5ba0-4624-90da-1bcd8cb2c3e4.png)
Launch to which items requests are performed
![image](https://user-images.githubusercontent.com/21055259/136187317-a39b80a5-396f-4390-aeb5-6618c48c3833.png)

For small launches with an amount of tests ~100 response timing is quite same for both V4 and V5 with a small value ~10-20ms
![image](https://user-images.githubusercontent.com/21055259/136188640-2af6590a-af5f-4bbd-9f9e-63607c1613d1.png)

Versions of deployed instances:
![image](https://user-images.githubusercontent.com/21055259/136187422-35d7472f-75fc-4369-8d04-bfa599e51199.png)
4.3.6
![image](https://user-images.githubusercontent.com/21055259/136187364-63d4cb50-ef50-4f58-a752-10d668530030.png)
5.5.0

**Comment by DeNNyA19** [comment]
@evjlobanova  we have many feature jobs which run in scope in the pipeline in terms of one regression and we generate one report for all launches. Also in the default export it is not possible to remove before/after methods and see only tests. Our custom report aggregates all required for us information into one report and provides links into respective failures (which is useful for ReportPortal navigaton)

**Comment by dmitryyu** [comment]
Thanks for the answer, and for the workaround.

Mainly we’ve just raised the issue to highlight that now it’s slower. We do not do the export every day so we can wait until it’s completed even with slower response. 

regarding export - we use some of widgets, but even if we have the option inside of system we still have some issues:
1. We need to provide access for users who can see it, when xlsx report can be just uploaded to a shared drive.
2. we are attaching the final xlsx report  to every release artifact (the excel uses table format) - so it can be configured/filtered/sorted/excluded by few obvious actions and get a requested(different) info instead of providing access and instructions how to get it. I would say it’s just more simple.
3. When we have excel report - we can see explanations for all cases, and by removing(filtering) we just see cases which need to be verified additionally.

**Comment by evjlobanova** [comment]
Thank you for the details.
We are planning partly to resolve these by adding:
1. a possibility to make embedded widget/dashboards
2. a Viewer role - users can check info in RP without login
2. a report for release, which can be stored in RP for all times and can be shared a separate document
