### ISSUE TITLE
[Feature request]: Make possibility to search through all launches/suites/features/scenarios for appropriate text occurrences

### ISSUE THREAD

**Issue by jurteg** [reportportal/reportportal#158]
As RP user I need to search for some text occurrences in all launches, so I'm able to find text matches in issues, launches etc. This functionality will help to trace different changes in tests like: dynamic of their number, to match similar issues over period of time, evaluate start dates of behavior we need to investigate etc. This could be used for many purposes that can not be underestimated in terns if testing process.

Functionality should be able to search in:
- launch names
- feature names
- scenario titles
- step names
- stacktraces
- launch/feature/scenario description

Maybe some of this is planned to be implemented accordingly to this post: https://github.com/reportportal/reportportal/issues/62#issuecomment-287834214 ?

**Comment by DzmitryHumianiuk** [comment]
@jurteg good one.

in few month we will introduce ElasticSearch. and this will give ability to use `full-text search`
then this feature will be considered

**Comment by evjlobanova** [comment]
the same request from SIarhei (@serega.m) (slack/reportportal/ general chat)

**Comment by evjlobanova** [comment]
In version 5.0 we have added a clickable area for widgets which is based on filter.
For example Overall Statistics widget.
![image](https://user-images.githubusercontent.com/30413511/76962989-4d55bd00-6931-11ea-9f61-519b2f8179e0.png)

It shows summ information about filter.
When a user clicks on the widget.
Then system redirects user to the *list view for filter*
![image](https://user-images.githubusercontent.com/30413511/76963068-7d04c500-6931-11ea-9e21-46a0cbd9b282.png)
This view combines test cases from different launches.

So that partialy you problem can be solved, and you can find test cases between several launhces.

Such clickable area is also available for:
- Pattern widget
- Cumulative trend chart widget
- Overal statistics widget

In version 5.1 it will be available for all widgets which have statistics that based on several launhces.

**Comment by evjlobanova** [comment]
Close as a duplicate https://github.com/reportportal/reportportal/issues/45
