### ISSUE TITLE
Security vulnerabilities for Https support 

### ISSUE THREAD

**Issue by Jayarams99** [reportportal/reportportal#1734]
We are trying to integrate reportportal in our project.There are some security vulnerabilities found with https implementation using Traefik.Is there any other work around to implement https without using traefik?

**Comment by alena-babrova** [comment]
Hello @Jayarams99,

We had a major release with security fixes in version 23.1: https://reportportal.io/releases/v23.1.
Please, take a look at this version. Hopefully, it covered the issue described as well.
There are no alternatives for Traefik in our solution.

If the issue is not resolved, do not hesitate to reopen the ticket with details.

Thank you for your contribution!
