### ISSUE TITLE
Do we have any feature to consolidate all project's dashboard in single dashboard

### ISSUE THREAD

**Issue by amitjadhav927** [reportportal/reportportal#1740]
### Discussed in https://github.com/reportportal/reportportal/discussions/1739

<div type='discussions-op-text'>

<sup>Originally posted by **amitjadhav927** May 16, 2022</sup>
Hi Team,

We have multiple project and if we want to check the dashboard then we have to select that project's dashboard from the drop-down.
So my ask is there any feature that we want to consolidate all project's dashboard in single (or we can say main) dashboard. Where it should have project name with its pie chart (like pass, fail, skip test cases %).
</div>

**Comment by govindsh** [comment]
+1 this feature would be really helpful.

**Comment by amitjadhav927** [comment]
@govindsh: Hi do you know that how to use report portal api to create dashboard ?
what is my idea is i will call project level apis and get the widgets id, so i will call apis using different - different projects name and i will have the widgets id.
now how can i show the dashboard as per the projects and widget id ?

**Comment by govindsh** [comment]
@amitjadhav927  - sorry for the late response, I believe we can create dashboard with following steps:
1. POST /v1/{projectName}/dashboard
2. GET Widget / Filter at different projects 
3. PUT /v1/{projectName}/dashboard/{dashboardId} and use updateWidgets 
I haven't tried this yet. If you get a chance, let me know how it goes :)

**Comment by manojguptavonage** [comment]
Hi,

By any chance were you able to get it working?

**Comment by brabenetz** [comment]
It is complicated, but it helps to use the object-library for the Rest-API:

        <dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>commons-model</artifactId>
            <version>5.7.0</version>
        </dependency>

1 Get Template-Dashboard Infos Dashboard, Widgets and Filter:
- GET /v1/{projectName}/dashboard
- if widget isSupportMultilevelStructure() ( https://github.com/reportportal/service-ui/blob/cebf31022be50b0e0c8e56959461a8e943a2a3d2/app/src/components/widgets/index.js#L80-L93 )
  - GET /v1/{projectName}/widget/multilevel/{widgetId}
- otherwise:
  - GET /v1/{projectName}/widget/{widgetId}
- GET /v1/{projectName}/filter

2a. Update Dashboard in target Project (if exists):
- DELETE /v1/{projectName}/dashboard/{dashboardId}/{widgetId}  # remove existing Widgets
- PUT /v1/{projectName}/dashboard/{dashboardId}

2b. Or Create Dashboard in target Project:
- POST /v1/{projectName}/dashboard

3a. Update Filter (if exists):
- PUT /v1/{projectName}/filter/{filterId}

3b. Or Create Filter:
- POST /v1/{projectName}/filter

4. Create Widgets and add it to the new Dashboard:
- POST /v1/{projectName}/widget
- PUT /v1/{projectName}/dashboard/{dashboardId}/add

**Comment by MaryiaRymarchyk** [comment]
hello @amitjadhav927, sorry, but we don't have the feature to consolidate all project's dashboard in single dashboard. 
We hope, comments above helped you. 
We'll close the issue for now, but if you still have questions, please, do not hesitate to contact us.
