### ISSUE TITLE
RegEx for AutoAnalysis

### ISSUE THREAD

**Issue by vishallanke** [reportportal/reportportal#1779]
We set AutoAnalysis criteria to 100% because in case of failures of API testing only Status code is different.
`Excepted 200. API returns 403`

`Excepted 200. API returns 500`

AutoAnalysis should not treat these as same error logs. So we set criteria to 100% logs must match

However , some of the tests return error logs as

`Error: Organization 3bdc3536-9931-41b3-ad6f-f20a17bd0a121 doesn't have any subscription after 10 seconds`

`Error: Organization 45dc3536-9931-41b3-ad6f-f20a17bd0a121 doesn't have any subscription after 10 seconds`

Here, only Id is different
AutoAnalysis does not work as logs does not match 100%

**Comment by alena-babrova** [comment]
At the moment this is as designed.
Under the hood, system makes some kind of pre-analysis and marks some parts of strings as a "noise" so that these items do not take part in the analysis process itself (skipped while comparing).
In your case, even though the matching is set to 100%, the system understands that it is a unique identifier with high equality rate and is treated as "noise" (not important, technical) and is not taken into consideration when analyzer processes the strings.

At the moment, there are no upcoming plans on changing this behaviour.

Thank you

**Comment by alena-babrova** [comment]
As we haven't received a reply from you, we'll close the issue for now.
Just in case you still have the issue, please, do not hesitate to get in touch.
