### ISSUE TITLE
Log messages not displayed if unable attach file to step

### ISSUE THREAD

**Issue by admizh** [reportportal/reportportal#18]
I try send big file to report portal, it my test (testNg):
```java
@Test
    public void bigFileTestWithMinimumBatchSize() throws Exception {
        //rp.batch.size.logs = 1 (set via reportportal.properties)
        URL resource = Resources.getResource("big.file");
        String path = Paths.get(resource.toURI()).toAbsolutePath().toString();
        logger.info("1# event before sending big file");
        logger.info("RP_MESSAGE#FILE#{}#{}", path, "2# event (very big file)");
        logger.info("3# event after sending big file");
    }
```
Current results: 
"_2# event (very big file)_" event not logged in RP
I think we should log it and root cause (exception)

![2016-12-02_13-14-25](https://cloud.githubusercontent.com/assets/6014483/20829400/5a792ec2-b895-11e6-8ed9-f0f8bba05024.png)

**Comment by avarabyeu** [comment]
@admizh It's actually expected behavior since log is related to attachment. Does really see any sense to keep log message if binary data is rejected. @DzmitryHumianiuk what do you think?

**Comment by admizh** [comment]
@avarabyeu & @DzmitryHumianiuk  - When step message not logged is already bad. It difficult to understand what happened and why my binary files not available. let's add simple step with message - that we were not able to attach a file. Since many users can not even grasp that here must be some file (no any steps in RP UI). It provide additional tasks for automation engineers - They should check CI build log - for catching this issues.

**Comment by DzmitryHumianiuk** [comment]
@avarabyeu I'm agreed with @admizh.
it's not obvious what happens if binary rejected with size over 16Mb.

1. Log message should be stored for sure
2. Add `ERROR` or `WARNING` log that binary was not attached.

and finally, i think we should consider the option to upload file 16Mb+

**Comment by avarabyeu** [comment]
@DzmitryHumianiuk @admizh 

Guys, let me clarify. There are two limits:
1. Request size limit
2. Request part limit e.g. binary attachment limit. 
Now we have request-level limitation which is causes mentioned issue. 

I still think 16 mb is absolutely enough for one file. So what i would suggest to do:
1. Remove request size limit
2. Introduce request part limit == 16 mb (each log entry is 16 mb)
It means you will be able to send request without size limitation, but each particular part should not exceed 16mb.

Regarding batch processing, i would personally prefer to avoid saving binary data comments (e.g. log message) when binary data is not actually saved. So, for me expected behavior this is following:

1. Save log entries independently. E.g. save everything which is possible to save.
2. If binary saving is prohibited, does not save message as well since it doesn't make sense.

> Add ERROR or WARNING log that binary was not attached.
This is a not good idea. We should not add/edit any message obtained from client-side

**Comment by avarabyeu** [comment]
fixed
