### ISSUE TITLE
Make possible to assign people for test failure  analysis activity

### ISSUE THREAD

**Issue by AndriiFrolov** [reportportal/reportportal#1803]
**Make possible to assign people for test failure  analysis activity**
...

*So that when regression suite failed you can distribute activities by team member & team member can filter only those issues that he assigned to**

Ideally if additional feature present like assign team members based on history assignments, e.g. if person analyzed test failure yesterday, assign same test failure to same person again (use case - when this is Automation test failure reason and test was not properly fixed)
...

**Comment by alena-babrova** [comment]
Hello @AndriiFrolov 

At the moment, there is no option to make users assignments on the tests/failures.

However, I may suggest several workarounds you can consider.
1. You can use "Attributes" for tests when reporting them into our system, so that users can filter all items using the attributes. For example, attribute can have name of an area/functionality/etc., or even name of specific person from your team who is responsible for that area. This should be applied with every test results posting.
After that they can filter the failed items by the proper attribute:
![image](https://user-images.githubusercontent.com/89584140/194894451-4f81b5f9-1ff1-4274-94ce-cbbbf3eab27a.png)

2. If you can split the responsibility by the type of errors that occur, you can use Defect Types. The benefit of this is that Analyser can automatically assign Defect Types that were used for the same errors on previous runs.
But this works only based on the previous runs so you have to set Defect Types manually for new types of errors.
![image](https://user-images.githubusercontent.com/89584140/194895357-2557d982-d312-44dc-bfd9-9f21bdfdc7ec.png)

If you have any questions don't hesitate to ask us.
Thank you.

**Comment by alena-babrova** [comment]
Hello @AndriiFrolov 

I've talked to Product Owner and we have plans for the following functionality - "Assign users for failed tests".
Planned release version is 6.0.
At the moment you can use the workarounds that I described above.
I'm closing the issue with planed milestone. 
If you have any questions don't hesitate to get in touch.
Thank you!
