### ISSUE TITLE
[WIDGETS] No data available

### ISSUE THREAD

**Issue by ksuglotova** [reportportal/reportportal#181]
Received from the Alisa Guseva

In case if no data meet widget criteria, then 'no data available' is shown on a widget area. It would be better to have a option to hide the 'No data available' in case of all tests are in Passed status, for example.

**Comment by ksuglotova** [comment]
One of the possible options is to add configurable default message to the widget wizard. Then for pass/failed rate widget the default message may be 'No failed tests' if user decided to configure it

**Comment by avarabyeu** [comment]
@DzmitryHumianiuk @evjlobanova can we guys fix it since wontfix resolution is here

**Comment by DzmitryHumianiuk** [comment]
@avarabyeu I'm not sure we really should make such a fix.

request is to follow the specific configuration, and replace the default output for `No Data` with something like `All successful`

Custom thing for custom case.

 @evjlobanova could you please contact **Alisa**, in reportportal.slack.com and ask here for details and their specific use case with screenshots?

**Comment by evjlobanova** [comment]
@DzmitryHumianiuk @avarabyeu  Alisa said that  her team has a such case constantly, because all test cases are passed often. The most used widget is Launch execution and issue statistic, so the widget looks something like this.
![image](https://user-images.githubusercontent.com/30413511/32180072-0cf88202-bda2-11e7-876b-7d95d2247a7d.png)
  
I proposed her to use an Overall statistic widget with a dynamic filter (one launch selected)  and check  Passed, Failed, Sipped criteria only. 
The priority of this improvement is evaluated as low by the User.

**Comment by DzmitryHumianiuk** [comment]
@evjlobanova 
well. For **Launch execution and issue statistics** we can change default `No data available` with `No issues` for pie chart, which is responsible for issues in statistics.
Small improvement.

**Comment by evjlobanova** [comment]
We have refactored the Launch execution and issue statistics widget, so now, if a launch is passed, a user will see:
![image](https://user-images.githubusercontent.com/30413511/32235167-ccc7f554-be6f-11e7-8e04-c59de454c041.png)
