### ISSUE TITLE
Allow clients to publish directly to AMQ queues

### ISSUE THREAD

**Issue by rplevka** [reportportal/reportportal#1825]
**Describe the solution you'd like**
It would be great if the agents could directly connect and publish/consume messages to/from RabbitMQ. I believe this would allow much bigger throughput especially with logging.
With some ACL config on the RMQ level, this might be an interesting alternative.
...

**Is your feature request related to a problem? Please describe.**
Currently, all requests have to go through API service via HTTP. This often leads to service unavailability and intermittent issues with testing sessions that have live logging enabled

...

**Comment by DzmitryHumianiuk** [comment]
@rplevka this is a good idea.
and it might be the option for the version 6.

but i'm not sure if it will be easy to give access to the messages in rabbit directly.
since it will brake a lot of security limitations and restrictions.

The reason why we are sending messages and structure into the API first for the RP v4.x-5.x is because we should get a real database ID of the element to associate it with.
I mean, in order to store the test case, and use its real id for reporting of the logs, it have to be stored in database and the real id returned to the agent.

with the RP6 we will get structure by UUID, which even can be generated even on the client side.
in this case, we will have 2 unique identifiers, for instance, for the log: `launchID` and `UUID` of the parent test item generated on the client side.
For the front-end pretty enough to use as a unique key.

and they API will receive this request, and should not proceed it at all, and just push to the message bus. Where another log consumer can store it into elastic.

**Comment by HardNorth** [comment]
@DzmitryHumianiuk @rplevka Actually it's already possible to send `uuid` with requests: https://github.com/reportportal/commons-model/blob/develop/src/main/java/com/epam/ta/reportportal/ws/model/StartRQ.java#L63
And I believe there is no any limitations on posting to RabbitMQ directly.

The reason why we don't want to share it as a way of doing things is that RP itself already support different ActiveMQ providers. And each particular language and ActiveMQ provider has its own drivers with all sorts of configuration headache like: streaming/channels/unary call types, synchronous/asynchronous processing, direct/reactive clients, different configuration approaches, own bugs. It literally impossible to cover all use cases which will open if we decide that it's a good idea to post data directly into ActiveMQ providers.

@rplevka So two things here:
* There is no barrier here if you are ready investigate and implement it on you own
* We are not going to provide any support here, or discuss it on public to not provoke other users with less competencies do this, fail, and then post us issues with moaning for help

**Comment by DzmitryHumianiuk** [comment]
Agree with @HardNorth here.

Standardization is must for us. Since we have to have the same app running both for on-prem setup and in the cloud-native setup, based on cloud services.

And, AFIAK, rabbitMQ is hidden by default. One can still expose the port, and work with it directly.
but this is a _[rabbit hole](https://www.dictionary.com/e/slang/rabbit-hole/)_.


@HardNorth yes, we can send with `uuid`,
but we still have to get the uuid from the API first, in order to keep the data integrity (parent-child relations).
The trick happens, when we can generate UUID on the client/agent side both for parents and child, and send it to the API without any worries of getting parent ID in advance of sending child.

this also will remove all limitations and impediments in the Rabbit queues.
Since there is no need in all re-try queues. Consumers (APIs) can pull messages from the queue without specific order,
since integrity will be saved via solid relation of uuids formed on the client side.

**Comment by HardNorth** [comment]
@DzmitryHumianiuk It's up to user how to handle integrity. User can send self-generated UUID to parent item and place it as parent ID into child item. That's what we are going to do in version 6, but nothing can stop us doing it in version 5, we just need to move this logic on client.

**Comment by DzmitryHumianiuk** [comment]
@HardNorth i doubt if we need it in RPv5.
i would rather make it a part of RPv6 and save the effort for implementing v6, than back-porting it to v5.

at least we are doing the steps into the right direction.
