### ISSUE TITLE
Log page: width

### ISSUE THREAD

**Issue by ksuglotova** [reportportal/reportportal#183]
Can I configure log page width?
For example, for failed tests pick up the native android logs, in which key information is marked up by the 
https://github.com/orhanobut/logger

On Report Portal that mark up turns out to mess.

Received from @dkorobtsov (Slack/reportportal/russian).

**Comment by DzmitryHumianiuk** [comment]
@lexecon ?

**Comment by DzmitryHumianiuk** [comment]
@dkorobtsov could you update on this item?

is it still relevant, or you find workaround

**Comment by dkorobtsov** [comment]
@DzmitryHumianiuk yep, still relevant :)
it's no critical, of course, just a minor UI issue

**Comment by lexecon** [comment]
@dkorobtsov, It is possible to format your message log using the Markdown syntax. To do this, at the beginning of the message, you need to insert a key phrase `!!!MARKDOWN_MODE!!!`  and use this [syntax](https://simplemde.com/markdown-guide). You can disable the column view of the log so that it occupies the entire width of the screen. This functionality is called `console view`.
