### ISSUE TITLE
Elastic Search requirements for 5.7.2

### ISSUE THREAD

**Issue by anubhavsinghal07** [reportportal/reportportal#1840]
Hi Team,

 I am planning to upgrade to  5.7.2 version and I read the release notes, it says that the data will be stored in ElasticSearch and Postgres in parallel and after next release it will be migrated to ElasticSearch only.

So the question is regarding Elastic search requirements on the server, do we need to enhance anything on the server ( like HDD/RAM) and do we any need any premium/paid ElasticSearch service to use this version.

Do we need to perform any manual migration of this data in future or everything will done automatically after upgrade ?

Thanks

**Comment by DzmitryHumianiuk** [comment]
@anubhavsinghal07 this is a right question.

And yes, you need to increase RAM and CPU for the elasticSearch. Since it will now receive and process more data.
In case of cloud setup, i recommend to add more pods for elastic.

As for the data migration in v5.8, it will be handled automatically with the integrated scripts inside `migration` contrainer.
Migration of logs will be done based on launch id.
i mean, if logs with launch id not found that it will read and post logs into the elastic.
