### ISSUE TITLE
Is it possible to download Launch Controller data with API? 

### ISSUE THREAD

**Issue by LyuboKushev** [reportportal/reportportal#1850]
I would like to export all of Launches records using Python. 
When I use the standard address: https://saas.reportportal.io/api/v1/MY__PROJECT/launch + access_token = MY_TOKEN and have set the "Authorization" header to "Bearer MY_TOKEN" I only get the first 20 records available. 

When I go through the web interface, I can set the page.size = 300, and page.page = 5, however after I download the json file and read it with pyhton I can only read the 300 records from the last page (page 5).

My question is: Is there a dynamic way through which I can set the API to download all Launches records? 
Thanks!

**Comment by DzmitryHumianiuk** [comment]
@LyuboKushev there is no API call to get all-all-all launches in one call, neither like any other object in RP. And never will be.
just because you may have hundred of thousands items and basically bring the server down to knees.

Because of that there is a best practice called **Pagination**.
which means that API will return you a paged data, including information about total pages, total items, size and current page.

Within the first response you will have everything you need.
1. Get number of pages
2. iterate pages in the loop 


```bash 
curl https://SERVER/api/v1/PROJECT/launch?page.page=1&page.size=50&page.sort=startTime,number,DESC
```
returns:
```json
{
    "content": [
        ...
    ],
    "page": {
        "number": 1,
        "size": 50,
        "totalElements": 234,
        "totalPages": 5
    }
}
```

`totalPages` gives you the number.

run the loop with `page.page=N`
```
page.page=1
page.page=2
page.page=3
page.page=4
page.page=5
```
and concatenate lists.

done.
