### ISSUE TITLE
[Feature Request] Add possibility to create and save filters based on test name of all tests in launch

### ISSUE THREAD

**Issue by oglagovskiy** [reportportal/reportportal#186]
Right now, we can only save filters for launches.
But imagine situation when i have 1 launch with different browsers and decided to create dashboards based on Chrome only test results, another for FF only test results and so on. But they are all in launch. We can't create those dashboards, because we can't create saved filter based on test name for the whole launch.
Ideally we would have:
Launch on 200 smoke tests, inside:
50 Chrome <-- created filter 1 for Launch Name cnt some name or Tags are equals Smoke + Test Name contains Chrome
100 Firefox <-- created filter 2 for Launch Name cnt some name or Tags are equals Smoke + Test Name contains FF
100 IE11<-- created filter 3 for Launch Name cnt some name or Tags are equals Smoke + Test Name contains IE11
Then we can create dashboards for each of this to analyze them separately.

**Comment by ksuglotova** [comment]
#74 has the similar requirements

**Comment by evjlobanova** [comment]
I suppose for this reasons, you can use Component Health check widget. 
This widget shows the passing rate of the application components which are indicated by the specified attributes.

Use case:

Situation: As a Project Manager or Test Lead, a I want to see the most unstable place in my product ( application).

Solution: All test cases in my project in ReportPortal have an attributes. For example function: (order, team, configure, administrative), type: (backend, API, Unit, UI), ...., marketstate: (open, close), role: (ProjectManager, Member, Admin) and other. The attributes can be different and dependend on your project needs.

A user can create a Component Health Check Widget and set attribute key = function for the 1st level, for the 2nd -type and for the 3rd - marketstate

So that a user will see on the first level a several groups: order, team, configure, administrative. All groups will contains only test cases with attribute which contain attribute key function. Each group has been grouped by attribute value: order, team, configure, administrative. If a user clicks on the group function: order, the system will show the second level of the widget. All test items on the second level will be contain the attribute function: orderand attributes which contain attribute key: type. And these items will be grouped by attribute values: backend, API, Unit, UI. The same logic will be applied for the next levels.
![image](https://user-images.githubusercontent.com/30413511/76970027-4b452b80-693c-11ea-8329-e9c0ee299b61.png)

**Comment by evjlobanova** [comment]
Closed as a duplicate
