### ISSUE TITLE
Upload logs, screenshots and videos after test ended

### ISSUE THREAD

**Issue by badrinrs** [reportportal/reportportal#1869]
Is there a way to upload logs, screenshots and videos to a test or test step after a test completion?

This is essential in mobile use case wherein test can crash upon which tests complete. We do store launchUUID and  UUID for later usage. I am unable to post files to the launchUUID after the launch is complete.

I have tried using the following API(s):

1. `/v1/{projectName}/log/entry`
2. `/v2/{projectName}/log/entry`

**Comment by badrinrs** [comment]
@DzmitryHumianiuk Can you please advise how I can upload logs/screenshots/videos after a test run is complete.

**Comment by DzmitryHumianiuk** [comment]
@badrinrs please take a look here
https://github.com/reportportal/examples-java/blob/master/example-testng-logback/src/main/java/com/epam/reportportal/example/testng/logback/callback/CallbackReportingTest.java

this is a callback function, which retrieves the last test item and sending a log to it after the test finish. The test works only if
  <code>rp.reporting.callback</code> property set to <code>true</code>.

And practically you are making the right steps.
In order to push the log, you need to know the **uuid** of current test case, but not the launch (not launchUUID)
https://github.com/reportportal/documentation/blob/master/src/md/src/DevGuides/reporting.md#batch-save-logs
