### ISSUE TITLE
Report Portal in Rancher

### ISSUE THREAD

**Issue by cybem** [reportportal/reportportal#187]
Hi guys,

Firstly, I would like to thank you for the awesome and very useful software.

But recently we've faced some problem when we were trying to start Report Portal under [Rancher](http://rancher.com/rancher/).

# The short version

Under Rancher, Docker containers can't communicate with each other using their own hostnames (which coincide with their container IDs).

# The long version

1. Report Portal uses [Eureka](https://github.com/Netflix/eureka) as a discovery solution.
2. Every service announces itself in Eureka server using their own hostname (which coincide with their container ID).
3. Report Portal Gateway service uses Eureka to know upstreams of service endpoints. It fetches upstreams from Eureka and runs health checks. Actually, it fetches container hostnames.
4. During health checks, Gateway tries to resolve container hostnames to their own IPs using Rancher DNS server and fails due to Rancher architectural design. Rancher developers believe (Rancher issue [#5761](https://github.com/rancher/rancher/issues/5761)) that containers must not communicate directly using their own hostnames. Containers should communicate using service name that is an abstraction in Rancher. I think Rancher guys are right.
5. Due to the impossibility to resolve hostnames, Gateway service decided that their upstreams are down and Gateway service silently ignores incoming requests (returns nothing).

# The workaround we've used

After a bit of research, we found a workaround for the problem. The problem is known and workaround is described [here](https://forums.rancher.com/t/trying-to-run-eureka-netflix-under-rancher-resolving-issues/777/4). Fortunately, Eureka client allows to override hostname provided to Eureka server during registration using the `eureka.instance.hostname` Java system property. Inside Docker container, we can obtain service name doing a request to the special URL - http://rancher-metadata.rancher.internal/latest/self/container/service_name. So our code that runs Java application looks like that:

```
EUREKA_INSTANCE_HOSTNAME=$(curl http://rancher-metadata.rancher.internal/latest/self/container/service_name)
java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -Deureka.instance.hostname="$EUREKA_INSTANCE_HOSTNAME" -jar /app.jar
```

# Some possible solutions to the problem

1. Check if a container is launched inside Rancher and use the technique described above. This can be integrated into existing Dockerfiles or we can use a separate shell script.
2. Improve Eureka client in order to support Rancher services. I didn't dive into the Eureka source code deeply, but I think that a sort of provider (in terms of Eureka) can be implemented.

# Further work

We are ready to do everything to make Report Portal work in Rancher out of the box. Do you need extra information? What pull request are you ready to accept?

Thanks in advance.

**Comment by avarabyeu** [comment]
@cybem hi! Thanks for the detailed info. Actually, we are about to migrate from Eureka to Consul in couple of weeks. But issue you mentioned is still supposed to be reproduced - you have to point each service to the right service registry instance. What i would suggest is to use env properties instead of JVM vars. This way you can pass right value using docker-compose file and avoid re-creating images. For the eureka, right env variable name would be: 'EUREKA_INSTANCE_HOSTNAME'

But again, we are migrating to Consul. Netflix's gateway is supposed to be replaced with [fabio](https://github.com/fabiolb/fabio). The scheme is the same - service registers itself in service registry and then gateway (load balancer) takes info from registry and routes requests to the appropriate container. So, anyway you have to pass some custom hostname to the registry to let it know what hostname is actually should be used to access the service. 
Have a look at the configuration of some service (API in example):
```yaml
eureka:
  instance:
    hostname: ${HOSTNAME:api}
```
You can try to export $HOSTNAME env variable and it will be used as hostname of container in the registry. This same thing is configured for consul:
```yaml
  cloud:
    consul:
      host: registry
      discovery:
        hostname: ${HOSTNAME:api}
        prefer-ip-address: false
```
*Summarizing everything.*
I believe, we don't need to have any additional stuff to support Rancher. It's possible to configure DNS information right into the docker-compose file via env vars. Let's try to go this way. If you face any issue, feel free to ask questions, we are open to cooperation and making configuration management better. 

Regarding PRs, we are ready to accept everything that can be useful for the users. So, feel free to create one and we will discuss it.

**Comment by avarabyeu** [comment]
@cybem can we close the issue?

**Comment by cybem** [comment]
Thank you, Andrei @avarabyeu, for your comprehensive response.
Yes, I think the issue can be closed.
We are going to try a new version of Report Portal.

Best wishes.
