### ISSUE TITLE
Configure SAML Max Session Length Via Environment Variable

### ISSUE THREAD

**Issue by quinn-kleinschmidt-milwaukeetool** [reportportal/reportportal#1876]
Recently I have enabled Microsoft SAML in my Report Portal instance. I have had users recently getting 403 errors thrown when reaching on uat/saml/sp/SSO/alias/report-portal-sp. I am facing the same problem as described in this [issue](https://github.com/reportportal/reportportal/issues/1618) in which the max session life is hardcoded and too short for my use case. Currently this values is hardcoded as 4320 seconds in the [application.yaml](https://github.com/reportportal/service-authorization/blob/master/src/main/resources/application.yaml). Can this be made so it can be configured as an environment variable?

**Comment by raikbitters** [comment]
@quinn-kleinschmidt-milwaukeetool  We will provide this parameter via environment property in the future realize. As a fast solution - you can synchronize a live session duration on the SAML provider side. We use two days for a duration session by default on the ReportPortal side.

**Comment by quinn-kleinschmidt-milwaukeetool** [comment]
Yeah no worries I already have a work around I am using for this issue. I just though it would be nice to have a better way to configure this in the future which is why I created this issue.

**Comment by VeranikaRymzha** [comment]
Hello there,
@quinn-kleinschmidt-milwaukeetool , FYI
The issue was fixed by the team: Saml live session will be configurable via env variable RP_SAML_SESSION-LIVE= #time in minutes.
This improvement will be a part of the next release of ReportPortal. We plan it for April.

**Comment by MeirsPortal** [comment]
Thank you very much Veranika.
Looking forward for this fix in your next release 5.7.4

Best regards,
Meir.

קבל ‏Outlook עבור Android‏<https://aka.ms/AAb9ysg>

________________________________
מאת: Veranika Rymzha ***@***.***>
נשלח: יום שלישי, 28 בפברואר 2023, 21:42
אל: reportportal/reportportal ***@***.***>
עותק: Meir Halfon ***@***.***>; Manual ***@***.***>
נושא: Re: [reportportal/reportportal] Configure SAML Max Session Length Via Environment Variable (Issue #1876)


Hello there,
@quinn-kleinschmidt-milwaukeetool<https://github.com/quinn-kleinschmidt-milwaukeetool> , FYI
The issue was fixed by the team: Saml live session will be configurable via env variable RP_SAML_SESSION-LIVE= #time in minutes.
This improvement will be a part of the next release of ReportPortal. We plan it for April.

**Comment by MeirsPortal** [comment]
> Hello there, @quinn-kleinschmidt-milwaukeetool , FYI The issue was fixed by the team: Saml live session will be configurable via env variable `RP_SAML_SESSION-LIVE= #time in minutes`. This improvement will be a part of the next release of ReportPortal. We plan it for April.

When do you expect to release 5.7.5 with is fix?

**Comment by VolhaKarenko** [comment]
Hi @MeirsPortal, the release is planned around the end of May

**Comment by MeirsPortal** [comment]
Hi,

Is this fix part of v23.1 release? 
I couldn't find it in the release notes: https://reportportal.io/releases

**Comment by VolhaKarenko** [comment]
Hi @MeirsPortal,
Yes, it is mentioned in the third section "Enhancements Based on Community Feedback" with a reference to https://github.com/reportportal/reportportal/issues/1618

**Comment by DzmitryHumianiuk** [comment]
fixed.

**Comment by Idosegal** [comment]
We have upgraded our environment from 5.7.0 to the latest (1.23) mainly because of this improvement.
I have adjusted the `samlSessionLiveTime` parameter to 129600 (Azure AD default session lifetime), and the uat service failed to start.
Log file is attached.
[reportportal-uat-ff9c87cc6-jqsx7.log](https://github.com/reportportal/reportportal/files/11929276/reportportal-uat-ff9c87cc6-jqsx7.log)

**Comment by APiankouski** [comment]
When 129600 minutes was converted to milliseconds result exceeded allowable rage of int32.
The max allowable value for samlSessionLiveTime is around 34560 minutes (24 days)

**Comment by DzmitryHumianiuk** [comment]
@Idosegal check the comment above
