### ISSUE TITLE
JUnit ignored class not counted in the launch as skipped

### ISSUE THREAD

**Issue by vfedirko5** [reportportal/reportportal#1913]
**Steps To Reproduce:**
- Ignore test class(not a method) via JUnit4 "@Ignore" annotation
- Run tests
- Observe the ReportPortal launches

**Actual Result:** 
- Tests in the class not identified as skipped and not presented in Total statistic

**Expected Result:**
- When whole test class was ignored all test methods(tests) should be marked as skipped and counted in Total statistics  as well

 **Build** 5.7.3

![ohIvJ1mhbp](https://user-images.githubusercontent.com/97690476/210882311-5b8376c0-039f-4660-9ccf-9c7f092b8b74.png)
![bamboo](https://user-images.githubusercontent.com/97690476/210882069-f3799b85-c092-4551-9ac5-bc182af661c8.png)
![oDkZmKA4kt](https://user-images.githubusercontent.com/97690476/210882611-cb1c3b55-6185-4696-bf60-8f6a0f298ee0.png)

**Comment by HardNorth** [comment]
@MaryiaRymarchyk @vfedirko5 There is no option to report such tests, because JUnit 5 does not send any details about the amount of tests which were skipped in that case. So the only option is implement some logic to scan the whole class for tests which are defined there, but it's extremely difficult due to the following reasons:
1. JUnit 5 has conception of dynamic tests and test Generators. It's not possible to say how many tests there are without calling such methods, which might not run because will be called outside JUnit 5 context.
2. Inheritance: such classes might contain various amount of derived classes, and you should scan the whole classpath to find them.
3. Extensions and custom annotations, which might affect the number of tests. We are not a test framework, we know nothing about neighbour extensions and should not know about them.

Given all of these I came to the only possible solution for us: do not even try to do JUnit's job and implement this logic for them. For those who want to challenge themself I left a special method:
https://github.com/reportportal/agent-java-junit5/blob/develop/src/main/java/com/epam/reportportal/junit5/ReportPortalExtension.java#L855

You are free to extend our class and implement it yourself.
