### ISSUE TITLE
skipped tests come up with "To_Investigate" by default

### ISSUE THREAD

**Issue by rujutashinde** [reportportal/reportportal#1967]
When i import a junit file using the `/import` reportportal api or from the gui, all the skipped tests in the junit file come up with `To Investigate`.

![image](https://user-images.githubusercontent.com/86486008/227024810-7982db76-40be-4487-8076-0497f56ec3de.png)

Can we change this behavior so that skipped tests by default do not show up with anything? like this:

![image](https://user-images.githubusercontent.com/86486008/227024954-3e54e778-ee4b-484e-a7fb-bfc156b32429.png)

How can we modify these skipped items to not show up under `to_investigate` using an api?
i tried using the following but it does not change anything but gives a success int he output

`curl -X PUT "https://reportportal-ccit.apps.ocp-c1.prod.psi.redhat.com/api/v1/dr_test_project/item/211768/update" -H  "accept: */*" -H  "Content-Type: application/json" -H  "Authorization: bearer <token>" -d "{      \"statistics\": {        \"executions\": {          \"total\": 1,          \"skipped\": 1        },        \"defects\": {}        },        \"issue\": {}}"`

```
200 | Response body
{   "message": "TestItem with ID = '211768' successfully updated." }
```
the test item still is seen as to_investigate

Request URL
`https://<my_reportportal_instance>/api/v1/dr_test_project/item?filter.eq.id=211768&filter.eq.launchId=7925&isLatest=false&launchesLimit=0`

```
{
  "content": [
    {
      "id": 211768,
      "uuid": "3b0e0201-9ead-4e41-aee0-64fdf2491fde",
      "name": "test_set_release",
      "parameters": [],
      "attributes": [],
      "type": "STEP",
      "startTime": 1679509375609,
      "endTime": 1679509412372,
      "status": "SKIPPED",
      "statistics": {
        "executions": {
          "total": 1,
          "skipped": 1
        },
        "defects": {
          "to_investigate": {
            "total": 1,
            "ti001": 1
          }
        }
      },
      "parent": 211640,
      "pathNames": {
        "launchPathName": {
          "name": "skip_issue",
          "number": 2
        },
        "itemPaths": [
          {
            "id": 211640,
            "name": "satellite611"
          }
        ]
      },
      "issue": {
        "issueType": "ti001",
        "autoAnalyzed": false,
        "ignoreAnalyzer": false,
        "externalSystemIssues": []
      },
      "hasChildren": false,
      "hasStats": true,
      "launchId": 7925,
      "uniqueId": "auto:52021781b03306a6706888210a1ff2d0",
      "testCaseHash": 1466118777,
      "patternTemplates": [],
      "path": "211640.211768"
    }
  ],
  "page": {
    "number": 1,
    "size": 20,
    "totalElements": 1,
    "totalPages": 1
  }
}
```

I have used the reportportal python client where when we are finishing a test item we can send `issue_type as NOT_ISSUE` and that testitem does not get marked as to investigate. What can be done using RP api ? or if there is a configuration that can be edited on the Reportportal instance itself?

```
Current version:
API Service: 5.7.2;
Authorization Service: 5.7.0;
Service UI: 5.7.2;
```

Appreciate the help

**Comment by DzmitryHumianiuk** [comment]
@rujutashinde 
well, first of all this `NOT_ISSUE` is a sort of shamy legacy from the early stages of ReportPortal.
this will be address with a new API in RPv6.

I've played with API, and found out this you can sent `NOT_ISSUE` when finishing the test.
But it won't be recognized on PUT/UPDATE of the test item.

asked the team if there is an available param to accomplish this.

But for now i can recommend to send **No Defect** issue type for the skipped test cases, which you want to update.
This will be the easiest way to go right now.

As for the general purpose of Defect assigned to Skipped item,
this is something we need to address in on the project level configuration.

References in documentaion:
https://reportportal.io/docs/dev-guides/ReportingDevelopersGuide/#finish-child-item

<img width="878" alt="image" src="https://user-images.githubusercontent.com/11332788/227602646-52b00125-bdf6-4cfa-8acf-03d8dacfca32.png">

<img width="899" alt="image" src="https://user-images.githubusercontent.com/11332788/227602748-d4a0f0ed-4901-47cd-844a-f56bc837c60e.png">

**Comment by DzmitryHumianiuk** [comment]
@rujutashinde you should send so call locator, instead of the text name of the issue.
To find it, open up project settings -> Defect Types -> hover the mouse on the defect name you need (see the picture below).

for the root of the ND group it always looks as: `nd001`

<img width="796" alt="image" src="https://user-images.githubusercontent.com/11332788/228058715-0b67397a-1871-47dd-b72b-1ab18acea43e.png">

here is my call via the _ITEM PUT_
```bash
curl 'https://SERVER/api/v1/PROJECT/item/' \
  -X 'PUT' \
  -H 'content-type: application/json' \
  -H 'authorization: bearer TOKEN' \
  --data-raw '{"issues":[{"id":2686841545,"testItemId":2686841545,"issue":{"issueType":"nd001"}}]}'
```

response:

> ignore the `externalSystemIssues` since it's just the test failure with issue which i've used.

```json
[
  {
    "issueType": "nd001",
    "autoAnalyzed": false,
    "ignoreAnalyzer": false,
    "externalSystemIssues": [
      {
        "ticketId": "EPMRPP-4",
        "btsUrl": "https://jiraeu-api.com/",
        "btsProject": "EPMRPP",
        "url": "https://jiraeu.com/browse/EPMRPP-4",
        "pluginName": "jira"
      }
    ]
  }
]
```
and here is what i see on UI after it:
<img width="1398" alt="image" src="https://user-images.githubusercontent.com/11332788/228059394-f412f1a4-28c6-44e0-a6a1-e6d465cf0dff.png">

as for your requests:
Well, and looks like it's a bug or form of inconsistency:
my call to _item/ID/update_ with a PB defect

```
curl 'https://SERVER/api/v1/PROJECT/item/2686841545/update' \
  -X 'PUT' \
  -H 'content-type: application/json' \
  -H 'authorization: bearer TOKEN' \
  --data-raw '{"issues":[{"issue":{"issueType":"pb001"}}]}'
```

returns me 
```json
{
  "message": "TestItem with ID = '2686841545' successfully updated."
}
```
but no update appear.

<img width="1426" alt="image" src="https://user-images.githubusercontent.com/11332788/228062203-ffe71fbf-5c13-4cf1-b90f-67b5927d7676.png">

**Comment by DzmitryHumianiuk** [comment]
@rujutashinde 
it might me a bit misleading in the endpoint naming,
but descriptions says it all:

update of issues
<img width="1358" alt="image" src="https://user-images.githubusercontent.com/11332788/228066072-92580143-ea7b-4569-b30e-6c6603fa3d2e.png">

update of test item details itself
<img width="1374" alt="image" src="https://user-images.githubusercontent.com/11332788/228066011-29d58f65-9b46-4205-ae98-4b5b3ab10738.png">

Plus the test item update can receive the changed date only, there is no need to send the whole object as it should be.
Thus, it ignores something out of scope of this update.

@rujutashinde you should send so call locator, instead of the text name of the issue.
To find it, open up project settings -> Defect Types -> hover the mouse on the defect name you need (see the picture below).

for the root of the ND group it always looks as: `nd001`

<img width="796" alt="image" src="https://user-images.githubusercontent.com/11332788/228058715-0b67397a-1871-47dd-b72b-1ab18acea43e.png">

here is my call via the _ITEM PUT_
```bash
curl 'https://SERVER/api/v1/PROJECT/item/' \
  -X 'PUT' \
  -H 'content-type: application/json' \
  -H 'authorization: bearer TOKEN' \
  --data-raw '{"issues":[{"id":2686841545,"testItemId":2686841545,"issue":{"issueType":"nd001"}}]}'
```

response:

> ignore the `externalSystemIssues` since it's just the test failure with issue which i've used.

```json
[
  {
    "issueType": "nd001",
    "autoAnalyzed": false,
    "ignoreAnalyzer": false,
    "externalSystemIssues": [
      {
        "ticketId": "EPMRPP-4",
        "btsUrl": "https://jiraeu-api.com/",
        "btsProject": "EPMRPP",
        "url": "https://jiraeu.com/browse/EPMRPP-4",
        "pluginName": "jira"
      }
    ]
  }
]
```
and here is what i see on UI after it:
<img width="1398" alt="image" src="https://user-images.githubusercontent.com/11332788/228059394-f412f1a4-28c6-44e0-a6a1-e6d465cf0dff.png">

as for your requests:
my call to _item/ID/update_ with a PB defect

```
curl 'https://SERVER/api/v1/PROJECT/item/2686841545/update' \
  -X 'PUT' \
  -H 'content-type: application/json' \
  -H 'authorization: bearer TOKEN' \
  --data-raw '{"issues":[{"issue":{"issueType":"pb001"}}]}'
```

returns me 
```json
{
  "message": "TestItem with ID = '2686841545' successfully updated."
}
```
since my payload do not contains anything, which affects details level of the test case.

but agree, this might be a bit misleading.

**Comment by rujutashinde** [comment]
Thank you! @DzmitryHumianiuk
