### ISSUE TITLE
Add option for Flaky Tests widget to support retries

### ISSUE THREAD

**Issue by vadim-garbuz** [reportportal/reportportal#2002]
Flaky tests widget does not appear to take in account tests that have failures in retried launches
e.g. if the test failed in original launch, but passed in retry, then in overall stats it is reported as passed (and this is good) but it is also reported as passed in flaky tests widget (this is not so good) as this test has a change from fail to pass

**Comment by Kozovskaya** [comment]
Hello @vadim-garbuz, thank you for your request.
That's right, currently the 'Flaky Tests Cases' widget takes into account the last status of retry, because the widget is build to show the **test status for particular launch execution** and the final status of test of this launch - it's the last retry.
If you want to see all the statuses of the test you need to make a new launch execution and not a retry of a single test.

**Comment by Kozovskaya** [comment]
Currently we don't plan to change the logic of the widget, but probably in future we will think about such functionality!
