### ISSUE TITLE
DB size increased

### ISSUE THREAD

**Issue by babantax** [reportportal/reportportal#2016]
Hi Team, I´m seeing from some time ago that the database of my Report Portal instance is growing very fast. Checking the tables by size I see that there are some indexes that have abnormal sizes (See screenshot) Any Idea of what can be happening?

![image](https://github.com/reportportal/reportportal/assets/52815118/5ec2b3c5-a342-41a6-a4e8-3506347a90f0)

**Versions:**
 - Version of RP 5.7.3
 - Postgres 11.7

**Comment by irynakozak2** [comment]
@babantax Hi! Since the PostgreSQL database is not releasing the disk space physically after the deletion of the data (called the dead tuples), we recommend considering to setup the downtime and maintenance window periodically to conduct the VACUUM FULL operation. 

Could you please share the result of the following queries:

`SELECT relname, n_dead_tup FROM pg_stat_user_tables order by n_dead_tup desc;`
`SELECT relname, last_vacuum, last_autovacuum FROM pg_stat_user_tables;`

Waiting for your reply.

**Comment by irynakozak2** [comment]
@babantax Hi! Long time no hear from you, so I close that issue for now. If that issue is still relevant for you after the VACUUM FULL execution or if you need other help - please reply to this ticket or consider creating a new one.
Thank you!
