### ISSUE TITLE
Exclude and include some attributes simultaneously in one single launch filters

### ISSUE THREAD

**Issue by forelock7** [reportportal/reportportal#2036]
**Describe the solution you'd like**
Add possibility to **exclude** one attribute and **include** another attributes  in **one filter** of launches

**Is your feature request related to a problem? Please describe.**
It's hard to manipulate with launch filters. I only can choose single action(_all/without all/any/without any_) for multiple attributes.
It will be very convenient to choose different action for different attributes in one single launch filter.

**Comment by Kozovskaya** [comment]
Hello @forelock7! 
Yes, currently you can filter launches only by one attribute option and I understand that sometimes it's necessary to have more options. We are now thinking about updating our Filter so that it could provide for our users additional possibilities. We plan to cover your case.
As we already have similar issue regarding Filter (https://github.com/reportportal/reportportal/issues/1918) I will close this one!

**Comment by Kozovskaya** [comment]
Hello @forelock7! 
Yes, currently you can filter launches only by one attribute option and I understand that sometimes it's necessary to have more options. We are now thinking about updating our Filter so that it could provide for our users additional possibilities. We plan to cover your case.
As we already have similar issue regarding Filter (https://github.com/reportportal/reportportal/issues/1918) I will close this one!

**Comment by forelock7** [comment]
Thanks for response.
