### ISSUE TITLE
unable to access report portal from another machine

### ISSUE THREAD

**Issue by mahadevk8** [reportportal/reportportal#2041]
I have installed report portal with docker set up on my local mac and my teammate trying to access report portal from his system.
We are getting "This site can't be reached."

**Comment by MaryiaRymarchyk** [comment]
Hi @mahadevk8  it is quite difficult to help cause this message could appear for a lot of errors. The most common causes are:
    DNS resolution errors
    Connections that time out
    An overall failure of your internet connection
    Misconfigured internet, network, or firewall settings, VPN, etc.

I assume that issue is not in RP application, but in Internet connection. Try to find solution in the internet (e.g. https://www.atatus.com/blog/how-to-fix-this-site-cant-be-reached-error/#solutions-to-fix-this-site-cant-be-reached-error).

**Comment by MaryiaRymarchyk** [comment]
@mahadevk8 do you have any updates here?

**Comment by DzmitryHumianiuk** [comment]
@mahadevk8 this is not ReportPortal issue.
Please google how to expose your application in network running in docker on MacOS.
