### ISSUE TITLE
Unable to login reportportal with LDAP credentials.

### ISSUE THREAD

**Issue by Dhaamodharan** [reportportal/reportportal#2080]
Integrated LDAP plugin with proper config and it was working good for couple of weeks. All of a sudden now unable to login and its throws the below exception

```An error occurred while connecting to server: You do not have enough permissions. xxxx.xxx.com:3268, nested exception is javax.naming.CommunicationException: xxxx.xxx.com:3268 [Root exception is java.net.UnknownHostException: xxxx.xxx.com]```

**Comment by DzmitryHumianiuk** [comment]
@Dhaamodharan my first thought sit on the side that your LDAP server don't allow RP server to communicate with it.

The full response will be:

The error message provides some clues about what might be causing the issue when trying to connect to the LDAP server:

1. **Permission Issue**: The initial part of the error message "You do not have enough permissions" suggests that the credentials or the account being used to connect to the LDAP server may not have adequate permissions. You might need to check if the account has the necessary permissions to access the desired resources on the LDAP server.

2. **UnknownHostException**: The latter part of the error "java.net.UnknownHostException: xxxx.xxx.com" indicates that the system is unable to resolve the hostname (xxxx.xxx.com) to an IP address. This could be due to:
   - A typo in the server name.
   - DNS resolution issues.
   - Network connectivity problems between your machine and the LDAP server.
   - The server being down or unreachable.

Here are some steps you can take to troubleshoot the issue:

1. **Verify the Hostname**: Double-check the hostname (xxxx.xxx.com) to make sure it's correctly spelled and points to the intended LDAP server.
  
2. **Test DNS Resolution**: You can use tools like `ping`, `nslookup`, or `dig` to check if the hostname correctly resolves to an IP address.

3. **Network Connectivity**: Ensure that there's network connectivity between your machine and the LDAP server. You can use tools like `ping` or `traceroute` to check this.

4. **LDAP Port**: The error message indicates that the connection is trying to be made on port 3268. This is typically used for global catalog queries in Microsoft's Active Directory. Ensure that this is the correct port, and the server is listening on it.

5. **Check Server Status**: If you have access, ensure that the LDAP server is running and is reachable from your network.

6. **Firewall/Security Groups**: Ensure that any firewalls or security groups are not blocking the connection to the LDAP server.

7. **Check Credentials**: Make sure you're using the correct credentials, and they have the required permissions to connect to the LDAP server.

If you've checked all of these and are still facing issues, you might want to engage with your network or system administrators to dive deeper into the problem.
