### ISSUE TITLE
Can triage result migrate over to different project as well?

### ISSUE THREAD

**Issue by saurabhsrivastava2009** [reportportal/reportportal#2086]
Hi Team,

In our current setup, we have a job which triggers multiple child job which will act as a launch is RP side. So we have a common project where all the child data will be populated and also will be populated in the child specific projects.
So say for e.g. I have triaged a failure in the child project, is there a way to pass on that triage information to the main/common project as well?
Do we any settings/config or APIs to achieve this?

Thanks in advance
Saurabh

**Comment by MaryiaRymarchyk** [comment]
Hi @saurabhsrivastava2009,  what do you mean by child specific project in terms of RP? 
Actually we don't have any relation between projects for now. Each project on RP side is independent from others and has it's own settings. 
But if we talk about launch and analysis of failures - here AutoAnalysis may help you. If you have similar logs in several launches and you have triaged failures in one of them - then you can initiate AutoAnalysis manually on all other launches, so all similar logs will be defined with same defect type.
Probably i didn't get you right, if so - please clarify your question.

**Comment by saurabhsrivastava2009** [comment]
Hi @MaryiaRymarchyk 
By "child specific project", I meant that our main job(master job) triggers multiple product jobs(child jobs). We have created project for each product(say 5 projects for 5 products) and one common project for all(Cumulative product data).
We send the same data to both types of project. Common Project will collect all product data, whereas the product specific project will collect only their respective data.

- The common project is for managers view
- Product based projects are for triagers/automation engineers.

Now when they(automation engineers) triage something on their project, that triagging result is not reflected in the common project. So the issue here is the managers are not able to see the defects, which essentially doesn't seems right. Now if managers also want to see the defect data, someone from the automation team have to triage the same failures again.

AutoAnalysis works for the same project, but not across different projects. 

So I was looking for some workaround, or maybe an API which can help us to resolve this manual effort?

Let me know if you got my question here?

**Comment by MaryiaRymarchyk** [comment]
Unfortunately as I say above, RP doesn't have any relation between projects for now. Each project on RP side is independent from others and has it's own settings. And AutoAnalysis works inside one index (one project).
We plan in far future that relation between projects will be possible but it is not our near-term priorities.
Maybe you can try aggregate your data in different launches with different attributes inside one project. Then you will be able to filter launches by attributes -  for the manager and for the automation engineers. And AA will work for all launches inside one project.

**Comment by DzmitryHumianiuk** [comment]
@saurabhsrivastava2009 what you're describing should likely be addressed not by transferring the triage solution to other projects, but by introducing sub-streams within projects.

We have a feature in our backlog that involves modifying the project structure by adding new levels. Essentially, we're introducing an Organization - Project - Stream structure. Here, streams can serve the role of those child projects and essentially act as virtual divisions within a single container called Project.

In this approach, the Cumulative Product Data would be at the Project level. When automation engineers triage individual products within each sub-stream, there won't be a need to copy or redirect the results elsewhere. This is because the Project itself will be the repository for common data.

Any other approaches or workarounds are essentially a waste of time and akin to building castles in the sand. This is because the logic should be addressed with a different approach, and any temporary modifications will be replaced by a new and robust logic.

**Comment by DzmitryHumianiuk** [comment]
This is correlated with all: https://github.com/reportportal/reportportal/labels/Feature%3A%20OrganizationLevel
- https://github.com/reportportal/reportportal/issues/1537
- https://github.com/reportportal/reportportal/issues/1297
- https://github.com/reportportal/reportportal/issues/644
- https://github.com/reportportal/reportportal/issues/454
- https://github.com/reportportal/reportportal/issues/193

**Comment by DzmitryHumianiuk** [comment]
This is not directly one-to-one correlation with this request: https://github.com/reportportal/reportportal/issues/193
but practically related, since the solution is equal for both of them.

Closing with respect to https://github.com/reportportal/reportportal/issues/193
