### ISSUE TITLE
Unable to get last 5 status of a test case using API

### ISSUE THREAD

**Issue by saurabhsrivastava2009** [reportportal/reportportal#2122]
Hi Team,

I'm trying to get the status of a test case for the last 5 launches. I would like to know and report how it performed over the last 5 runs.

The APIs that I'm using is as follows
`GET https://{{ourProjectURL}}/api/v1/{{projectName}}/item?filter.name={{testCaseName}}&page.size=1`

I'm hoping this will return us the testCaseID, but it throws error 400 bad request
```
{
    "errorCode": 40011,
    "message": "Incorrect filtering parameters. Incorrect format of filtering parameters"
}
```

If I get the testCaseID, then using that I was hoping to use the following to get the last 5 status
`GET https://{{ourProjectURL}}/api/v1/{{projectName}}/item?filter.type=TEST_CASE&filter.parentId={{testCaseItemId}}&page.size=5`

I also tried to use the endpoints given in https://reportportal.io/docs/dev-guides/APIDifferencesBetweenV4AndV5#test-item-controller, but not sure how to use it to get the results from the last 5 runs for a testcase.

Can you let me know if this flow is correct?

Thanks in advance :)

**Comment by DzmitryHumianiuk** [comment]
there is a history endpoint for the item.
`GET https://{{SERVER}}/api/v1/{{PROJECT}}/item/history?historyDepth=5&type=line&filter.eq.id={{ID}}`

**Comment by saurabhsrivastava2009** [comment]
Hi @DzmitryHumianiuk 
What is the `{{ID}}` here? Is this the testID that gets generated at the time of calling the following API?
`POST https://{{SERVER}}/api/v1/{{PROJECT}}l/item/{{classId}}` which gives us testID

As I tried with it but getting the following error
```
{
    "timestamp": 1694507312411,
    "status": 400,
    "error": "Bad Request",
    "path": "/v1/superadmin_personal/item/history"
}
```

**Comment by saurabhsrivastava2009** [comment]
Hi @DzmitryHumianiuk 

I got how to got ID, but its from the UI. Is there any way to get the ID during runtime?

I tried to use the following endpoints to get the project ID first 
`GET https://{{SERVER}}/api/v1/project/list`

This returns the response in this form ( removing projects which are required here)
```
{
    "content": [
        {
            "id": 1,
            "projectName": "superadmin_personal",
            "usersQuantity": 1,
            "launchesQuantity": 8,
            "launchesPerUser": null,
            "uniqueTickets": null,
            "launchesPerWeek": null,
            "lastRun": 1689780242413,
            "creationDate": 1683850062438,
            "entryType": "PERSONAL",
            "organization": null
        }
    ]
}
```

After this I was thinking of using the following API to get the testcase id
`GET https://{{SERVER}}/api/v1/projects/{{projectID}}/test-case`

where `{{projectID}}`, I think is the `id `from the above response.
But this throes a 404 not found error
```
{
    "timestamp": 1694524175643,
    "status": 404,
    "error": "Not Found",
    "path": "/v1/projects/1/test-case"
}
```

Is there a way to get the Test case ID during runtime?

**Comment by DzmitryHumianiuk** [comment]
@saurabhsrivastava2009, ReportPortal has two distinct types of Identification Numbers:

1. **`ID`**: This is the Database ID, which is generated once the element is recorded in the DB on the API side.
2. **`UUID`**: This stands for Universally Unique Identifier. It's generated either on the Message Queue side, when API receives the request, but not yet process it,  or generated on the Client side (test framework).

This means every object has a `UUID` even before it's recorded in the database and assigned a real `ID`. This situation arises when a request received by the API is queued for processing. The only way to identify this element during this phase is by its `UUID`. Having a `UUID` also allows us to send a callback to the initiator (test framework), essentially saying "we got your item, don't wait for the server processing", and continue executing.

Endpoints accessed via `/api/v1` typically use `ID` as the identifier since these are synchronous calls. 
Endpoints accessed via `/api/v2` usually use `UUID` as the identifier since these are asynchronous calls.

A `UUID` will always look like `3eb84332-06d5-478d-b67e-a429601359a3`. [wiki](https://en.wikipedia.org/wiki/Universally_unique_identifier)
An `ID` will always be a `long` primitive number, like `818514142`.

**To address your question:**
When you send an API call to create a test item, you'll receive a `UUID` in response. Here's where it can get tricky: even if it's labeled as `ID`, it might still be the `UUID`. The way to discern this is by comparing its format to the known formats of `UUID` and `ID`. 
If it looks as a UUID, it will always be a UUID in response of this endpoint, and vice versa for ID. 
It's a straightforward rule.

This naming convention can be confusing, but it's in place to maintain backward compatibility with a majority of existing integrations (reporting agents) and custom reporters developed by the community. 
We plan to address this legacy issue in a major update codenamed RPv6.

Now, once you have the `UUID`, you'll need to retrieve the actual ID of the element recorded in the database:

`GET https://{{SERVER}}/api/v1/{{PROJECT}}/item/uuid/{{UUID}}`


the response will be:
```json
{
📍"id": 818514221,
  "uuid": "9b23981f-8120-4baf-a89b-268a4f04898b",
  "name": "[2] TEST",
  "codeRef": "com.epam.rp.tests.testitem.TestItemUpdateIssuesTest.User is able to update an issue's ignoreAnalyzer flag for test item",
  "description": "",
  "type": "STEP",
  "startTime": 1693236244115,
  "endTime": 1693236246149,
  "status": "PASSED",
  "statistics": {
    "executions": {
      "total": 1,
      "passed": 1
    },
    "defects": {}
  },
  "parent": 818514139,
  "pathNames": {
    "launchPathName": {
      "name": "RP Smoke Test",
      "number": 89
    },
    "itemPaths": [
      {
        "id": 818513933,
        "name": "TestItemUpdateIssuesTest"
      },
      {
        "id": 818514139,
        "name": "API.TestItemController.UpdateIssueOfSpecifiedTestItem.ChangeIgnoreAnalyzerFlag"
      }
    ]
  },
  "hasChildren": false,
  "hasStats": true,
  "launchId": 298616,
  "uniqueId": "[engine:junit-jupiter]/[class:com.epam.rp.tests.testitem.TestItemUpdateIssuesTest]/[test-template:User is able to update an issue's ignoreAnalyzer flag for test item(com.epam.rp.enums.ItemTypes)]/[test-template-invocation:#2]",
  "testCaseId": "com.epam.rp.tests.testitem.TestItemUpdateIssuesTest.User is able to update an issue's ignoreAnalyzer flag for test item[TEST]",
  "testCaseHash": -1781032391,
  "patternTemplates": [],
  "path": "818513933.818514139.818514221"
}
```
where `ID` from database is what you need for 
`GET https://{{SERVER}}/api/v1/{{PROJECT}}/item/history?historyDepth=5&type=line&filter.eq.id={{ID}}`
