### ISSUE TITLE
SAML users profile gets project manager role by default

### ISSUE THREAD

**Issue by abalasub-wm** [reportportal/reportportal#2146]
**Describe the bug**
I have enabled SAML Okta login in RP. I see all the users who log in to the application get the account created successfully. This is expected. But the default role getting mapped to those users is project manager. I want to limit the privilege by giving them a member or customer role initially. Do you have any settings to make the default role?

**Expected behavior**
SAML logged in users need to have some low privilege role like customer or member instead of high privilege role like project manager

**Screenshots**
If applicable

**Versions:**
 - OS, Browser
 - Version of RP [find it under Login form, copy as is]

**Comment by MaryiaRymarchyk** [comment]
Hello @abalasub-wm it is expected behavior that each new user in RP gets Project Management role in his **Personal Project.**  The user should has maximum permissions on his Personal project. No any settings for default role exists. 
If the user is assigned to any other project - role could be specified in RP directly during assignment.
