### ISSUE TITLE
Report portal is forcibly closing connections when doing requests to its API

### ISSUE THREAD

**Issue by avd1989** [reportportal/reportportal#2151]
I created a customized integration code between Report Portal and our automation framework which uploads all the reports and screenshots to it. We've been seeing that we get this error randomly:
Currently using build 5.7.3
```
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
```
When calling the /launch/import endpoint of the RP instance. I'd like some guidance on this matter as I am not understanding why would RP do that

**Comment by DzmitryHumianiuk** [comment]
@avd1989 this is made intentionally for the security reasons. And for the stability issues.
Just image that RP instance can serve hundreds of projects at the same time, and receive thousands of RPS.
System should free up unused connections, in order to serve potentially new incoming calls.

Practically, we recommend in such a case to use our SDKs, like https://github.com/reportportal/client-python, or any other client for your language to call required APIs.

We also agree that opening and closing the connections for each interaction might be overwhelming. That's why we are working on new gRPC-based agents (streaming agents), which will keep the connection stream open to avoid all HTTP overhead while sending the data.

**Comment by DzmitryHumianiuk** [comment]
@avd1989 we just release the async version of https://github.com/reportportal/client-python, this might help. Check the latest version please

**Comment by avd1989** [comment]
Perfect, thanks. Will have a look!
