### ISSUE TITLE
Use RP as test repository by combining tests across multiple repos and layers

### ISSUE THREAD

**Issue by Nayana-BM** [reportportal/reportportal#2160]
@DzmitryHumianiuk @evjlobanova 
**What we want to achieve**
We want to push test results across all repos to RP so we get an aggregated view of test coverage for features

**Project Background**
1. We have 20+ repos(scala, golang, python, JS) which has tests across layers (unit, integration, functional-api/ui)
2. We push test results coming from dev repo to internal GoCd tool
3. We push functional test results to RP. We use test level attributes as feature tags. We further have dashboard widgets which groups the test results based on feature tags.

**Problem and options explored**
1. We have ways to push test results from each repo as individual launches with necessary attributes as feature tags. However, we don't see an option for following,
a. Option to create a filter that can combine latest launches from all unique launch names
b. Option to use multiple filters on the dashboard widget to show results based on attributes

2. We explored generating xml report across all repos, so that these can be combined and pushed as single launch. But seems like there is a limitation to use test attributes in xml format

3. W are exploring merge launches option currently. Need to validate if this works for us

Do you suggest any option that we could use with existing RP features for our usecase ?

**Comment by DzmitryHumianiuk** [comment]
Hi @Nayana-BM,

Thanks for the insightful questions. Let me address them in detail:

**1.a.** Several of our widgets support the `All launches / Latest launches` toggle. In `Latest launches` mode, the system will pull only the most recent executions of each unique launch name that appears in the filter results. Off the top of my head, I know that the `Cumulative trend chart` consistently operates in the `Latest` mode, while the `Component health checks (both table and tile)` can switch between the `Latest launches` and `All launches` modes. Given that you're primarily looking to differentiate test results by attributes at the test level, the `Component health checks (table view)` seems like your best bet.
![image](https://github.com/reportportal/reportportal/assets/11332788/f977471e-5cfa-4d17-bd67-97f9d69ea94a)

**1.b.** I need a bit more clarification here. Are you suggesting the need to select multiple filters for a single widget and then divide all their tests by attributes? This would be a complex query for our database. Our system is built on the foundational filtering capabilities of our database and the query builders on top of them. Filtering with two distinct parameters complicates the backend code significantly. Perhaps you might consider using a more intricate singular filter that encompasses all the needed launches? For instance, creating a unique attribute at the launch level and only including that. Could you provide an example where you need two filters simultaneously and explain their criteria?

**2.** Indeed, we currently have restrictions on the data that our import function can handle. There are two main reasons for this: 
- 1. We adhere to the conventional XML report standard of the jUnit format, which doesn't accommodate extra information such as attributes (or perhaps we're behind on the latest updates). 
- 2. Our primary focus remains on real-time integrations because of their flexibility and broader capabilities.
Therefore, we haven't prioritized enhancing our import functions.

**However, we'd gladly welcome your Pull Requests to improve the import feature, and we can release them with the next version.**

**3.** Merging launches might be the best current solution. However, this largely depends on the volume of each launch. I recall we had some constraints related to the volume of test cases in launches, and we made a fix for that issue. A comprehensive overhaul of the merge functionality has been postponed until after transitioning to a flat structure.

Overall, we'd love to hear more about your specific use case concerning the need for two or more filters for a widget. It's possible that this issue could be addressed by simply adding additional attributes at the launch level.

**Comment by DzmitryHumianiuk** [comment]
@Nayana-BM did it help?

**Comment by Nayana-BM** [comment]
Hi @DzmitryHumianiuk 

Yes, your suggestion on 1(a) helped us. We only had to tweak the attributes we used and the launch names to help our usecase.

Thank you
