### ISSUE TITLE
Doesn't work resources because of the reportportal

### ISSUE THREAD

**Issue by Flegmatik89** [reportportal/reportportal#2161]
Hi, I have a question about configuration reportportal, because my resources doesn't work.
I have a project for testing (for example projectDad). In the project added another project (for example projectSun) which has 4 folders: bin, libs, resources and runtime. And also I added reportportal. 
I started tests in projectDad. He started projectSun. projectSun for starting updating need resources folder. But reportportal blocked it and projectSun can't access to resources folder.
And my question: how does configure reportportal so that it all work?

Reportportal configured as describe in https://github.com/reportportal/agent-java-junit5 and I used maven.
Register ReportPortal extension through service location.
configuration - https://prnt.sc/AmtVtgipMtkj

**Comment by HardNorth** [comment]
@Flegmatik89 We don't block resources folder, we event don't read anything from it. Are you sure this behavior is related to us?

**Comment by Flegmatik89** [comment]
Yes, when I turn off reportportal <rp.enable>false</rp.enable> in pom file I see that projectSun starting updating

**Comment by Flegmatik89** [comment]
Thanks a lot, it works.

**Comment by HardNorth** [comment]
@Flegmatik89 I didn't hear anyone else has such troubles, so this is related to some kind of you system or configuration specifics. Since this option is ON for everyone by default and if it was an implementation issue we would sink in GitHub issues. But for future if you would need multi-process client join you can use `rp.client.join.mode= SOCKET` along with `rp.client.join=true` this does not involve volume reading/writing.

Case closed.
