### ISSUE TITLE
Implement dashboards pagination and allow more than 300 dashboards per project

### ISSUE THREAD

**Issue by glibas** [reportportal/reportportal#2168]
**Describe the solution you'd like**

We are using ReportPortal extensively and recently upgraded from version 5.6.0 to version 5.9.0 and hit an issue with number of dashboards we can create per project. It looks like only 300 are allowed (here is a comment describing when the limit was introduced https://github.com/reportportal/reportportal/issues/1790#issuecomment-1333691059), however we would like to have more for audit and historical reference.

Are there any plans to increase the number of allowed dashboards? 

Is it possible to tweak the configuration to allow more on our installation?

**Comment by Kozovskaya** [comment]
Hi @glibas, I'll discuss it with the team and will revert to you soon!

**Comment by DzmitryHumianiuk** [comment]
Hey @glibas, could you walk me through the situation where you're needing to manage over 300 dashboards?

I've got a simple breakdown for you on how to recycle dashboards by updating filters through API calls. 
Check it out here: https://github.com/reportportal/reportportal/issues/1790#issuecomment-1325867704

With this method, you might be able to cut down the total number of dashboards you need.

Let me know if this solution fits your needs and if everything's clear.



</p>
</details>

**Comment by glibas** [comment]
Hi @DzmitryHumianiuk ,

Apologies for taking long to get back to you on this one. 

One of use cases is as follows (there are more in different departments as the workflow slightly differs from team to team):

We run nightly regression tests for microservices. Test execution is grouped by the owner team which owns microservice, e.g. 1000 microservices are owned by 20 teams.
After every test execution we generate a dashboard for that execution, so that we'll have 20 dashboards specific to each team and 1 overall dashboard summarizing all executions across all teams.
Additionally the data is extracted from the filters used by the dashboards and used to create a custom email report with the reference to the dashboards.

So in the end of execution we've got 21 dashboards created (based on 21 filters) and 20 emails sent (one per team) summarizing execution statistics and referencing the dashboard which should be used for investigation.

Currently we are limited to around 15 days of historical data, considering 300 dashboards per project limit. Not taking into account custom static dashboards created by users into same project.

We'd like, however, to be able to store at least 3 months worth of historical results for audit and compliance purposes. 

As a temporary workaround we've implemented automated dashboards cleanup mechanism which is running on trigger daily removing old dashboards so we can create new ones during tests execution.

We'd appreciate any help or advice on how to raise the current limit.

**Comment by DzmitryHumianiuk** [comment]
Hey @glibas,

Thanks for the detailed explanation of your workflow. It really helps to understand the context.

Just to clarify, are you currently preserving the data snapshot for each day specifically through these dashboards? 
Because if we look at reusing the same dashboard through filter updates, it seems there's a possibility to always have a fixed dashboard for the latest build. But latest only.

However, I get what you're trying to achieve. In this case, the quickest solution indeed seems to be increasing the dashboard limit. Like a Quick Fix.

But something else I'd like to understand is how to use the current widgets to give you a broader historical view. One idea that immediately comes to mind, something we've been thinking about for a while, is a sort of `release sign-off` function. It would create a fixed snapshot of results for storage, almost like a PDF report. We thought of possibly offloading it to a separate data table, maybe with reduced data volumes – not storing all logs, just statistics, test names with their statuses, and comments on failure reasons, to avoid it becoming a copy of the launches themselves.

This feature, though, would require some work and definitely isn't a quick fix.

In the meantime, could you share what one of your dashboards looks like and the kind of information you display on it? This could give us more insight into how to best accommodate your needs.

Thanks!

**Comment by DzmitryHumianiuk** [comment]
the same: https://github.com/reportportal/reportportal/issues/1790

**Comment by glibas** [comment]
Hi @DzmitryHumianiuk 
Happy new year and sorry for the slow reply but I'm sure you know how these things go at this time of year.

The quickest temporary solution will work for us. 

Indeed we could have updated filters to reuse same dashboard but that doesn't give us easy access to historical execution summary which we can get by preserving the dashboard for daily executions.

Below are couple use cases (there are more across organization, since different departments have different workflows but all will benefit from the higher dashboards limit):

1. As already described we have a dashboard for every regression (and release sign off) executions, summarizing stats across all microservices included into regression/release sign off testing:
![image](https://github.com/reportportal/reportportal/assets/16775850/f47fb436-6f62-4edf-84ee-c1410ad0d9bb)
2. Each project is an owner of hundreds of microservices, each microservice has CI job which executes UI/API regression tests.
So we have a separate dashboard for each microservice to track it's metrics. e.g. tests duration, success rate, flakiness.
For example in one of the projects we have around 300 microservices, each of them has a separate job for UI and API tests, so if we generate (which we would like to do) a dashboard for each of them we need to have 600 dashboards only for that not counting regression execution. 
![image](https://github.com/reportportal/reportportal/assets/16775850/878e9110-6db1-4db2-922e-13bede341e99)

Thanks,
Glib

**Comment by Kozovskaya** [comment]
Hello @glibas 
The ReportPortal version 24.2 is already released! The improvement is there!
I'm closing the issue.
Thank you for using ReportPortal!
