### ISSUE TITLE
rabbitmq Disk full

### ISSUE THREAD

**Issue by babantax** [reportportal/reportportal#2208]
rabbitmq PVC gets full and rabbit start to deny connections.
I think is happening since we updated rabbitmq from 10.3.5 to 10.3.9.

![image](https://github.com/reportportal/reportportal/assets/52815118/72f3fda3-938c-428d-ba87-f886466a0451)

**Comment by Pink-Bumblebee** [comment]
@babantax , could you please explain your issue and screenshot more detailly?? 
Please provide version of RP.
Also, as I see in kubernetes helm chart file in GitHub, bitnami/RabbitMQ version was changed to 10.3.9 in February, 2023. It was 2 releases ago.

**Comment by babantax** [comment]
Yea, I have Version 23.2 (5.10).
I have now RabbitMQ 10.3.9.
So problem seems like data grow slowly but in some weeks it reaches 16GB
![image](https://github.com/reportportal/reportportal/assets/52815118/1132507c-0399-44e2-a5b4-1ab5d91ebde5)

**Comment by irynakozak2** [comment]
@babantax Hi, seems like the issue is with the messages in the dead-letter queue, which is not cleaned up by default, so if you have any it needs to be manually cleaned.

Could you please connect to the rabbitmq management UI and show the actual status of the reportportal.dlq?
<img width="1425" alt="image" src="https://github.com/reportportal/reportportal/assets/51473435/9f97da9f-7452-4cba-b814-33d4a91c4beb">

**Comment by babantax** [comment]
Sure
![image](https://github.com/reportportal/reportportal/assets/52815118/34f10fd3-e77c-43fa-bd5c-53cfc2447d32)
Should I use purge option?
![image](https://github.com/reportportal/reportportal/assets/52815118/70a722fd-4847-408f-8157-3cdf737c4344)

**Comment by irynakozak2** [comment]
Thank you! Yes, you can, but the total storage used for those dead messages is quite small and not correlated to 1 GB. What about your other queues?

**Comment by babantax** [comment]
Not sure, I see many idle and a few running
![image](https://github.com/reportportal/reportportal/assets/52815118/e179bfd6-d888-4c9c-8594-1c8d6764f1ae)

**Comment by babantax** [comment]
And I see this in the logs
![image](https://github.com/reportportal/reportportal/assets/52815118/00c34f9a-47ff-4811-869a-0e6bec268d14)

**Comment by irynakozak2** [comment]
Could you please verify if are there bindings on the queues? Like the following:

<img width="922" alt="image" src="https://github.com/reportportal/reportportal/assets/51473435/72fa8a2d-b8b3-487d-9e52-f3472d5e00f5">

I assume that the issue is somewhere in the configuration/deployment as fas as the messages are not consuming from the queues.

**Comment by babantax** [comment]
Hi I rolled back rabbitmq chart version to 10.3.5 a couple of days ago and problem is not happening.
No sure what could be the source problem

**Comment by irynakozak2** [comment]
Hi @babantax, thank you for the update. We haven't found the issue with the RabbitMQ on the 3.12.2 version. But we will keep this information in further development and notify you in case of any valuable findings.
