### ISSUE TITLE
[AA:: boost human priority] When fail was investigated during run differently from previous runs the Auto Analysis will change it to previous runs' investigation result

### ISSUE THREAD

**Issue by andrey-patin-1979** [reportportal/reportportal#227]
Scenario:

1. Run1 has Fail1 with investigation result "Product bug" and bug attached to it.
1. Run2 is performing and already has Fail1 which was identified as "Auto bug" **manually** (SUT's behavior was changed prior to Run1) but has same log (only attached screenshot is different).

Result: upon end of Run2 Auto Analysis (AA) will change investigation result to one from Run1, but expected to leave it as is since it was manually investigated before AA.

**Comment by evjlobanova** [comment]
Hi! Now we are working on improving the function of auto-analysis so the problem will be solved.

**Comment by DzmitryHumianiuk** [comment]
With new AA, based on ML, it will be covered with:

1. For defects, which submitted by human/manually, priority will be increased during AA
2. And according to new algorithm, list of item for analysis will be created only after Launch Finish received. In current versions (before 4.0), list was populated in run-time with launch. That's why, defect typed. assigned to testItem was ignored, based of already created list for analysis.


Action Item:
- add flag on AA/Human analysis
- create priority boost for Human flag in Bool query

**Comment by pbortnik** [comment]
Added flag 'autoAnalyzed'. Priority of defects with 'autoAnalyzed=false' is 2x boosted.
