### ISSUE TITLE
Launchers not detected when ReportPortal is on a different host. Working on localhost

### ISSUE THREAD

**Issue by zephirus** [reportportal/reportportal#2304]
I'm running the exact same Cucumber project code on both scenarios:

1. Reportportal running on localhost: http://localhost:8080
2. Reportportal running on another machine: http:myIpAddress:8080

The launches are collected only for localhost, not for the reportportal on a different machine.

I don't have any clue of why this happens.

What can it be and how can I debug this in the logs?

**Comment by alena-babrova** [comment]
Hello @zephirus,

I'm afraid it's not ReportPortal issue as long as it works for localhost. It seems to be your network configuration issue because ReportPortal cannot access a machine outside your local system. 
Please, make sure you've configured everything correctly and the machine you are trying to connect is available from within your localhost.

**Comment by zephirus** [comment]
It was in fact something related with the machine (that is on the same network). For any reason that I can't understand, it stopped working. Tried with others and is working fine.

**Comment by zephirus** [comment]
Not ReportPortal issue.
