### ISSUE TITLE
[Question] Planned curl/libcurl vulnerability patch and 24.2 Release date

### ISSUE THREAD

**Issue by IgoDan** [reportportal/reportportal#2349]
Hi guys.

As a matter of fact, we in our organisation are looking forward to the next full release because of planned vulnerability patching. It is crucial for us to have newer curl and libcurl packages (version >=8.4.0) in your docker images, in order to prevent the popular CVE-2023-38545 vulnerability.

Beacuse of that I wanted to ask if Release 24.2 is coming anytime soon? And also, will it cover the changes mentioned earlier?

Truth is, that we are tight on time and need to take special action if it turns out that the release won't be coming before the end of october (or it won't contain the curl/libcurl update).

I am looking forward to your answer.
Thank you in advance!

**Comment by Pink-Bumblebee** [comment]
Hello @IgoDan , 
We expect that this issue will go away in the upcoming 24.2 release in 3rd decade of October.

**Comment by APiankouski** [comment]
We don't see this vulnerability on our scans. I guess it disappeared after the update to the latest amazoncorretto image, along with many others. 24.2 will be anonced soon, within a few days.

**Comment by IgoDan** [comment]
Great, thanks for your insight. Looking foward to the news in the near future.

**Comment by IgoDan** [comment]
Hey again,
After updating to latest R24.2 images I still notice the CVE-2023-38545 vulnerability in almost all of the ReportPortal containers. For example: 
- Image service-api still has vulnerable curl/libcurl 8.3.0 version
- In image service-authorization, curl/libcurl has been updated from version 8.2.1 to 8.3.0, which is still <=8.4.0 according to the vulnerability
- The service-api image is the only one free of the vulnerability - with curl/libcurl version 8.9.1 (probably thanks to using an alpine base image)

After a bit of searching, I am not sure if updating this curl/libcurl version in your images is a change you are willing to make in a near future. It would involve package version changes in almost all out of your services' images (+ possibly switching to different rabbitmq version). It seems to me, that your scans are not picking up this vulnerability correctly.
But considering you have added this issue to your 24.2 milestone, I am hoping those changes will take place. May I ask then, if there is any planned date in the near future or at least plans to address the issue?

It is very important for me to get more insight into your plans. This critical vulnerability is unfortunately the reason I may need to stop using ReportPortal as a test analytics platform in the future.

Thank you in advance!

**Comment by drcrazy** [comment]
Hello IgoDan, 

check for curl version alone works fine only for LFS-like setup. 

Usually flavor (Ubuntu, RH, AmazonLinux) vendors are patching binaries to fix vulnerabilities within same version. For example (all versions are not real), if curl was 8.2 in ubuntu 22.04 it might stay 8.2 in ubuntu 22.04 until EOL but security fixes will be applied by Canonical in order to fix CVEs.

Service-api is built on top of Amazon Coretto image. Either Docker hub scanner is not picking up this vulnerability correctly or Amazon applied fix for that issue without bumping minor version of curl. 

Here is a link for service-api base image on Docker hub: https://hub.docker.com/layers/library/amazoncorretto/21.0.4/images/sha256-bb0582ecfcdc1da2b2b5eb0c1597025c00dcb6d17b54acc59798d111ea331cd9?context=explore

0 (zero) vulnerabilities.
