### ISSUE TITLE
Running microservices on different hosts

### ISSUE THREAD

**Issue by kshcherban** [reportportal/reportportal#241]
Hello,

I have an issue while trying to run updated reportportal inside AWS ECS. Before you introduced consul it worked in docker network **bridge** setup but now it stopped.

I switched to host network, tried to bind all services different ports, but seems that not all microservices support port overrides.

Current version: Service Index: 3.1.1; Authorization Service: 3.2.1; Service UI: 3.2.4;

Here's an error that I get from api when i try to login to ui
```
2017-09-28 09:57:28.118  WARN 1 --- [nio-8080-exec-4] o.s.b.a.s.o.r.UserInfoTokenServices      : Could not fetch user details: class java.lang.IllegalStateException, No instances available for localhost
```
UI says that login is correct but Api returns 401 and no redirect occurs. How can i debug that?

Please advise will you support running your services not with docker compose but in other way?

**Comment by avarabyeu** [comment]
@kshcherban What service do you have problem with? For java-based services it should be`SERVER_PORT`

**Comment by kshcherban** [comment]
Yeah, i already figured it out and managed it to work but documentation misses lots of things. For example you have hardcoded redis and consul (registry) addresses and ports in your java services, you also hardcoded uat address in api config (https://github.com/reportportal/service-api/blob/develop/src/main/resources/application.properties#L4 https://github.com/reportportal/service-api/blob/develop/src/main/resources/application-docker.yaml#L18). Probably there's a way to change that but it's not documented.

`RP_SERVER.PORT` environment variable is not documented, i guess it's port setting for golang apps.

It would be great if you improve documentation about installation and configuration and support your microservices architecture to work on different servers and not only with docker compose. For example AWS ECS doesn't support docker links in both directions, so if you link all services to consul (registry), they are able to resolve consul with internal hostname, like registry but not vice versa.
```
2017/09/27 16:14:57 [WARN] agent: http request fai
led 'http://a35543ba5467:8080/health': Get http://a35543ba5467:8080/health: dial tcp: lookup a35543ba5467 on 172.16.64.2:53: no such host
```
Here you can see that service was registered with it's docker hostname that's not resolvable from another container, however they run on the same instance in bridge mode.

**Comment by avarabyeu** [comment]
hi @kshcherban . Thank you for pointing this our. Actually, all properties that you can find in application.properties/yml can be overriden via env variables. For mentioned property, it will be
`RP_UAT_SERVICE_URL`
Unfortunately, we are not able to describe all configuration properties in the documentation. Since java-based apps are based on spring-boot, there is number of spring-related properties: 
https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

Plus, we have our properties which override spring's ones. So, we tried to cover in docs the most widely used ones. But anyway, thank you for the feedback. Feel free to PR to documentation repository if you see that smth might be improved.
