### ISSUE TITLE
Do we have any plan to integrate with Jmeter load or perf test reports with report portal

### ISSUE THREAD

**Issue by learnappium** [reportportal/reportportal#244]
Is there any way to integrate jmeter  load test report with reportportal.
or any way  to convert Jmeter load test report in junit report and send to peport portal.

**Comment by kirlionik** [comment]
> Is there any way to integrate jmeter load test report with reportportal.
Right now - no. But Report Portal Team has already thought about implementation of this feature.

>any way to convert Jmeter load test report in junit report and send to peport portal.
It depends on what data you want to see in RP

**Comment by learnappium** [comment]
Thanks @kirlionik   i am looking forward for jmeter and Secure pro integration

**Comment by adityakap** [comment]
Has there been any change on this since Oct 2017?

**Comment by aquadrehz** [comment]
I'm still looking forward for this too.
Is there any road map or request for implementation?
Maybe we can discuss.

**Comment by yhthahira** [comment]
Please let us know on the current status of integrating JMeter and Report Portal

**Comment by sspieker-cc** [comment]
I have just entered another feature request for this type of integration.  Any information being supplied to RP will be better than no data at all.

The load test type of test plan is a form of gathering metrics.  There is also other uses for JMeter such as API testing and combined behaviors that may be executing HTTP requests for gathering data.

It seems that the current limitation with using JMeter is that there are no easily implemented / defined events to link a listener or getting logger linkage.

**Comment by DzmitryHumianiuk** [comment]
integrations with JMeter Perf thru 
https://github.com/carrier-io/carrier-io/wiki/Performance-Testing.-PerfMeter-%28jMeter%29

**Comment by sspieker-cc** [comment]
This PerfMeter solution is convoluted and complicated to make work and conversely it will only report test failures.  When a JMeter testplan is executed without error, there is a report to report portal however, there are NO details such as number of test cases and so forth.

Having an agent/listener that would monitor the test plan that would allow for reporting using the Log4j appender would be ideal!  Simply adding the appender to the configuration is never executed (unless I am doing something wrong here).

Is the logger all that should be needed (along with the client-java and commons jars) in order to get reporting implemented in a 'cheap' way?
