### ISSUE TITLE
Move test event (launch, suite, test) duration to separate column

### ISSUE THREAD

**Issue by sporitskiy** [reportportal/reportportal#263]
Now:
![1](https://user-images.githubusercontent.com/15995047/32332010-7133757e-bff5-11e7-8059-e611d40b07bc.jpg)

Suggested:
![2](https://user-images.githubusercontent.com/15995047/32332592-f09ede7e-bff6-11e7-80eb-95ce2c601272.jpg)

I am sure many people need to sort test suites (or launches or separate tests) by duration to see possible gaps in performance and for estimating optimizations of long regression.

**Comment by evjlobanova** [comment]
hi! we have already had a similar request, please check issue #93 . We plan to close this features by two ways: 
1. We will implement a `Sub launch view` (description of the feature is here #259 ). `Most time-consuming tests` widgets  on a Sub launch view will show the most time-consuming tests of the launch (TOP-20). Therefore you can look through a list quickly. Planing date of implementation is a spring of 2018 . 
2.  Technically, adding a duration filter is a painful change, because duration is not stored in DB (all items have only `start_time` and `finish_time`, and duration calculates on the fly). Maybe if we decide to move to PosrgeSQL, we will have a possibility to consider about adding a filter by duration. But now it is a pretty hard to do this.

Do issues #93 and #259 cover your need?
