### ISSUE TITLE
Does ReportPortal send something to your servers?

### ISSUE THREAD

**Issue by Tset-Noitamotua** [reportportal/reportportal#27]
Not sure if you noticed my [additional question in closed issue](https://github.com/reportportal/agent-Python-RobotFramework/issues/1#issuecomment-265092347) so I repost it as separat issue here.

> @DzmitryHumianiuk
I have taken a closer look at documentation and also watched your presantations on youtube. Quite on question remains: When I set it up - will it run fully (100%) on my system (my infrastructure) or will it send results to your servers for analysys?

**Comment by avarabyeu** [comment]
Hi @Tset-Noitamotua! No, portal doesn't send anything to us. It's sad actually, because we would like to collect some usage info, but it's still not implemented and even not planned for implementation :) 

Regarding external connections to outside world, I can highlight the following ones:
1.       Connection to SMTP servers. 
2.       Authentication via GitHUB OAuth – goes to Github’s ouath server to obtain user token and user info.

**Comment by Tset-Noitamotua** [comment]
Thank you!
