### ISSUE TITLE
[FR] Add ability to export user list in CSV from admin management board

### ISSUE THREAD

**Issue by talgreen1** [reportportal/reportportal#284]
Add ability to send emails from the report portal to all the users:

- Admin will be able to send emails to all registered users. For example: Announce new feature, usage tips & conventions

- Project manager will be able to send emails to all the project users. For example: Project's conventions

**Comment by evjlobanova** [comment]
@talgreen1 please, can you describe more wide your need? Why you want to have an ability to send emails directly via report portal?

**Comment by talgreen1** [comment]
Hi,
Sure - for example - we (admins) want to announce new feature of report portal to all our report portals users, or send them some usage tips.It would be nice if this could be done directly from the report portal because we do not have record and emails of all the users.
    On Tuesday, December 5, 2017, 5:11:33 PM GMT+2, evjlobanova <notifications@github.com> wrote:  
 
 
@talgreen1 please, can you describe more wide your need? Why you want to have an ability to send emails directly via report portal?

**Comment by evjlobanova** [comment]
@talgreen1 and also could you please describe how you solve this issue now?

**Comment by DzmitryHumianiuk** [comment]
ReportPortal not a messaging system.

But, we have the same need.
Currently we do we same, but via direct request to Database.

As a part of **Management Board** update (available for admins only), will be added possibility to filter users, and export these results into XLS file.

For example, filter users which logged in no more then 3 months, and email contains `@mail.com`.
After it -> Export as XLS.


This will be the most powerful way to handle emailing,
Since for proper mail creation, you need an Editor in RP, which will support HTML emails and so on.

It's much better to use Excel-Word Mailing functionality.


RESOLUTION:
move to Management Board requests.
close current issue

**Comment by talgreen1** [comment]
Excellent idea. 
How about exporting to CSV instead? It's less depended and you still can open it in Excel.

**Comment by DzmitryHumianiuk** [comment]
@talgreen1 will be done within **Management Board** update.
I also missing this functionality.

Agree with you, it's better to make it in CSV

**Comment by DzmitryHumianiuk** [comment]
@talgreen1 done.
available in ALL USERS section of admin board.
filter and export list of users to CSV format with emails in it.
