### ISSUE TITLE
Question about usage of GPL-licensed clients/agents for running tests

### ISSUE THREAD

**Issue by abotalov** [reportportal/reportportal#293]
Most of Report Portal's clients / agents are licensed under GPLv3 (not LGPL).

I read a bit about this license, and it looks like this license disallows a case where a GPL-licensed library and proprietary code are parts of the same program.

From https://www.gnu.org/licenses/gpl-faq.en.html#GPLInProprietarySystem
> However, in many cases you can distribute the GPL-covered software alongside your proprietary system. To do this validly, you must make sure that the free and nonfree programs communicate at arms length, that they are not combined in a way that would make them effectively a single program.
> The difference between this and “incorporating” the GPL-covered software is partly a matter of substance and partly form. The substantive part is this: if the two programs are combined so that they become effectively two parts of one program, then you can't treat them as two separate programs. So the GPL has to cover the whole thing.

There are many posts that tell that using / linking to GPL library from proprietary code is not possible:
* https://en.wikipedia.org/wiki/GPL_linking_exception
* https://softwareengineering.stackexchange.com/a/87450/54761
* https://stackoverflow.com/a/999479/841064
* https://www.reddit.com/r/Python/comments/26mo7k/gpl_a_nono_for_python_web_frameworks/
* https://softwareengineering.stackexchange.com/a/37237/54761
* https://opensource.stackexchange.com/a/415
* https://en.wikipedia.org/wiki/GNU_General_Public_License#Linking_and_derived_works

Here are some of clients / agents that look to have GPL license:
* https://github.com/reportportal/agent-python-pytest
* https://github.com/reportportal/agent-Python-RobotFramework
* https://github.com/reportportal/agent-java-cucumber
* https://github.com/reportportal/agent-net-nunit
* https://github.com/reportportal/agent-js-jasmine
* https://github.com/reportportal/client-java
etc.

I'd like to ask about the point of view about this.

**Comment by DzmitryHumianiuk** [comment]
@abotalov, good question,
There is a very large number of interpretations, as well as what should be done in this case.
Most of them refer to the understanding of derivatives and derivational refinement.

That's true that GPLv3 is a `virus` license. It means, that everything what is done based on GPL code, should be licensed under GPL as well. 
But it case if you want to publish it. If you don't then there is no need.

There are two cases, when you should publish it:
- if you took gpl code, made changes, and passed it to the 3rd part. Then you should.
- if you took gpl code, made changes, and sell product on top of this, Then you should.

So you if you took code `as-is`  you don't need to worry.

## But in order to avoid the duality of the interpretations we will re-license all agents and integrations under **Apache 2.0 license.**

**Comment by schoi1** [comment]
I would like to re-open this issue as I am waiting for .NET agents (especially agent-net-specflow) to be changed to Apache 2.0 license. I can see that only **agent-java** has been changed, but not other agents.

Our company does not accept GPL licenses and it is crucial for us to know when other agents will be changed to Apache 2.0 license. Otherwise, we have to look at alternatives.
