### ISSUE TITLE
Integration with SauceLabs

### ISSUE THREAD

**Issue by avdynut** [reportportal/reportportal#348]
Hello all,
It would be nice to see test execution results from SauceLabs on tab ATTACHMENTS. Or in some other way.
For example, [embed script](https://wiki.saucelabs.com/display/DOCS/Embedding+Test+Results+in+HTML+Pages).
Now we us this approach: Add to logs line with direct link to test result
`http://saucelabs.com/jobs/{WebdriverSessionId}`

**Comment by DzmitryHumianiuk** [comment]
considered for workshop

**Comment by evjlobanova** [comment]
## Description
**As a User** I watch [Sauce Labs|https://saucelabs.com/] video of test execution on the test log view.
 **So that** I can quickly find the test failure  without reading RP logs.
 **For that** I should:
 1. Configure integration with Sauce Labs (project) by filling fields: User name (text field), Asses token (text field)
 2. Run Tests with attributes:  SLID:XXXX  (where key is "SLID" and value is # of the job in Sauce Labs ) and  SLDC : EU (EU or US) 
 3. Find items which have Sauce Labs label on the  Step view
 4. Watch video on the log view and commands on the log view.

![image](https://user-images.githubusercontent.com/30413511/61866884-b25e2d80-aede-11e9-8c31-6789b0a9091b.png)
![image](https://user-images.githubusercontent.com/30413511/61866924-c3a73a00-aede-11e9-962e-59e0a3538402.png)
![image](https://user-images.githubusercontent.com/30413511/61866950-cf92fc00-aede-11e9-88bc-457e67e8fac3.png)
![image](https://user-images.githubusercontent.com/30413511/61866961-d6217380-aede-11e9-9365-27238cf48728.png)

**Comment by evjlobanova** [comment]
@AmsterGet Ilya, could you please check if we can send session_ID via WebDriver?
