### ISSUE TITLE
RP3: AA doesnt work when runs were merged to one.

### ISSUE THREAD

**Issue by KursLabIgor** [reportportal/reportportal#350]
We have encountered that 5 different run merged to one and at least one of them has issue from previous run , but it doesn't populate automatically. One test has history from 12 launch, i suppose in next run with the same fail reason it should automatically set fail reason. 
Run merges via API call.
could be problem due such scenario with AA?

**Comment by evjlobanova** [comment]
@KursLabIgor could you please clarify the your case? You have 1 launch which has been already analyzed and 4 launches which have all failed tests with defect type  "To investigate".  Then you merge them. And after that you try to auto-analyzed them but there is no results, am I right?

**Comment by KursLabIgor** [comment]
@evjlobanova  we have list of merged runs ~12. which already has investigated issue.  When i start automation it produce for me several runs simultaneously after they all finished all runs merged to one. i assume that AA will start analyze them. But no. now clear?

**Comment by evjlobanova** [comment]
@KursLabIgor what your RP version is?

**Comment by KursLabIgor** [comment]
@evjlobanova  Current version: API Service: 3.3.1; Service Index: 3.1.1; Jira Service: 3.3.0; Authorization Service: 3.3.0; Service UI: 3.3.2;

**Comment by pbortnik** [comment]
@KursLabIgor 
hello, it is expected behavior. AA starts only after finish launch. If you need something like run AA for merged launches you can make another api request after merge with id of a new launch.

`curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'Authorization: bearer $YOUR_TOKEN' 'https://rp.epam.com/api/v1/$YOUR_PROJECT/launch/$LAUNCH_ID/analyze'`
