### ISSUE TITLE
Add custom defect types to "To Investigate" group

### ISSUE THREAD

**Issue by Rider1982** [reportportal/reportportal#41]
Needed for mark not analysed failures as currently investigating by team member to avoid duplicating of investigation or extra communication in team.

**Comment by DzmitryHumianiuk** [comment]
@Rider1982 we will discuss it within next workshop with the team.
Sounds reasonable.

@avarabyeu what do you think?
it's kind of idea crossing with `Assign for investigation`, but here you can mark it at `Under investigation` or `Under review`.

but here also start another issue: should this `under review` status assigned automatically as user open up the test case, and changed back into `To Investigate` when closed and no changes made?
or this should be handled by user only.

**Comment by Rider1982** [comment]
Custom subtypes looks more comfortable for me. They allow me for example to classify fail's investigation team and approach ("investigating by autotest team", "investigating by R'n'D team", "analyzing by customer", "to discuss on daily meeting" and so on).

**Comment by DzmitryHumianiuk** [comment]
@Rider1982 thank you for details.

The issue we face with this change: represent it later on different widgets.
Currently `To Investigate` state assumed that no one touched it, and this used in formulas of various widgets.
This leads to cascade updates of all dependent objects.

**Comment by andrey-patin-1979** [comment]
It can be used to show progress of investigation but really not a feature which helps a lot

**Comment by ailjushkin** [comment]
I think, giving a type to an investigation like `taken`/`not taken` has common sence. But:
That does not automate completely investifation process of a team: it is still required to do an action manually to take issue/mark it somehow. I don't see a lot profit of that feature. The same efficiency in my honest opinion could be achieved just by assigning users to a certain suites to process.

**Comment by ailjushkin** [comment]
For instance, you could output username which is currently watching certain log of a test.

**Comment by citestusers** [comment]
Hello, for us it would be a real big help, to be able to preserve any comment under any type of issue.
For "To investigate"particularly I don't see why should be there a new status like taken/not taken, this will be a manual work every time to investigate an issue for the first time, and a reason for why is it left in to investigate is also mandatory to be added into a comment under the "To investigate" item in my opinion in this case, if somebody had looked at a to investigate item and could not decide for a correct status because of dependencies (like environment issues, platform upgrades, etc).

This would indicate, that there is still necessary manual work on that test failure, and that way we also wouldn't need to "spam" our Jira, other BTS with tasks, to "follow up this failure/investigate that one", until we couldn't decide what kind of issue is that, but would be self-contained on RP with a simple workflow, and there wouldn't be any extra steps to handle issues under investigation.

From my opinion(without any insight of how RP works), if this AUTO_SYSTEM recognized and automatically copied comments, from every other type of statuses, I wouldn't see a major obstacle to make it work for an additional status.

Thank you in advance.

**Comment by ailjushkin** [comment]
Last time I down voted this issue but facing with real usage of RP we found that this thing is vitally important.

So I propose this use case:
0. Manager does not want to use excel or anything like that, he wants a tool for investigation planning.
1. Manager starts planning next work for next several days.
2. He opens 'to investigate' filter
3. He add additional filter like `name` contains 'blabla1'
4. He makes multiple selection of all cases and changes it types from `to investigate` to `to investigate > username1`
5. He changes a filter and updating new portion of investigations to a new group called `to investigate > usernameN`

So once user ended up investigation of a certain test, he changes its type from `to investigate > username1` to a `product bug` or `system issue` etc.

And we don't actually care about what user do while status isn't changed.

**Comment by ulmanA** [comment]
suggestion solution: add assignments management, so we will be able to assign project's member to a failure. and every member will have view that show him its assignments. (later notification on new assignments can be added.)

**Comment by DzmitryHumianiuk** [comment]
@Rider1982 done for 5.0 already :)

![image](https://user-images.githubusercontent.com/11332788/47105326-457d7f00-d24c-11e8-95f4-29e3be808711.png)

number of sub-types also increased to 15

**Comment by DzmitryHumianiuk** [comment]
## Resolution: implemented
