### ISSUE TITLE
Implenent any way to display error message in test items lists

### ISSUE THREAD

**Issue by Rider1982** [reportportal/reportportal#42]
It is a good idea to see test error message in list of executed test items. Now the only way is put error message to description. Possible implementations: new log item type (displayed message) or possibility to show the first log item in list.

**Comment by DzmitryHumianiuk** [comment]
hm.....
many many many version ago, we tried to made it.
Additional column in test-cases table, which showed first error log.

but later it was reduced, since took to many space to be readable and had no much real usage.

looks like you use something already for reports, @Rider1982, could you please show a screenshot, where this looks valuable?

**Comment by Rider1982** [comment]
Ok, here I see several fails and their error messages and it looks fine for me:
![image](https://cloud.githubusercontent.com/assets/14853118/21246124/c728eee8-c337-11e6-8673-146ed326a8a2.png)

**Comment by DzmitryHumianiuk** [comment]
we will discuss it to include into updated design

**Comment by DzmitryHumianiuk** [comment]
@Rider1982 
I guess, we will cover it in other view.
Kind of `test case grouping` view, based on stack trace.

First, it will help to group of similar fails occurs.
Second, it will make stack trace visible at test case level.

**Comment by DzmitryHumianiuk** [comment]
@Rider1982 
please also check #152 
it have description how to add stacktrace automatically into test case description.

grouping by stacktrace will be release as separate widget
