### ISSUE TITLE
[FR] Add filter to inner tags [items] at project level

### ISSUE THREAD

**Issue by vgri** [reportportal/reportportal#433]
It will be very useful to have the ability of filtering by inner tags so we will be able to have one display showing results filtered by launch tags with items tags.
For example, I have results from deployment and results from the test and I want to be able to filter the test results in addition to the regular filters. 
I use build 4.2.0 and update item tags by UI/REST API.

**Comment by evjlobanova** [comment]
@vgri we have the similar request here #74.  Which your main business goal? Could you explain your workflow? What actions you want to perform after you filter test?

**Comment by vgri** [comment]
Hi @evjlobanova, Our main business goal is to have all our testing data in one place without separating it into sub-projects or duplicating launches. We want to use the filters to get the most accurate status for the requested query by reducing noise from unwanted or not relevant test results.
The workflow is simple, after running Jenkins job we import one zip file via REST API to the project. The second step is adding tags and description to launch/test by ID. Not all files in the newly created launch are test results. We would like to tag the relevant items as tests and being able to filter them later on project level.

**Comment by evjlobanova** [comment]
@vgri do you want  to create a filter based on test for one launch? If yes, what your 
further with this filter?

**Comment by evjlobanova** [comment]
@vgri you want to find tests by appropriate tag from All launches?

**Comment by DzmitryHumianiuk** [comment]
@vgri just to give you a clue:
#74 is about the possibility to create and save filter under launch view. Currently all filters can be applied only for launches view (upper level).
#186 practically about the same.

So we decided to add special view, called **sub-launch widgets** #259 
It's kind of dashboard, but related to particular launch name only, and aggregate data from exact launch you have opened, assuming history of this launch for trend building and so on.

Practically, this view will help you to see insights and details, corresponding to particular raw of launches. And this is the place, where you can create a filter for test cases (or testItems), by any criteria, representing it by list of widgets, which pretty equal to currently existing at dashboard view.

So, if you will have 2 launches, with 100 test cases each, where you have 70 test cases tagged as `test` in `launch_x` and 50 test cases tagges with tag `test` and `launch_y` correspondingly, then you can see any kind of statistics widget with number 70 on it, by clicking `launch_x` sub-launch view, and number 50 for `launch_y` accordingly, by clicking on it.
Let's call it **option 1**

@vgri Does this fit your expectations or you looking for option, when at launch view RP will show you numbers as 70 and 50 at launches view, instead of 100 an 100?
Let's call it **option 2**

And **option 3**, then you create a widget, on regular dashboard, which allows you to apply additional filter for a filtered launches, which can filter inner testitem objects in each filtered launch as well?

Which one is yours?

**Comment by vgri** [comment]
@DzmitryHumianiuk, If I understand you correctly option 3 is what we need.

For example, we have two launces:
X, tagged as 'not_only_tests', with 100 tests, 70 of them are tagged as 'this_is_test'.
Y, tagged as 'not_only_tests', with 100 tests, 50 of them are tagged as 'this_is_test'.
The two filters tags 'not_only_tests' + sub_tags 'this_is_test' in the RP project view will return the 120 'this_is_test' as a result.

**Comment by StLuke** [comment]
Hi, any update on this?  @evjlobanova

**Comment by evjlobanova** [comment]
@StLuke hello! now our team are working on moving to React and PostgreSQL, approximate date for the migration is the end of 2018 year. After it we are have plans to implement sub-launch view for launch, and after gradually add widgets based on tags. So it is difficult to say exact date.

About inner filters we are in the middle of discussion how to implement this and how to reflect it on UI. There is no final decisions for that.

**Comment by StLuke** [comment]
Thanks for the info @evjlobanova . Sounds really promising.

**Comment by itzikb-redhat** [comment]
@DzmitryHumianiuk Hi, Is there an update regarding this issue?

**Comment by DzmitryHumianiuk** [comment]
Planned for v6
ETA Q3-Q4 2020

**Comment by evjlobanova** [comment]
As a possible solution you can try Component Health Check widget.

This widget shows the passing rate of the application components which are indicated by the specified attributes.

Use case:

Situation: As a Project Manager or Test Lead, a I want to see the most unstable place in my product ( application).

Solution: All test cases in my project in ReportPortal have an attributes. For example function: (order, team, configure, administrative), type: (backend, API, Unit, UI), ...., marketstate: (open, close), role: (ProjectManager, Member, Admin) and other. The attributes can be different and dependend on your project needs.

A user can create a Component Health Check Widget and set attribute key = function for the 1st level, for the 2nd -type and for the 3rd - marketstate

So that a user will see on the first level a several groups: order, team, configure, administrative. All groups will contains only test cases with attribute which contain attribute key function. Each group has been grouped by attribute value: order, team, configure, administrative. If a user clicks on the group function: order, the system will show the second level of the widget. All test items on the second level will be contain the attribute function: orderand attributes which contain attribute key: type. And these items will be grouped by attribute values: backend, API, Unit, UI. The same logic will be applied for the next levels.
![image](https://user-images.githubusercontent.com/30413511/76970027-4b452b80-693c-11ea-8329-e9c0ee299b61.png)

**Comment by evjlobanova** [comment]
https://github.com/reportportal/service-ui/issues/1796

**Comment by evjlobanova** [comment]
Closed due to this request relates to the issues #74 and #259.
You can follow the progress on these issues in the mentioned ones.
