### ISSUE TITLE
Please update documentation regarding some features

### ISSUE THREAD

**Issue by dzmitry-lahoda** [reportportal/reportportal#483]
Hi, 

Here I outline various use cases I have seen during my past years on different projects, doing all kinds of automation of quality, for possible applications of RP. Outcomes could be improved documentation, tutorials or separate issues created.

As my home work I did quick look and searches of issues and codes on github and documentation on reportportal.io. Also @DzmitryHumianiuk have answered some of my questions live.

**JIRA integration.**
I know that there is JIRA integration. I have searched documentation. I do not see answers I need.
I need clear outline of what scenarios are supported. I am interested in documentation which allows people to find what interactions are possible, without installing and setup.

**Elastic Search**
I have heard Elastic Search stores Errors. I want tutorial(blog post?) on how to access that data on installed instance of RP. What structure of data is? What are indexes?
This will allow technical persons to answer if they could write custom correlation of failures by stack-error content, time or VM where test were run,  efficiently. So I hope for documentation(blog post?) which describes how data is stored in ES. Another document describing ES configuration, including how to put not only Errors into ES.

**How to call RP from Jenkins**

I need to create custom tags on tests (unstable, validation , etc) and query these back during Jenkins runs. These test should not fail push of code into production by Jenkins even if failed.  If test was good N+ times then Jenkins will call RP to remove tag.

Is is possible to document Jenkins example to call RP from command line?

**Performance measurements**
I have heard all logs are in MongoDb. What about metadata - time, VM, tests tags, etc?
Document how MongoDb data is stored.  Will it be possible to get data for 10k test run 100 times, then average time of each test, then calculate percentage shift of time increased compared with previous period? Will it be efficient query?
Can I filter MongoDB query by tag/description to obtain performance of tests by tags? E.g. tags "performance" + "loading" +"machine_az12rb" to get only runs of part of tests.

I have heard about export into time series database. How would I do that? Documentation. 

**Really cool stuff**

Example of simplest case like:

1. Parse C#/Java code from git.
2. Pare logs of failures. 
3. Analyze C#/Java code to get history of changes and calls via Roslyn/Java parser.
4. Correlated code changes and stack logs. 
5. Output buggy commit. 
6. Killer blog post.

Except finding root causes of issues it will allow to control unstable tests - if stack of test and stack of new code absolutely different than chances these are related are lower, and we see unstable test not related to current work at hand.

If any of these need more than documentation or configuration, please create, if appropriate, issue for each so I and others can vote.

**Comment by DzmitryHumianiuk** [comment]
@dzmitry-lahoda thanks for detailed question.
Down below answers and action items for BA and team:

 - [ ] **JIRA integration capabilities** - @evjlobanova describe as separate doc

 - [ ] **Elastic Search capabilities** in RP - @evjlobanova @pbortnik @avarabyeu describe

 - [ ] **How to call RP from Jenkins** - describe example - @evjlobanova @pbortnik 
it's pretty easy, by sending `curl` requests. 
Valid commands for cli tools you can find at `http://RP-SERVER/ui/#api` page.

- [ ] **Performance measurements** - 
>What about metadata - time, VM, tests tags, etc?

Everything stored in MongoDB for version 1-4.x
With 5.0 version we migrate to PostgreSQL. Because of efficiency

>Will it be possible to get ...

Yes. it's possible. But complicated to implement, and slow to receive this data from DB.
That's the reason to migrate on PG.
In default deployment, DB ports closed, the same relevant for Production instance.
But you can expose it within own instance.

>Can I filter MongoDB query by tag/description to obtain performance of tests by tags? E.g. tags "performance" + "loading" +"machine_az12rb" to get only runs of part of tests.
Hard staff for Mongo, but easy thing for PG.
Can you make it from regular UI - no.
Add extension and make separate calls with it - yes.

**Really cool stuff** this is where we plan to go ^_^

**Comment by MaryiaRymarchyk** [comment]
It seems that ticket is quite outdated. 
I'll close it as no remain actions. However, if there are any objections - ticket can be reopened.
