### ISSUE TITLE
Credentials is clear in docker logs

### ISSUE THREAD

**Issue by stephanemartin** [reportportal/reportportal#626]
**Describe the bug**
Credentials is clear in docker logs

**Expected behavior**
The login and password must not be present in logs

I propose to use post with www-form-urlencoded for credentials. So they will be not present in server logs.
Maybe you have better practice to avoid that :)

**Screenshots**
![bugportal2](https://user-images.githubusercontent.com/3063721/58236823-07958b80-7d44-11e9-86e3-725cea1d9cd1.png)

**Versions:**
 - Ubuntu 18.04.1 /docker 18.06.1-ce, chrome 74
 - Version of RP  Analysis Service: 4.3.0; API Service: 4.3.4; Index Service: 4.2.0; Authorization Service: 4.2.0; Service UI: 4.3.6;

**Comment by naddison** [comment]
*Bump*, plain text credentials in a payload is already a huge web security 101. At least even base64 encoding them is better than nothing.

What makes plain text passwords and usernames go from bad 101 to *this is reallllly bad* they are being passed as query params! These will show up in *any* logger along the path of traffic. 

Can someone please comment and tell me this is changed/fixed in V5?

**Comment by goodbomb** [comment]
This is a HUUUUGE problem. How did anyone think this was an acceptable approach for authentication? This is the worst possible way authentication could be implemented. We went ahead and started using ReportPortal because it looked like an amazing out-of-the-box solution, but after getting everything set up and deployed, we hooked up Active Directory only to notice that not only were credentials being passed through in plain text format, they were sent as query params! Ho-lee-shit.

Can someone PLEASE look at this and get a fix in asap? This is an enormous security problem.

**Comment by nami-varthakavi** [comment]
This is a massive risk to all of the people hooking on to report portal by making their credentials out in public traffic. This will be like a BIGGG Noooo to not hook on to Report portal. 
Please fix this asap!!!!!!

**Comment by DzmitryHumianiuk** [comment]
No worries guys.
Will take as priority zero tomorrow

**Comment by goodbomb** [comment]
Much appreciated @DzmitryHumianiuk !

**Comment by DzmitryHumianiuk** [comment]
## **`Resolution:Fixed`**

@stephanemartin @naddison @goodbomb @nami-varthakavi fixed in version 5.
Also will be added to v4 (it will be last and final release for v4)

Now login/pass  transmitted in request body, rather than in URL.
it also will not appear in docker logs after it.

you can double check UI at https://beta.demo.reportportal.io/ (beta-beta-v5 rollout).
compose for v5 available here: https://github.com/reportportal/reportportal/blob/v5/docker-compose.yml _**but as for today, it is under active stabilization_

and we will not hash or encode login/pass in request body, because of: https://security.stackexchange.com/questions/8596/https-security-should-password-be-hashed-server-side-or-client-side

We still will distribute HTTP version, along with HTTPS.
- HTTP for demo/play usage
- HTTPs for production usage

Production usage should have HTTPS, enabled Content-Security-Policy.

**Comment by goodbomb** [comment]
Thanks for the quick turnaround @DzmitryHumianiuk !

**Comment by stephanemartin** [comment]
@all Thanks !

**Comment by nami-varthakavi** [comment]
Hi, in which version in V4 this fix will be available?
