### ISSUE TITLE
RP Launches do not terminate upon SIGKILL of the test execution

### ISSUE THREAD

**Issue by ehaelyon** [reportportal/reportportal#661]
Hi,
It seems like the launches status remain In-Progress when I kill my pytest test run
It looks like there is no timeout which is defined for the launch to understand that its connection with pytest handler is gone - I kill my local test run from the PyCharm, the launch will keep continue forever until I finish it manually
...

The RP UI should know when a test is terminated by force and automatically stop the launch after some period of time (5 minutes timeout or something)
...

**Screenshots**
<img width="1136" alt="Screen Shot 2019-07-16 at 1 38 29" src="https://user-images.githubusercontent.com/37264867/61253879-3ee44f80-a76b-11e9-9faa-0eeff7f3a72a.png">
<img width="1531" alt="Screen Shot 2019-07-16 at 1 39 10" src="https://user-images.githubusercontent.com/37264867/61253881-3ee44f80-a76b-11e9-8bdc-01ed188b7907.png">

**Versions:**
 - OS: macOS Mojave (version 10.14.3)
 - Browser: Chrome
 - Version of RP: 4.3.0

**Comment by DzmitryHumianiuk** [comment]
@ehaelyon RP should receive `FinishLaunchRQ`, in order to finish launch on UI.
If process killed, then no one sends it to server.

In project settings you can find `Launch inactivity timeout`
minimal = 1h

![image](https://user-images.githubusercontent.com/11332788/62660559-05bc8b00-b977-11e9-8732-7e7ef73fe79c.png)

![image](https://user-images.githubusercontent.com/11332788/62660575-110fb680-b977-11e9-8f9f-19e095ffb324.png)

**Comment by ehaelyon** [comment]
Hi,
Thanks a lot! I figured that few days after opening the bug and forgot to close it
Thanks for your reply! :)
