### ISSUE TITLE
Issue with v1/dn_personal/item API request[v5bug]

### ISSUE THREAD

**Issue by ehaelyon** [reportportal/reportportal#678]
Hi,
I think that there is an issue with the POST of `v1/dn_personal/item` API - It seems like it cannot find any launch id even if it exists
Here is the launch info from the `/v1/{projectName}/launch/{launchId}` API request
```
{
  "owner": "dn",
  "share": false,
  "description": "",
  "id": 7,
  "uuid": "5fff98ea-0d53-40b4-b8e5-430e2776d075",
  "name": "EdenLaunch",
  "number": 1,
  "startTime": 1564690293530,
  "lastModified": 1564690777680,
  "status": "IN_PROGRESS",
  "statistics": {
    "executions": {},
    "defects": {}
  },
  "attributes": [],
  "mode": "DEFAULT",
  "analysing": [],
  "approximateDuration": 0,
  "hasRetries": false
}
```
as you can see the id of the launch is 7
Here is the result when I try to create a test suite under the launch with the API request `v1/dn_personal/item`
```
{
  "errorCode": 4041,
  "message": "Launch '7' not found. Did you use correct Launch ID?"
}
```

**Comment by DzmitryHumianiuk** [comment]
@ehaelyon try to send requests with `uuid` instead of `id`.
Not a straight forward approach :)

We plan to update it

**Comment by DzmitryHumianiuk** [comment]
@Eden Haelyon this is not obvious way to report data.
works as desired, but really hard to understand at the first look.

*We plan to refactor it before 5.0 final.*

*the idea is next:* we moving all reporting from synchronous controllers to complete ashync.
Since reported item in async mode is not guaranteed to be recorded in DB in runtime, it will go to the queue (RabbitMQ). And API threads will read the queue and post data in DB.
Since all items(child) in queue, send for specific launch(parent), are not guaranteed that launch(parent) already recorded in DB and has DB_ID, we generate `uuid` for them, at the moment of sending, by client side.
and queue use these uuids for reference to the item.

we also will add support for DB-id reference

**Comment by DzmitryHumianiuk** [comment]
@ehaelyon see #684

**Comment by z41** [comment]
Same issue with wdio5 integration. It uses a fork https://github.com/BorisOsipov/reportportal-js-client instead of official client (https://github.com/reportportal/client-javascript) for some reason.
Will this be fixed in Report portal api? Or should be client fixed as well?

**Comment by z41** [comment]
Please, ignore the above. I was suggested to use beta-versions of wdio plugin / service where all is fixed:

"wdio-reportportal-reporter": "5.1.0-beta",
"wdio-reportportal-service": "5.1.0-beta"

**Comment by DzmitryHumianiuk** [comment]
#684

**Comment by nvborisenko** [comment]
I faced the same issue: GET api/v1/{project}/launch/{id}
It returns new model, with new properties, and modified properties.

https://github.com/reportportal/reportportal/issues/684#issuecomment-525856866
