### ISSUE TITLE
Hashicorp Consul Web UI and API access vuln-High Vuln

### ISSUE THREAD

**Issue by ChitraLekhaBHeemana** [reportportal/reportportal#683]
Noticed "Hashicorp Consul Web UI and API access vuln 8500/tcp"  Vulns found with recent Scan.

**Comment by DzmitryHumianiuk** [comment]
@ChitraLekhaBHeemana default deployment config is not meant to be production ready.
It is demo setup, which has port opened by default, in order to simplify troubleshooting.

Production deployment should have 8500 port closed.

AND
Consul is relevant for v4 version.
V5 of ReportPortal will not have Consul any more.

Does it make sense?

**Comment by DzmitryHumianiuk** [comment]
## Resolution: hide exposed ports

**v4**
- [ ] hide exposed ports in docker-compose

**v5**
- [x] consul removed
- [ ] hide ports for elastic, rabbitMQ, etc.

**Comment by evjlobanova** [comment]
@AlehB could you please check if 2nd point for v5 from Dima`s message has been already done?

**Comment by AlehB** [comment]
Production-ready installation type of ReportPortal 5.x is Kubernetes
https://reportportal.io/docs/Deploy-with-Kubernetes

It does not expose the ports by default

**Comment by avarabyeu** [comment]
Hashicorp consul is not part of RP v5 anymore
In case Consul Web UI is considered vulnerable by some third-party security scan, port should not be exposed (just comment 8500:8500 in docker-compose.yml).
