### ISSUE TITLE
Field 'startTime' should not be null

### ISSUE THREAD

**Issue by maluyvova** [reportportal/reportportal#684]
**Describe the bug**
...
22:01:17.437 [main] DEBUG io.github.bonigarcia.wdm.BrowserManager - Creating instance of class io.github.bonigarcia.wdm.ChromeDriverManager
22:01:17.693 [rp-io-0] ERROR com.epam.reportportal.service.Launch - [18] ReportPortal execution error
com.epam.reportportal.exception.ReportPortalException: Report Portal returned error
Status code: 400
Status message: Bad Request
Error Message: Incorrect Request. [Field 'startTime' should not be null.] 
Error Type: null

	at com.epam.reportportal.service.ReportPortalErrorHandler.handleError(ReportPortalErrorHandler.java:83) ~[client-java-4.0.10.jar:?]
	at com.epam.reportportal.service.ReportPortalErrorHandler.handle(ReportPortalErrorHandler.java:59) ~[client-java-4.0.10.jar:?]
	at com.epam.reportportal.restendpoint.http.HttpClientRestEndpoint$1.subscribe(HttpClientRestEndpoint.java:517) [client-java-4.0.10.jar:?]
	at io.reactivex.internal.operators.maybe.MaybeCreate.subscribeActual(MaybeCreate.java:45) [rxjava-2.1.16.jar:?]
	at io.reactivex.Maybe.subscribe(Maybe.java:4096) [rxjava-2.1.16.jar:?]
	at io.reactivex.internal.operators.maybe.MaybeCache.subscribeActual(MaybeCache.java:77) [rxjava-2.1.16.jar:?]
	at io.reactivex.Maybe.subscribe(Maybe.java:4096) [rxjava-2.1.16.jar:?]
	at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeTask.run(MaybeSubscribeOn.java:54) [rxjava-2.1.16.jar:?]
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38) [rxjava-2.1.16.jar:?]
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26) [rxjava-2.1.16.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
22:01:17.700 [rp-io-0] DEBUG com.epam.reportportal.utils.SubscriptionUtils - Launch file create successfully completed
**Expected behavior**
...
dependencies:
<artifactId>agent-java-testng</artifactId>
            <version>4.2.1</version>
<artifactId>client-java</artifactId>
            <version>4.0.16</version>

**Screenshots**
If applicable

**Versions:**
 - Mac OS, Chrome
 - version: '2.4'

**Comment by DzmitryHumianiuk** [comment]
@maluyvova do you work with v5 of RP?

**Comment by rupamchakraborty** [comment]
@DzmitryHumianiuk -  I am also facing the same problem, though mine is Nunit Report Portal.  Please check image attached below.
I'm using Nunit - 3.12 ,  ReportPortal.Nunit - 3.7.7  along with NunitConsole - 3.8  Nuget pkg

Please suggest a way forward

![image](https://user-images.githubusercontent.com/27431386/62534330-850e6980-b866-11e9-903c-b60e7b68e03d.png)

**Comment by maluyvova** [comment]
@DzmitryHumianiuk yes I'm using v5 of RP

**Comment by nvborisenko** [comment]
API interface is broken in v5. The `start_time` property was renamed to `startTime`. The same for `end_time`. I guess all agents are affected, that's weird.

I am as agent/client contributor don't know what is the best way how to upgrade packages and make it backward compatible in silent mode.

**Comment by nvborisenko** [comment]
Is it time to introduce `api/v2`?

**Comment by maluyvova** [comment]
@DzmitryHumianiuk  @nvborisenko  any workaround?

**Comment by vlinsw** [comment]
I also encountered this problem, how to solve it?

**Comment by DzmitryHumianiuk** [comment]
@maluyvova @rupamchakraborty @nvborisenko @vlinsw 

v5 beta access opened for review of ui and functionality, which will be available soon.
As i mentioned in Slack, **agents will be updated to v5, once we have finalize Api for v5 reporting.**

2 dedicated persons conduct performance testing and improvements for async reporting in v5 right now. There was few last-minute changes in v5, that's why we decided not to show v5 agent updates, since they will be changed.

**V5 API version will not be compatible with v4 agents.**
Since async reporting brings tons of changes, and changes approaches for data consistency.
Thus, if we will make changes in agents, we decided to change params object according to the naming conventions as well (reference to `start_time/startTime`, etc.)

V5 Api will require more parameters in requests, but still will have the same list of controllers (launch controller, item controller, logs controller, etc.)
**Once we finalize performance improvements - we will share documentation which will represent side-by-side comparison of v4 requests and v5 requests.**
Few highlights:
- user/client access token will be renamed into `token`, instead of `UUID`
- each object (launch, testItem, log, etc.) will have unique object ID (so called `uuid`) generated on client side, and added into RQ
- data consistency (relation) will be built on top of `uuid`s, stored in queues
- once data object recorded in DB it will have db-object-id, which will be used for synchronous calls by UI
- UI will show data, based on DB ids (reference to the issue #678 )


![image](https://user-images.githubusercontent.com/11332788/62635008-8790c200-b93f-11e9-9bee-9ff5fd76cb1f.png)


We already have `api/v2` for async controllers
![image](https://user-images.githubusercontent.com/11332788/62634941-6a5bf380-b93f-11e9-9d13-4c132861dd91.png)

**Comment by maluyvova** [comment]
@DzmitryHumianiuk that's fine, but on official ReportPortal website you provided how to install V5 which is not working at this moment, can anyone as an alternative provide instruction on how to install V4?

**Comment by dagansandler** [comment]
I'm not really sure I understand. If async controllers are under API/v2, why does v1 need to change? That's a weird decision that is going to make it impossible to upgrade without service interruption.  
Since you guys are providing RP as SaaS as well, I'm not sure how you intend to upgrade without interference.... A simple roadmap or explanation would help here...

To clarify what I mean - imagine someone currently has an RP server running v4 with 100 different users using it, all running v4 clients.
Once the RP server upgrades to v5, all clients will immediately break, causing unnecessary service interruption and mandating that **every** user updates their clients at a very short timespan that they can't control if they don't want to lose results being reported.
If they upgrade their clients to v5 before server upgrade they will break, if they upgrade after, they will also break.
If anyone is currently using RP as part of their CI processes or considering it, this makes it highly unappealing to continue doing so...

**Comment by DzmitryHumianiuk** [comment]
@maluyvova do the same, just use v4-based `docker-compose.yml`
https://github.com/reportportal/reportportal/blob/0a3f91a9f69d89605e0d6d4cf0305a82a188b453/docker-compose.yml

Will update documentation accordingly.

thank you

**Comment by DzmitryHumianiuk** [comment]
@dagansandler i agree with you statement.
That's why we don't release v5 api specifications.

we will brainstorm how to make this smooth.

**Comment by goblinmaks** [comment]
@DzmitryHumianiuk When we can expect work finalization for V5 api ?
@nvborisenko Maybe you can deploy prerelease version with alpha/beta prefix of ReportPortalClient package. Looks like need to change only Names of DataMember in DTOs of client. As workaround peoples can manually install correspond version of ReportPortalClient for V5 api.

**Comment by evjlobanova** [comment]
Backward compatibility has been added for agents v4

**Comment by gksangepu** [comment]
Hi, 
I'm using the "api version: 4.3.4" still seeing the same issue. 

`Error: Request failed with status code 400: {"error_code":4001,"message":"Incorrect Request. [Field 'startTime' shouldn't be null.] "}`

Complete Error log:
`[16:32:17] I/launcher - Running 1 instances of WebDriver
[16:32:17] I/direct - Using ChromeDriver directly...
Jasmine started
Error: Request failed with status code 400: {"error_code":4001,"message":"Incorrect Request. [Field 'startTime' shouldn't be null.] "}
    at /path/to/node_modules/reportportal-client/lib/rest.js:27:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:20286) UnhandledPromiseRejectionWarning: Error: Request failed with status code 400: {"error_code":4001,"message":"Incorrect Request. [Field 'startTime' shouldn't be null.] "}
    at /path/to/node_modules/reportportal-client/lib/rest.js:27:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:20286) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:20286) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
The program is paused and stopping the program
(node:20286) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 3)
(node:20286) UnhandledPromiseRejectionWarning: Error: Request failed with status code 400: {"error_code":4001,"message":"Incorrect Request. [Field 'startTime' shouldn't be null.] "}
    at /path/to/node_modules/reportportal-client/lib/rest.js:27:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:20286) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)`

**Comment by DzmitryHumianiuk** [comment]
@gksangepu it means that you use Agent libraries of version 5 with RPv4.

downgrade to rp js libs, which will start with major version 4.
e.g. 4.x.x

**Comment by gksangepu** [comment]
@DzmitryHumianiuk   downgrading to 4.0.0 works. Thanks.
 But _agent-js-jasmine_ latest (3.0.0) is dependent on _reportportal-client: ^5.1.0_. I have to downgrade the _agent-js-jasmine_ version to 2.0.1. 

Is there a way to use the latest _agent-js-jasmine_  and _reportportal-client: 4.X.X_ ?

**Comment by DzmitryHumianiuk** [comment]
@gksangepu we do not plan to make back support for libraries made for RPv4.

Team focused to make it stable for newly release version of RPv5.

**Comment by narayananpalani** [comment]
I have reporportal older version used in docker hence wdio repo has wdio v4 which is yet to get upgraded. On the other hand my cypress v8 tests failing to connect rps for a simple reason of startTime change from start_time. This is one of the useless idea to stop backward compatibility hence i have really no clue on when i can get my cypress tests connected to reportportal. By the look of it, I need to upgrade wdio to v7 ,get rps above v5 and get the cypress tests connect to rps service after that..long way to go. hmm

**Comment by DzmitryHumianiuk** [comment]
Hi all,

During the transition to a radically new version 5, with complete redesign under the hood, we had to find a compromise between preserving the old accumulated problems and transferring this legacy to the next versions. 
Or getting rid of them and updating new clients for the changed API.

Our choice was made in the direction of getting rid of the accumulated issues and reworking the connected agents (framework connectors). 
Since it is both faster and cheaper, and in any case, changes in the agents had to occur in order to support the new functionality.
Therefore, the choice was made. It wasn't an easy choice. And the price for switching to a new architecture was some incompatibilities with old adapters.

In particular, changing `start_time` to `startTime` was not a key change, but was only a point related to building the correct naming of objects across a whole codebase. The change of this field was addressed in the updated clients for each platform. Which appeared simultaneously with the release of version 5.

However, Some integrations are made by contributors, and are not the direct responsibility of our team. 
In this case, we expect updates from community. And for our part, we distribute instructions on required changes.

**Until now and from now on, we are guided by a simple rule: the major digit of the client version must match the ReportPortal version.**
Example:
client-java 4.x compatible with ReportPortal v4.x.x
client-java 5.x compatible with ReportPortal v5.x.x
etc.
