### ISSUE TITLE
How to Rename the Launch Name - Each time a iteration number is getting appended

### ISSUE THREAD

**Issue by SrikanthSunder** [reportportal/reportportal#690]

**Comment by DzmitryHumianiuk** [comment]
@SrikanthSunder can you specify more details?

**Comment by SrikanthSunder** [comment]
@DzmitryHumianiuk  For instance, if i trigger a run under Project with Launch Name as Integration, when each run is made i'm getting Integration#1, Integration#2, Integration#3 etc.,
Is there any way to override this lauch name with Customized name and also, how to remove the iteration numbers?

**Comment by DzmitryHumianiuk** [comment]
@SrikanthSunder you can define name for launch in properties file, prior to execution start.

You can also bypass command line Params for java based clients as `-Drp.launch=xxx` this will override name from property file.
You also can edit parameters in properties file by Jenkins pre-step, simply wringing launch name into it.

In version 5 we will allow to edit launch name on UI and by separate API request.

But launch number will not be removed.
It is RP internal thing, and used by ReportPortal engine.

**Comment by johnharnabi** [comment]
Hello. Can I ask where a "properties file" you a talking about is? 
I use WebdriverIo, and it has all configs in a one place, like:

> const conf = {
  reportPortalClientConfig: {
    token: '00000000-0000-0000-0000-00000000000',
    endpoint: 'https://reportportal-url/api/v1',
    launch: 'launch_name',
    project: 'project_name',
    mode: 'DEFAULT',
    debug: false,
    description: "Launch description text",
    tags: ["tags", "for", "launch"],
  },
  reportSeleniumCommands: false,
  autoAttachScreenshots: false,
  seleniumCommandsLogLevel: 'debug',
  screenshotsLogLevel: 'info',
  parseTagsFromTestTitle: false,
};

Can you describe in more details which properties you mean and how I can handle the launch renaming?

**Comment by RG108** [comment]
@DzmitryHumianiuk  
Continuing the discussion here, I have taken the below PR submitted by Prashant Patil to another level :
https://github.com/workwithprashant/karate-reportportal-demo/releases

1. Enabled parameterised environment (Karate-config.js support)
 2.Package based Execution - Report Portal will send notification post completion of packages which are basically kept in src/test/java
Now, the problem comes when I wish to send a single notification if I want to have multiple environments. Currently, Report Portal sends notification based on the no of environments.
I tried clubbing all the features into common package with multiple testparallel() methods in single testrunner class but that worked out but the results were not published properly in Report Portal.
And I get multiple notification also.
As we are going with concurrent threads here , can we share launch id with 2nd package as soon as execution finishes with 1st package and so on ?
 I see that instanceUUID which ReportPortal class uses has caching used so is there something I am missing here ?

Another issue if the above is not possible then can we use variable in the name of rp.launch name for each package under a project.
Please suggest !
Thanks in advance !
