### ISSUE TITLE
Widget legend - pins color

### ISSUE THREAD

**Issue by serhiisavruk** [reportportal/reportportal#7]
After adding new defect type I got inappropriate color of pins on my widgets.
<img width="632" alt="screen shot 2016-11-17 at 6 06 53 pm" src="https://cloud.githubusercontent.com/assets/1574658/20397276/d2e358e2-acf1-11e6-9aec-beef744d0f2b.png">
<img width="721" alt="screen shot 2016-11-17 at 6 07 11 pm" src="https://cloud.githubusercontent.com/assets/1574658/20397277/d2e79132-acf1-11e6-9b4f-8ff9a30a0c29.png">

**Comment by DzmitryHumianiuk** [comment]
@serhiisavruk i'm not really sure, that i've got your issue write.
Could you please give more details?
since i can't see any inappropriate behavior within you screenshots

**Comment by serhiisavruk** [comment]
Let me explain in other words.
I've got such results:
```
x2 System Issue (blue)
x1 Automation Bug (yellow)
x32 Passed (green)
```

However colors of pins are different from graph:
```
System Issue (orange), like 'To Investigate'
Automation Bug (lime), like 'IE Issue'
Passed (red), like 'Production bug'
```

**Comment by e-olga** [comment]
@serhiisavruk 
The issue is caused by specific of library 'nvd3' that we used for creating widgets.
If number of defect>0, the area is available on the chart and pin color is the same as defect color.
If number of defect=0, the area is not shown on widget, but the pin is and overlapped the previous one.
Refer to your screenshot, for instance, the area refers to 'System issue' (in blue), but its pin is overlapped by 'IE Issue' and 'To Investigate' pins.
So, the last is shown on the graph.

**Comment by e-olga** [comment]
The issue submitted to https://github.com/novus/nvd3/issues https://github.com/novus/nvd3/issues/1876
