### ISSUE TITLE
Install report portal on OpenShift

### ISSUE THREAD

**Issue by nkthota** [reportportal/reportportal#702]
can we install report portal on openshift? If so can you please point me to the installation instructions.

**Comment by arunkumar-muthusamy** [comment]
There is one for Kube. I believe it can quite possibly work for OpenShift with some conversion/tweaks.

[https://github.com/reportportal/kubernetes](https://github.com/reportportal/kubernetes)

**Comment by h4wkmoon** [comment]
Hi, 
I'm currently working on that. I choose to use external pgsql, external elastic, external rabbitmq.
RP pods are working except the api.

The api pod log ends with :

> 
> 2019-11-25 08:25:48.167  INFO 1 --- [           main] org.quartz.core.QuartzScheduler          : Scheduler meta-data: Quartz Scheduler (v2.3.1) 'reportportal' with instanceId 'api:3bdcdb5e80cf2c8de57df02aa7d461e5'
> --
>   | Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
>   | NOT STARTED.
>   | Currently in standby mode.
>   | Number of jobs executed: 0
>   | Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 1 threads.
>   | Using job-store 'org.springframework.scheduling.quartz.LocalDataSourceJobStore' - which supports persistence. and is clustered.
>   |  
>   | 2019-11-25 08:25:48.167  INFO 1 --- [           main] org.quartz.impl.StdSchedulerFactory      : Quartz scheduler 'reportportal' initialized from an externally provided properties instance.
>   | 2019-11-25 08:25:48.167  INFO 1 --- [           main] org.quartz.impl.StdSchedulerFactory      : Quartz scheduler version: 2.3.1
>   | 2019-11-25 08:25:48.168  INFO 1 --- [           main] org.quartz.core.QuartzScheduler          : JobFactory set to: com.epam.ta.reportportal.core.configs.SchedulerConfiguration$1@520ec7a7
> 
> 
and then nothing.
The pod ends being orange (5 minutes without health check )
In the api pod, nothing listens on port 8585.

As for route, I've set : 
/ ==> ui service
/api => api service
/uat => uat service

Authentication does not seem to function. When I try to use default/1q2w3e, the uat log indicates that the login is "anonymous". The ui gets "access denied".

I think I'm almost there but I miss a few things I can't get to work because I don't rp well enought yet. Can someone help us with the last tweaks, plz ?

**Comment by h4wkmoon** [comment]
useful info : this is v5.
I've just noticed that v5 is 5.0.0-RC-2. 
I'm switching to v4.

**Comment by DzmitryHumianiuk** [comment]
Closed as duplicate in honor of #715
