### ISSUE TITLE
[v5bug]Launch does not finish C#; NUnit

### ISSUE THREAD

**Issue by tuscias** [reportportal/reportportal#738]
**Describe the bug**
Launch is left in progress after tests finish running
**To Reproduce**
Open nunit-example project
run tests
check report portal 
launch is in progress

**Expected behavior**
Launch should close after tests finish running

**Other Info**
multiple API calls fail as issue type is not found
message=Test items issue type cannot be resolved. Invalid test item issue type definition 'ND001' is requested. Valid issue types' locators are: [ti001, ab001, pb001, nd001, si001]

**Comment by evjlobanova** [comment]
@nvborisenko Could you please help with the issue?

**Comment by vitali-sonchyk-epam** [comment]
@tuscias , could you please provide some more details?
Which instance of rp do use to log the results?

**Comment by tuscias** [comment]
on v5 beta it is failing
on v4 it is passsing 
i used https://github.com/reportportal/example-net-nunit repo for test execution

To be precise error occurs when test has status SKIPPED and this line is executed: https://github.com/reportportal/example-net-nunit/blob/master/src/Example/ReportPortalCustomization/Customization.cs#L25

I guess that on v4 issue type search is case-insensitive and on v5 case-sensitive.

HTH
Tomas

**Comment by vitali-sonchyk-epam** [comment]
@evjlobanova , @tuscias is right, this is an API issue, Issue types became case-sensitive,
nunit-agent is sending ND001 value as issue type type to put -> test-item-controller,
now in v5 controller rejects the request with this value.

Due to that nunit-agent is not able to finish the launch:  Cannot finish launch due finishing of child items failed.
Looks like, issue of report portal, not on the agent side.

**Comment by pbortnik** [comment]
Hi guys, yeah. Issue type will be made case-insensitive.

**Comment by pbortnik** [comment]
Will be fixed in 5.0-Final version on the backend side.
