### ISSUE TITLE
Possiblity to view the browser the test has run on

### ISSUE THREAD

**Issue by stevedc1989** [reportportal/reportportal#750]
As I run my test on mulitple browser (chrome,firefox,IE and Edge) it would be nice if there is an option or a way to give the browser and maybe the version to the reportportal. This in orde if a test failing is because of a specific browser/version or not.

**Comment by evjlobanova** [comment]
@stevedc1989 we are planning to introduce a view with executions of one test case on different envs (scope, browsers or others) #315

For npw, in **version 5.0** (now beta version is available for user testing) we replaced `tags` with `attributes`. Attribute has two parts `key` : `value` .
So that you will be able to report test results with attribute for instanse `browser:chrowe` or `browser: edge` and so on.
And also we added a widget `Component health check`, which shows statistics for chosen key
![image](https://user-images.githubusercontent.com/30413511/69231266-d8988f00-0b99-11ea-8711-b10babb33c83.png)


In version 4 you can add this info to the description or to the `tags` and check this info on log view.

Does this functionality cover your needs?
