### ISSUE TITLE
[FR] Add ability to assign test ownership for the existing tests

### ISSUE THREAD

**Issue by 501NotImplemented** [reportportal/reportportal#783]
As a user with a manager permission role, I would like to have the ability to assign the users from the project members list as "test owners" for the existing tests, so they would be responsible for maintaining and analyzing them.

**Comment by evjlobanova** [comment]
@501NotImplemented we are planning to introduce this feature in future version - 6.0.


Now there is no such function, but we are planning to do it in future plans.
If you use version 4. You can use `tags` for this reason, add `tag` to the test items, and then filter by them.
Or you can add info about an assignee to the `Defect comment`.

If you are using version 5, instead of tags you can use `attributes`


And also you can create a `custom defect types` for different assinee, for example To Investigate by Basil and etc, and add this defect type to test items

![image](https://user-images.githubusercontent.com/30413511/71477076-1cb22b80-27f9-11ea-8445-0e4f5e2f27f8.png)
1. Attributes
2. Deffect comment
3. Custom To investigate

**Comment by evjlobanova** [comment]
Duplicate #71 
All updates and progress regarding this feature you can find in the mentioned issue.
