### ISSUE TITLE
Test launch doesn't finish despite all tests are finished

### ISSUE THREAD

**Issue by hs-mzaretski** [reportportal/reportportal#795]
**Describe the bug**
Test launch in RP doesn't finish but in launch all tests finished. Also on SauceLabs where all tests run this launch finished already. In addition to this, one test wasn't send to the RP. On SauceLabs tests amount is 214 but on RP 213 only

**Expected behavior**
Test launch in RP finished as soon as all tests from the launch finished

**Screenshots**
<img width="501" alt="RPBug" src="https://user-images.githubusercontent.com/56677471/72143117-2e720200-33a7-11ea-8679-db4b2da4c86b.PNG">

<img width="77" alt="RPNumberOfTests" src="https://user-images.githubusercontent.com/56677471/72143173-48abe000-33a7-11ea-8453-a520f703c903.PNG">

<img width="510" alt="SauceLabsTestsFinished" src="https://user-images.githubusercontent.com/56677471/72143157-4184d200-33a7-11ea-81c3-3c93a6c126e6.PNG">

**Versions:**
 - OS: Windows 10, Browser: Chrome
 - Version of RP : Current version: Analysis Service: 4.3.0; API Service: 4.3.11; Index Service: 4.2.0; Jira Service: 4.3.0; Rally Service: 4.3.0; EPAM Authorization Service: 4.2.1; Service UI: 4.3.7;

**Comment by DzmitryHumianiuk** [comment]
@hs-mzaretski do you have logs of test automation itself available?

it will bring some light on issue root

**Comment by hs-mzaretski** [comment]
> @hs-mzaretski do you have logs of test automation itself available?
> 
> it will bring some light on issue root

Where I can find logs?

**Comment by DzmitryHumianiuk** [comment]
@hs-mzaretski your test automation logs. any console output.
you can search for anything like `.ReportPortal.`

**Comment by arybkin** [comment]
Hello guys. Here are two questions:
@hs-mzaretski  - do you have any parametrized tests in your run? Just to identify for myself is it the same problem or not for me.

@DzmitryHumianiuk  Have you updated something on rp.epam for the last couple days?

I have had issue with not finished test runs since 13 of January evening. Next errors are in logs:
Finishing to send the results to Report Portal... ReportPortal exception was thrown.
System.AggregateException: Cannot finish launch due finishing of child items failed. ---> System.AggregateException: One or more errors occurred. ---> System.AggregateException: Cannot finish test item due finishing of child items failed. ---> System.AggregateException: One or more errors occurred. ---> System.AggregateException: Cannot finish test item due finishing of child items failed. ---> System.AggregateException: One or more errors occurred. ---> System.AggregateException: Cannot finish test item due finishing of child items failed. ---> System.AggregateException: One or more errors occurred. ---> System.AggregateException: Cannot finish test item due finishing of child items failed. ---> System.AggregateException: One or more errors occurred. ---> System.AggregateException: Cannot finish test item due finishing of child items failed. ---> System.AggregateException: One or more errors occurred. ---> System.AggregateException: Cannot finish test item due finishing of child items failed. ---> System.AggregateException: One or more errors occurred. ---> System.AggregateException: Cannot finish test item due finishing of child items failed. ---> System.AggregateException: One or more errors occurred. ---> System.AggregateException: Cannot finish test item due finishing of child items failed. ---> System.AggregateException: One or more errors occurred. ---> System.AggregateException: Cannot finish test item due finishing of child items failed. ---> System.AggregateException: One or more errors occurred. ---> System.Exception: Cannot finish test item due 00:01:40 timeout while starting it.
   at ReportPortal.Shared.Reporter.TestReporter.<>c__DisplayClass24_0.<<Finish>b__1>d.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at ReportPortal.Shared.Reporter.TestReporter.<>c__DisplayClass24_0.<<Finish>b__1>d.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at ReportPortal.Shared.Reporter.TestReporter.<>c__DisplayClass24_0.<<Finish>b__1>d.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at ReportPortal.Shared.Reporter.TestReporter.<>c__DisplayClass24_0.<<Finish>b__1>d.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at ReportPortal.Shared.Reporter.TestReporter.<>c__DisplayClass24_0.<<Finish>b__1>d.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at ReportPortal.Shared.Reporter.TestReporter.<>c__DisplayClass24_0.<<Finish>b__1>d.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at ReportPortal.Shared.Reporter.TestReporter.<>c__DisplayClass24_0.<<Finish>b__1>d.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at ReportPortal.Shared.Reporter.TestReporter.<>c__DisplayClass24_0.<<Finish>b__1>d.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at ReportPortal.Shared.Reporter.TestReporter.<>c__DisplayClass24_0.<<Finish>b__1>d.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at ReportPortal.Shared.Reporter.TestReporter.<>c__DisplayClass24_0.<<Finish>b__1>d.MoveNext()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at ReportPortal.Shared.Reporter.LaunchReporter.<>c__DisplayClass21_0.<<Finish>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ReportPortal.Shared.Reporter.LaunchReporter.Sync()
   at ReportPortal.NUnitExtension.ReportPortalListener.FinishRun(XmlDocument xmlDoc)

**Comment by DzmitryHumianiuk** [comment]
@arybkin @hs-mzaretski  simple answer: fixed in v5

**Comment by arybkin** [comment]
@DzmitryHumianiuk  but it worked yesterday and before=). So did you change anything yesterday?

**Comment by nvborisenko** [comment]
@arybkin new versions of agents for c# will try to negotiate this issue. Sometimes http request might be timed out. New versions will just retry requests. It might help. Watch for agent releases.

**Comment by nvborisenko** [comment]
@arybkin please try **ReportPortal.NUnit v3.7.12**. If it doesn't help please create separate issue in [agent-net-nunit](https://github.com/reportportal/agent-net-nunit) repository.

**Comment by arybkin** [comment]
@nvborisenko thanks for your attention. So yesterday it worked for old and new versions of nuget package. Now everything is good for me.

Thanks,
Alex

**Comment by Phanishar** [comment]
Test Launch does not finish in Report portal though the actual Job is Finished in Jenkins. And I see around 476 scenarios passed with only 4 failures in Jenkins but the Report portal is still stuck on 200 scenarios and plus doing nothing. I am seeing only the scenarios that are passed
![Jenkins](https://user-images.githubusercontent.com/61402294/120446678-65cfbd00-c3a7-11eb-856f-289f7154f0e0.png)
https://lh3.googleusercontent.com/-OcdPOdMtxyg/YLcxAI-tYMI/AAAAAAAAAOI/gNVznBI93f8jqwo_FTswGdd_kVeIqiaLACJEEGAsYHg/s0/2021-06-02.png?authuser=0

**Comment by Phanishar** [comment]
Hi Vadzim,
I use the version 5.3.2 and My set of launch is passing in the jenkins but
not in Report Portal it tries to Run and Run.
[image: image.png]

[image: image.png]


These are the two errors .
