### ISSUE TITLE
Greyed out email in project notifications section.

### ISSUE THREAD

**Issue by brianbentson** [reportportal/reportportal#803]
**Describe the bug**
On the notifications settings page for a project the "From" email is greyed out and unchangable from the default `reportportal@example.com`
**Expected behavior**
One should be able to change the email to any email or it should be set to the default email from the email-server settings page in the administrate section.
**Screenshots**
![image](https://user-images.githubusercontent.com/8632096/73007013-80138700-3dc0-11ea-96af-67d805db7969.png)

**Versions:**
 - OSX, Chrome but it appears in all browsers afaik.
 - 4.3.6

**Comment by e-olga** [comment]
hello @brianbentson ,
There is an issue of version 4 of RP. User is not able to update the field from UI side.
To resolve the problem you need to send the API request 
PUT     {host}:{port}/api/v1/project/{projectName}/emailconfig
with body:
{
  "emailCases": [
    {
      "launchNames": [
        "string"
      ],
      "recipients": [
        "string"
      ],
      "sendCase": "ALWAYS",
      "tags": [
        "string"
      ]
    }
  ],
  "emailEnabled": true,
  "fromAddress": "string"//your email address
}

In ***Report Portal v5*** the Email notification page is re-designed: the email address is  applied from the server settings (the same as you wrote in Expected behavior)).

Best Regards,
Olga

**Comment by DzmitryHumianiuk** [comment]
Fixed in version 5
