### ISSUE TITLE
Can't create message with attachment.

### ISSUE THREAD

**Issue by ryzhkovd** [reportportal/reportportal#834]
I'm using ReportPortal.Client 3.0.0-betta.1 nuget package to send logs in to ReportPortal 5.0.
Message without attachment sending normally. When i add attachments to message, only text is displayed.

To send message with attachment i use this code:
```cs
var data = new byte[] { 1, 2, 3 };
CreateLogItemRequest RPmessage = new CreateLogItemRequest
{
 Text = message.Text,
 LaunchUuid = stepuuid,
 Time = DateTime.UtcNow,
 Level = MapMessageLevel(message.Level),
 TestItemUuid = stepuuid,
 Attach = new Attach("file1", "application/octet-stream", data)
};                
 var res = service.LogItem.CreateAsync(RPmessage).Result;
```
res contains uuid. Text of message display in UI but attachment doesn't.

After that I try start unit test from develop branch and CreateLogWithAttach is failed.
In debug i see that field Content is null and test can't get attachments from message.

**Comment by Andrey-Cherepakha** [comment]
The same for me. I use my local instance of RP 5.0. I can see a message but the attachment is not added.

TargetFramework netcoreapp3.1
ReportPortal.NUnit 3.7.13

```
                byte[] screenshot = ((ITakesScreenshot)Driver)?.GetScreenshot().AsByteArray;

                if (screenshot != null)
                {
                    Log.Error("Screen shot on failure.", "image/png", screenshot);
                }
```

**Comment by Andrey-Cherepakha** [comment]
After investigation, we found pout that the problem is on the server side.

@ryzhkovd please check that reportportal_minio_1 container is up. Login to the server and execute 
`sudo docker ps`

There should be a line like

`minio/minio:latest                                        "/usr/bin/docker-ent…"   About an hour ago   Up About a minute (healthy)            0.0.0.0:9000->9000/tcp                                                    reportportal_minio_1`

If minio is not working, start it.

`docker-compose up -d minio reportportal_minio_1`

To be able to start minio after the OS restart you need to add restart: always to the docker-compose.yml (it is missed and it is the root cause) and recreate containers.

**Comment by AlehB** [comment]
Hello,

restart: always policy was added to the Docker Compose file

Best Regards,
Aleh

**Comment by ryzhkovd** [comment]
After recreate minio container all works.
