### ISSUE TITLE
[v5]While doing docker-compose up getting username_minio1 error

### ISSUE THREAD

**Issue by vikasChobey** [reportportal/reportportal#835]
PS C:\Users\vchoubey> docker-compose up -d
vchoubey_elasticsearch_1 is up-to-date
vchoubey_uat_1 is up-to-date
vchoubey_gateway_1 is up-to-date
Starting vchoubey_postgres_1 ...
vchoubey_rabbitmq_1 is up-to-date
vchoubey_ui_1 is up-to-date
vchoubey_index_1 is up-to-date
Starting vchoubey_postgres_1 ... done
Creating vchoubey_minio_1      ... error
Creating vchoubey_api_1        ... done
Creating vchoubey_db-scripts_1 ... done

ERROR: for db-scripts  Container "1ecd0102ffd2" is unhealthy.

**Comment by vikasChobey** [comment]
ERROR: for db-scripts  Container "1ecd0102ffd2" is unhealthy.

**Comment by evjlobanova** [comment]
@AlehB Could you please check?

**Comment by AlehB** [comment]
Hi @vikasChobey ,

Could you please share db-scripts and minio containers logs? We need details to deal with the situation

By the way, since you are running it on Windows did you make the necessary changes for Docker on Windows https://reportportal.io/docs/Deploy-with-Docker%3Edeploy-reportportal-with-docker-on-windows?

Best Regards,
Aleh

**Comment by vikasChobey** [comment]
Above issue has been resolved
