### ISSUE TITLE
Improments for Log page. Add possbility to see error logs with 5 preceding it logs with other log level 

### ISSUE THREAD

**Issue by OrenAutoSmileBox** [reportportal/reportportal#845]
currently, when opening a step to see the log messages we can see 10 log messages and we have the ability to load 10 more each click 

in case of an error that happened after a significant amount of log messages 
we need to load 10 log messages each time in order to get to that error

it will be better we could:
- Jump directly to the error surrounding in order for me to see the preceding log messages 
or
- Click on the log message and it will jump to that message surrounding (that way we can search/filter for the error.. click it.. and see the preceding log messages )
or
- Load more than 10 log messages each time

![Annotation 2020-03-03 141613](https://user-images.githubusercontent.com/52413954/75774883-961a4d00-5d59-11ea-9cb7-b0f9d14067d9.jpg)

**Comment by evjlobanova** [comment]
What do you think if we a little bit change a logic of log view.
We can divide a log view on 2 parts:
- brief information about test: 
      * name, details, history
      * only error (and higher) logs and 5 logs before them
- all logs on one page

![Log view](https://user-images.githubusercontent.com/30413511/75792162-a0027700-5d7e-11ea-8900-423715021e9e.gif)

So that user will see only information about failure immediatly.
And if he needs to deep investigate all logs, he can click on Discover logs and dive through the all logs on one page.

What do you think about this idea?

**Comment by OrenAutoSmileBox** [comment]
It looks like a good idea!
I think it's practical and convenient 

will this be available inside a nested step as well?
on tests without errors, ill see the full log page?

If we are on the subject, I would like to have the ability to click on the log itself and to "jump" to the log surrounding on the full log page.
that way I have the ability to search for certain log messages.. click on them.. and see them with their surrounding logs.
it gives me more control over the navigation between logs

**Comment by MaryiaRymarchyk** [comment]
Hi @OrenAutoSmileBox, sorry for silence.
We have nice updates starting from Version 5.7.3 - you can navigate easily between error messages on log view and jump to the next available Error Log, so that it minimizes efforts to scroll across all the available logs including logs in Nested steps to find next Error log. 
![image](https://github.com/reportportal/reportportal/assets/122868739/c983c304-9ad2-4753-9165-ef0cf2d0168f)

Please let us know if you have more questions or ticket can be closed.

**Comment by MaryiaRymarchyk** [comment]
Hi @OrenAutoSmileBox , As we haven't received a reply from you, we'll close the issue for now.
If  the issue still relevant, just get in touch.
