### ISSUE TITLE
Incorrect valiadtion message when getting launches sorted by startTime

### ISSUE THREAD

**Issue by nvborisenko** [reportportal/reportportal#890]
GET /api/v1/default_personal/launch/?page.page=1&page.size=10&page.sort=start_time,ASC

Response:
message=Sorting parameter start_time is not defined

But `start_time` is defined.

Expected: `startTime`

**Comment by svettsova** [comment]
@evjlobanova issue is reproducible in 5.0 and 5.1 versions

**Comment by evjlobanova** [comment]
@svettsova could you please a defect to the Jira?

**Comment by svettsova** [comment]
done. issue ID - EPMRPP-49764

**Comment by Yumfriez** [comment]
@nvborisenko Fields naming changed from `underscore` to `camel case` since 5.0 version.
So for now it's correct to use `startTime` instead of `start_time`

**Comment by nvborisenko** [comment]
@Yumfriez Right, but service says I should use `start_time`: `Sorting parameter start_time is not defined`

I suppose correct message is `Sorting parameter startTime is not defined`

**Comment by Yumfriez** [comment]
@nvborisenko It is correct to use `startTime` instead of `start_time` according to our API, so when you use `start_time` validation fails and says that this parameter is not defined (because the one that is defined is `startTime`):
![image](https://user-images.githubusercontent.com/31598109/81669548-0b3b8a00-944f-11ea-96a1-2452a5c2ab06.png)

And if use `start_time`, which is incorrect:
![image](https://user-images.githubusercontent.com/31598109/81669771-581f6080-944f-11ea-932c-3b80b4a7df5d.png)

**Comment by nvborisenko** [comment]
You say `startTime` should be defined, API says `start_time` should be defined.

As a user of API I am reading error message as "Sorting parameter start_time is not defined, you should define it because of it's mandatory". Now I understand what `not defined` means, this is `unknown`, `not recognized`.

It's up to you close this issue or change error message, I don't mind.
