### ISSUE TITLE
Not able to login in reportPortal

### ISSUE THREAD

**Issue by agarwlanurag** [reportportal/reportportal#943]
OS : MacOS Catalina v10.15

I have followed all the steps listed for installation but getting an error occured while connecting to server . Can you please help in this.
![Screen Shot 2020-05-03 at 12 53 44 AM](https://user-images.githubusercontent.com/14285773/80899071-8ecfdb00-8cd9-11ea-9f2a-f35884595590.png)

**Comment by evjlobanova** [comment]
![image](https://user-images.githubusercontent.com/30413511/80951617-e1f07d80-8e00-11ea-95f1-1176c8887434.png)
Not all services have been run.
Please waut, and try again

**Comment by DzmitryHumianiuk** [comment]
@agarwlanurag you should have at least 4 services up and running,
which you can see at `Current version` section under login button.

Make 3 thing:
- double check that you did allocate at least 5GB for you docker machine/process
- give 5-10 minutes for services at first cold start for bootstrapping
- see what's statuses with `docker ps` command

**Comment by sudharsan81** [comment]
Hi Anurag,

Most of us who try to install and run report portal face this issue.

Please check is all the services(containers) are Up and running from  `docker ps -a | grep "reportportal_"`. 

However, there is no guarantee that the issue you mentioned will not surface if all the components are up and running.

I have been following issues in this repository and I learn these things over the period of time :
1. Several services keep restarting due to unsatisfied dependencies.
2. Even if you download the latest docker-compose.yml file, you cannot expect a fix.
3. I am so sorry to say that "evjlobanova" is more interested in closing the issue and not allowing the technical discussion to reach a logical conclusion.
4. In login, homepage await for those four mandatory services to appear healthy before you login. 
5. Try the installation in centOS. You "might" succeed.

**Comment by nvborisenko** [comment]
Also I have tried to deploy it locally on windows.

I can say:
- Don't hesitate to allocate more than 3GB ram for docker
- When all services are up, actually they are not up yet. Even if you see healthchecks are passed.
- Wait and wait, try again and again (login page doesn't reflect the current build number, or twitter updates, but main functionality works)

**Comment by sudharsan81** [comment]
Recently I used a specific old version of minio and it worked. In your `docker-compose.yml` file use this image for minio ` image: minio/minio:RELEASE.2020-03-05T01-04-19Z`

**Comment by DzmitryHumianiuk** [comment]
@sudharsan81 the majority of `help wanted` questions are about the same.
people do not read instructions and do no follow all steps in it.

95% of that questions are resolved by proposing to allocate more memory for docker, give correct permissions for elastic and give 10 minutes for microservices to bootstrap.

Our GitHub issues are flooded with similar questions. that's why some of them can be closed without deep details.

**Comment by DzmitryHumianiuk** [comment]
@sudharsan81 minio version fix pushed into compose file

**Comment by sudharsan81** [comment]
Thanks @DzmitryHumianiuk

**Comment by vinod212271** [comment]
OS: Windows 10
I have followed all the steps listed for installation but getting an error bad credentials when login as superadmin . Can you please help in this.
![image](https://user-images.githubusercontent.com/71780239/153008504-9a6a633f-c1cc-44a4-aec7-0a7bcf4efe5c.png)

**Comment by DzmitryHumianiuk** [comment]
@vinod212271 
1. https://github.com/reportportal/reportportal/issues/943#issuecomment-623384656
2. https://github.com/reportportal/reportportal/issues/943#issuecomment-625892043

**Comment by vinod212271** [comment]
I tried after some time with my new superadmin/password. Sign In is successful.
Thanks

**Comment by DzmitryHumianiuk** [comment]
> I tried after some time with my new superadmin/password. Sign In is successful. Thanks

then, as it mentioned in comments, you need to find out what is the state of your containers.
Find its statuses and read logs.
