### ISSUE TITLE
[faq] traefik.port means

### ISSUE THREAD

**Issue by vishallanke** [reportportal/reportportal#945]
What is the meaning of labels -> traefik.port in service section ?
For few services it is 8080, for few 8585 and for few 9999.
What does it indicates ?
Can I change this value ?

**Comment by digaetan** [comment]
quite long to explain...check some Traefik tutorials:
https://github.com/Praqma/learn-traefik

**Comment by avarabyeu** [comment]
@vishallanke in two words, it's port inside docker container a service is running on. Historically and based on developer decisions some services are running on different ports. There is no reason to change those ports since they are not exposed to outside world - the only entrypoint to application is traefik itself:
```
      - --entrypoints.web.address=:8080
```
Hope this helps

**Comment by vishallanke** [comment]
Yes, Thansk a lot
