### ISSUE TITLE
Launch name for widget have unexpected rule

### ISSUE THREAD

**Issue by serhiisavruk** [reportportal/reportportal#95]
I can't add launch name for "Most failure test-cases table" widget, because launch name length should be more equal three. This rule is not used on launch creation, so I have launches with name like "IR".
My launches:
<img width="457" alt="screen shot 2017-03-27 at 3 34 25 pm" src="https://cloud.githubusercontent.com/assets/1574658/24356583/4c70ee00-1303-11e7-8f91-3a0f91e41ac6.png">
Try to add launch to widget:
<img width="843" alt="screen shot 2017-03-27 at 3 34 42 pm" src="https://cloud.githubusercontent.com/assets/1574658/24356587/4d154df6-1303-11e7-89c7-4f370de2c03c.png">

**Comment by e-olga** [comment]
Added to RP backlog

**Comment by DzmitryHumianiuk** [comment]
@serhiisavruk initially works as desired.

will consider to to remove this limitation

**Comment by DzmitryHumianiuk** [comment]
**Statement:**
Limitation with 3 symbols introduced in order to limit number of requests to server.
Single symbol search requires to put in memory a lot of data from collection of launches.

**Solution:**
add any symbol to your launch name, or right in long form.

**Resolution:**
Won't fix. Works as desired.

**Comment by serhiisavruk** [comment]
How about adding length restriction on creating new launch stage?
