### ISSUE TITLE
Migration of Auto-Analyzed data

### ISSUE THREAD

**Issue by priyankachaturvedi30** [reportportal/reportportal#992]
I have setup reportportal instance on my local windows environment using docker. I have been using it for sometime for analysis of my tests runs. The auto-analysis feature is also working for me. Now I want to setup a new instance and migrate this data from my local to new instance. Is it possible to do so without loosing the the Auto-analyzer data ? Please suggest.

**Comment by DzmitryHumianiuk** [comment]
@priyankachaturvedi30 
in order to move ReportPortal data and Auto-Analyzer data into new instance, you should make 2 steps: 

1. Backup PostgreSQL DB data. [Manual](https://www.postgresql.org/docs/12/backup.html)
2. Restore DB within new instance. Open Project Settings -> Auto-Analyzer -> Re-generate Index

API will recreate indexed model, based on information from you database.
